<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Tutorial 3: Sampling and standard errors | Online Textbook for the Learning Line “Quantitative Methods to Understand E&amp;BI”</title>
  <meta name="description" content="An online textbook for the learning line Quantitative Methods within Entrepreneurship and Business Innovation Bachelor Program at Tilburg University." />
  <meta name="generator" content="bookdown 0.47 and GitBook 2.6.7" />

  <meta property="og:title" content="Tutorial 3: Sampling and standard errors | Online Textbook for the Learning Line “Quantitative Methods to Understand E&amp;BI”" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="An online textbook for the learning line Quantitative Methods within Entrepreneurship and Business Innovation Bachelor Program at Tilburg University." />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Tutorial 3: Sampling and standard errors | Online Textbook for the Learning Line “Quantitative Methods to Understand E&amp;BI”" />
  
  <meta name="twitter:description" content="An online textbook for the learning line Quantitative Methods within Entrepreneurship and Business Innovation Bachelor Program at Tilburg University." />
  




  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="b08.html"/>
<link rel="next" href="b09.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

<link rel="stylesheet" href="styles.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="book-title"><a href="./">QM to Understand E&amp;BI</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Welcome</a></li>
<li class="part"><span><b>I QM Basic</b></span></li>
<li class="chapter" data-level="" data-path="basic-course.html"><a href="basic-course.html"><i class="fa fa-check"></i>QM Basic: Course overview</a></li>
<li class="chapter" data-level="" data-path="b01.html"><a href="b01.html"><i class="fa fa-check"></i>Lecture 1: Introduction to Data Analysis</a></li>
<li class="chapter" data-level="" data-path="b02.html"><a href="b02.html"><i class="fa fa-check"></i>Lecture 2: Probability foundations and random variables</a></li>
<li class="chapter" data-level="" data-path="b03.html"><a href="b03.html"><i class="fa fa-check"></i>Lecture 3: Discrete distributions and expectation</a></li>
<li class="chapter" data-level="" data-path="b-ep01.html"><a href="b-ep01.html"><i class="fa fa-check"></i>Tutorial 1: Evidence and probability foundations</a></li>
<li class="chapter" data-level="" data-path="b04.html"><a href="b04.html"><i class="fa fa-check"></i>Lecture 4: Variance, conditioning, and belief updating</a></li>
<li class="chapter" data-level="" data-path="b05.html"><a href="b05.html"><i class="fa fa-check"></i>Lecture 5: Joint random variables, covariance, and correlation</a></li>
<li class="chapter" data-level="" data-path="b-ep02.html"><a href="b-ep02.html"><i class="fa fa-check"></i>Tutorial 2: Conditioning and relationships</a></li>
<li class="chapter" data-level="" data-path="b06.html"><a href="b06.html"><i class="fa fa-check"></i>Lecture 6: Continuous distributions and the normal model</a></li>
<li class="chapter" data-level="" data-path="b07.html"><a href="b07.html"><i class="fa fa-check"></i>Lecture 7: Samples, parameters, and estimators</a></li>
<li class="chapter" data-level="" data-path="b08.html"><a href="b08.html"><i class="fa fa-check"></i>Lecture 8: Sampling distributions and the central limit theorem</a></li>
<li class="chapter" data-level="" data-path="b-ep03.html"><a href="b-ep03.html"><i class="fa fa-check"></i>Tutorial 3: Sampling and standard errors</a></li>
<li class="chapter" data-level="" data-path="b09.html"><a href="b09.html"><i class="fa fa-check"></i>Lecture 9: Confidence intervals and tests against zero</a></li>
<li class="chapter" data-level="" data-path="b10.html"><a href="b10.html"><i class="fa fa-check"></i>Lecture 10: Hypothesis testing, errors, and power</a></li>
<li class="chapter" data-level="" data-path="b-ep04.html"><a href="b-ep04.html"><i class="fa fa-check"></i>Tutorial 4: Inference and tests against zero</a></li>
<li class="chapter" data-level="" data-path="formula-sheet.html"><a href="formula-sheet.html"><i class="fa fa-check"></i>QM Basic Formula Sheet</a></li>
<li class="chapter" data-level="" data-path="basic-mock-exam.html"><a href="basic-mock-exam.html"><i class="fa fa-check"></i>Mock Exam: QM Basic</a></li>
<li class="part"><span><b>II QM Intermediate</b></span></li>
<li class="chapter" data-level="" data-path="intermediate-course.html"><a href="intermediate-course.html"><i class="fa fa-check"></i>QM Intermediate: Course overview</a></li>
<li class="chapter" data-level="" data-path="i01.html"><a href="i01.html"><i class="fa fa-check"></i>Lecture 1: Simple linear regression</a></li>
<li class="chapter" data-level="" data-path="i02.html"><a href="i02.html"><i class="fa fa-check"></i>Lecture 2: Regression assumptions and coefficient inference</a></li>
<li class="chapter" data-level="" data-path="i03.html"><a href="i03.html"><i class="fa fa-check"></i>Lecture 3: Model fit and overall usefulness</a></li>
<li class="chapter" data-level="" data-path="i-ep01.html"><a href="i-ep01.html"><i class="fa fa-check"></i>Tutorial 1: Simple regression and model usefulness</a></li>
<li class="chapter" data-level="" data-path="i04.html"><a href="i04.html"><i class="fa fa-check"></i>Lecture 4: Multiple linear regression and controls</a></li>
<li class="chapter" data-level="" data-path="i05.html"><a href="i05.html"><i class="fa fa-check"></i>Lecture 5: Dummy predictors and joint usefulness</a></li>
<li class="chapter" data-level="" data-path="i06.html"><a href="i06.html"><i class="fa fa-check"></i>Lecture 6: Interactions and polynomial terms</a></li>
<li class="chapter" data-level="" data-path="i-ep02.html"><a href="i-ep02.html"><i class="fa fa-check"></i>Tutorial 2: Multiple regression and extensions</a></li>
<li class="chapter" data-level="" data-path="intermediate-code-sheet.html"><a href="intermediate-code-sheet.html"><i class="fa fa-check"></i>QM Intermediate Code Sheet</a></li>
<li class="chapter" data-level="" data-path="intermediate-mock-exam.html"><a href="intermediate-mock-exam.html"><i class="fa fa-check"></i>Mock Exam: QM Intermediate</a></li>
<li class="part"><span><b>III QM Advanced</b></span></li>
<li class="chapter" data-level="" data-path="advanced-course.html"><a href="advanced-course.html"><i class="fa fa-check"></i>QM Advanced: Course overview</a></li>
<li class="part"><span><b>IV Supplementary resources</b></span></li>
<li class="chapter" data-level="" data-path="r-refresher.html"><a href="r-refresher.html"><i class="fa fa-check"></i>R Refresher</a></li>
<li class="chapter" data-level="" data-path="math-refresher.html"><a href="math-refresher.html"><i class="fa fa-check"></i>Mathematics Refresher</a></li>
<li class="chapter" data-level="" data-path="videos.html"><a href="videos.html"><i class="fa fa-check"></i>External Video Guide</a></li>
<li class="divider"></li>
<li class="book-footer">Quantitative Methods learning line</li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Online Textbook for the Learning Line “Quantitative Methods to Understand E&amp;BI”</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="b-ep03" class="section level1 hasAnchor">
<h1>Tutorial 3: Sampling and standard errors<a href="b-ep03.html#b-ep03" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<div class="outcomes">
<span class="label">By the end of Tutorial 3, you can</span>
<ul>
<li>
identify a valid population and sampling frame;
</li>
<li>
distinguish parameters, estimators, and estimates;
</li>
<li>
calculate standard errors for a mean and proportion;
</li>
<li>
calculate and interpret quartiles and the IQR;
</li>
<li>
explain why a one-sample t procedure has <span class="math inline">\(n-1\)</span> degrees of freedom;
</li>
<li>
use the CLT without confusing observations and statistics;
</li>
<li>
qualify conclusions when the sampling design is limited.
</li>
</ul>
</div>
<div id="before-class-10" class="section level2 hasAnchor course-phase phase-before">
<h2>Before class<a href="b-ep03.html#before-class-10" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Bring your after-class work from Lectures 7 and 8. If the algebra is slowing
you down, review <a href="math-refresher.html#math-refresher">Mathematics Refresher: sums, fractions, and roots</a>.</p>
<p>Use the cumulative <a href="formula-sheet.html#formula-l8">formula sheet through Lecture 8</a>.</p>
<p>Complete from memory:</p>
<ol style="list-style-type: decimal">
<li>A parameter describes …</li>
<li>An estimator is …</li>
<li>The standard error of <span class="math inline">\(\bar X\)</span> is …</li>
<li>The CLT describes …</li>
</ol>
<details>
<summary>
Check your preparation
</summary>
<ol style="list-style-type: decimal">
<li>A parameter describes a population.</li>
<li>An estimator is a sample-based random rule used to estimate a parameter.</li>
<li><span class="math inline">\(\sigma/\sqrt n\)</span>, estimated by <span class="math inline">\(S/\sqrt n\)</span> when <span class="math inline">\(\sigma\)</span> is unknown.</li>
<li>The limiting distribution of a properly standardised sum or mean.</li>
</ol>
</details>
</div>
<div id="in-class-10" class="section level2 hasAnchor course-phase phase-in-class">
<h2>In class<a href="b-ep03.html#in-class-10" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Attempt each task before opening its answer.</p>
<div id="task-1-population-frame-and-claim" class="section level3 hasAnchor">
<h3>Task 1 — Population, frame, and claim<a href="b-ep03.html#task-1-population-frame-and-claim" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>A student randomly selects 100 rows from the teaching file and estimates the
mean initial equity offered.</p>
<ol style="list-style-type: decimal">
<li>State the population to which this design directly supports inference.</li>
<li>Explain why it does not represent all <em>Shark Tank</em> applicants.</li>
<li>Explain why it does not represent all US entrepreneurs.</li>
<li>State one change needed to target all US entrepreneurs.</li>
</ol>
<details>
<summary>
Check your answer
</summary>
<p>The direct finite population is the 1,441 recorded pitches in completed
Seasons 1–16. Applicants who were not televised are absent, so the frame does
not represent all applicants. The show also selects a specialised group of
entrepreneurs, not a probability sample of US entrepreneurs. Targeting all US
entrepreneurs would require an appropriate national sampling frame and random
selection from that frame.</p>
</details>
</div>
<div id="task-2-reproduce-the-realised-sample" class="section level3 hasAnchor">
<h3>Task 2 — Reproduce the realised sample<a href="b-ep03.html#task-2-reproduce-the-realised-sample" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div class="sourceCode" id="cb110"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb110-1"><a href="b-ep03.html#cb110-1" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb110-2"><a href="b-ep03.html#cb110-2" tabindex="-1"></a>pitch_sample <span class="ot">&lt;-</span> sharks[<span class="fu">sample</span>(<span class="fu">seq_len</span>(<span class="fu">nrow</span>(sharks)), <span class="dv">100</span>), ]</span>
<span id="cb110-3"><a href="b-ep03.html#cb110-3" tabindex="-1"></a></span>
<span id="cb110-4"><a href="b-ep03.html#cb110-4" tabindex="-1"></a><span class="fu">c</span>(</span>
<span id="cb110-5"><a href="b-ep03.html#cb110-5" tabindex="-1"></a>  <span class="at">n =</span> <span class="fu">nrow</span>(pitch_sample),</span>
<span id="cb110-6"><a href="b-ep03.html#cb110-6" tabindex="-1"></a>  <span class="at">mean_equity =</span> <span class="fu">mean</span>(pitch_sample<span class="sc">$</span>equity_offered_pct),</span>
<span id="cb110-7"><a href="b-ep03.html#cb110-7" tabindex="-1"></a>  <span class="at">sd_equity =</span> <span class="fu">sd</span>(pitch_sample<span class="sc">$</span>equity_offered_pct),</span>
<span id="cb110-8"><a href="b-ep03.html#cb110-8" tabindex="-1"></a>  <span class="at">q1_equity =</span> <span class="fu">unname</span>(<span class="fu">quantile</span>(pitch_sample<span class="sc">$</span>equity_offered_pct, <span class="fl">0.25</span>)),</span>
<span id="cb110-9"><a href="b-ep03.html#cb110-9" tabindex="-1"></a>  <span class="at">median_equity =</span> <span class="fu">median</span>(pitch_sample<span class="sc">$</span>equity_offered_pct),</span>
<span id="cb110-10"><a href="b-ep03.html#cb110-10" tabindex="-1"></a>  <span class="at">q3_equity =</span> <span class="fu">unname</span>(<span class="fu">quantile</span>(pitch_sample<span class="sc">$</span>equity_offered_pct, <span class="fl">0.75</span>)),</span>
<span id="cb110-11"><a href="b-ep03.html#cb110-11" tabindex="-1"></a>  <span class="at">deal_proportion =</span> <span class="fu">mean</span>(pitch_sample<span class="sc">$</span>deal_on_show)</span>
<span id="cb110-12"><a href="b-ep03.html#cb110-12" tabindex="-1"></a>)</span></code></pre></div>
<pre><code>##               n     mean_equity       sd_equity       q1_equity   median_equity 
##      100.000000       12.760000        7.707887        8.000000       10.000000 
##       q3_equity deal_proportion 
##       17.750000        0.640000</code></pre>
<ol style="list-style-type: decimal">
<li>Identify the parameter, estimator, and estimate for mean equity.</li>
<li>Identify the parameter, estimator, and estimate for the deal proportion.</li>
<li>Calculate the IQR of equity and interpret it.</li>
<li>Explain why a different seed can produce different estimates and a
different IQR.</li>
</ol>
<details>
<summary>
Check your answer
</summary>
<p>For equity, the parameter is the population mean <span class="math inline">\(\mu\)</span>, the estimator is
<span class="math inline">\(\bar X\)</span>, and the estimate is <span class="math inline">\(\bar x=12.76\)</span>. For deal outcome, the
parameter is the population proportion <span class="math inline">\(p\)</span>, the estimator is
<span class="math inline">\(\widehat P\)</span>, and the estimate is <span class="math inline">\(\hat p=0.64\)</span>. The sample quartiles are
<span class="math inline">\(Q_1=8\)</span> and <span class="math inline">\(Q_3=17.75\)</span>, so
<span class="math inline">\(\operatorname{IQR}=17.75-8=9.75\)</span> percentage points. The middle half of the
sampled initial equity offers lies from 8% to 17.75%. A different seed selects
a different random set of rows, so all realised sample statistics, including
the IQR, can change.</p>
</details>
</div>
<div id="task-3-standard-errors-and-sample-size" class="section level3 hasAnchor">
<h3>Task 3 — Standard errors and sample size<a href="b-ep03.html#task-3-standard-errors-and-sample-size" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Use the sample output above.</p>
<ol style="list-style-type: decimal">
<li>Estimate <span class="math inline">\(\operatorname{SE}(\bar X)\)</span>.</li>
<li>Estimate <span class="math inline">\(\operatorname{SE}(\widehat P)\)</span>.</li>
<li>Check the success-failure condition for <span class="math inline">\(\widehat P\)</span>.</li>
<li>Predict how each SE changes if <span class="math inline">\(n\)</span> increases from 100 to 400 while the
estimated spread remains similar.</li>
</ol>
<details>
<summary>
Check your answer
</summary>
<p><span class="math display">\[
\widehat{\operatorname{SE}}(\bar X)=7.7079/\sqrt{100}=0.7708.
\]</span></p>
<p><span class="math display">\[
\widehat{\operatorname{SE}}(\widehat P)
=\sqrt{0.64(0.36)/100}=0.0480.
\]</span></p>
<p>The sample contains 64 successes and 36 failures, so both are at least 10.
Increasing <span class="math inline">\(n\)</span> fourfold divides both SEs by <span class="math inline">\(\sqrt 4=2\)</span>.</p>
</details>
</div>
<div id="task-4-read-a-sampling-distribution-statement" class="section level3 hasAnchor">
<h3>Task 4 — Read a sampling-distribution statement<a href="b-ep03.html#task-4-read-a-sampling-distribution-statement" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Suppose the population mean is <span class="math inline">\(\mu=13.21\)</span>, the population SD is
<span class="math inline">\(\sigma=8.44\)</span>, and samples of <span class="math inline">\(n=100\)</span> are drawn independently.</p>
<ol style="list-style-type: decimal">
<li>State the approximate sampling distribution of <span class="math inline">\(\bar X\)</span>.</li>
<li>Calculate <span class="math inline">\(P(\bar X&gt;15)\)</span>.</li>
<li>Explain why this probability is not <span class="math inline">\(P(X&gt;15)\)</span>.</li>
</ol>
<details>
<summary>
Check your answer
</summary>
<p>The CLT gives approximately
<span class="math inline">\(\bar X\mathrel{\dot\sim}N(13.21,8.44^2/100)\)</span>, with SE <span class="math inline">\(0.844\)</span>. Therefore</p>
<p><span class="math display">\[
P(\bar X&gt;15)
=1-\Phi\!\left(\frac{15-13.21}{0.844}\right)
\approx0.017.
\]</span></p>
<p>This probability concerns a mean across 100 pitches. <span class="math inline">\(P(X&gt;15)\)</span> concerns one
pitch and uses the much wider population distribution.</p>
</details>
</div>
<div id="task-5-degrees-of-freedom-and-the-t-reference" class="section level3 hasAnchor">
<h3>Task 5 — Degrees of freedom and the t reference<a href="b-ep03.html#task-5-degrees-of-freedom-and-the-t-reference" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>A sample of <span class="math inline">\(n=12\)</span> observations is used to estimate a population mean and
the unknown population standard deviation.</p>
<ol style="list-style-type: decimal">
<li>What are the degrees of freedom for the one-sample t procedure?</li>
<li>Why is the answer not 12?</li>
<li>In R, compare <code>qt(0.975, df = 11)</code> with
<code>qt(0.975, df = 99)</code>. Which critical value is larger, and why?</li>
</ol>
<details>
<summary>
Check your answer
</summary>
<p>The degrees of freedom are <span class="math inline">\(12-1=11\)</span>. Once the sample mean is estimated,
the 12 deviations from that mean must sum to zero. Only 11 deviations can
vary freely; the last is determined by the other 11. The t critical value is
larger for 11 degrees of freedom because estimating <span class="math inline">\(\sigma\)</span> from a small
sample creates extra uncertainty. As the degrees of freedom increase, the t
distribution approaches the standard normal distribution.</p>
</details>
</div>
</div>
<div id="after-class-10" class="section level2 hasAnchor course-phase phase-after">
<h2>After class<a href="b-ep03.html#after-class-10" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="timed-individual-practice-12-minutes" class="section level3 hasAnchor">
<h3>Timed individual practice — 12 minutes<a href="b-ep03.html#timed-individual-practice-12-minutes" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>A random sample of 64 customers has mean monthly spending €82 and sample SD
€24. Among the 64 customers, 40 renewed their subscription.</p>
<ol style="list-style-type: decimal">
<li>Estimate the SE of mean spending.</li>
<li>Estimate the SE of the renewal proportion and check its condition.</li>
<li>State what would happen to both SEs at <span class="math inline">\(n=256\)</span>.</li>
<li>Write one sentence distinguishing sampling uncertainty from selection bias.</li>
<li>If a one-sample t procedure is applied to mean spending, state its degrees
of freedom.</li>
</ol>
<details>
<summary>
Check a model answer
</summary>
<p>The estimated SE of the mean is <span class="math inline">\(24/\sqrt{64}=3\)</span> euros. The renewal estimate
is <span class="math inline">\(40/64=0.625\)</span>, with estimated SE
<span class="math inline">\(\sqrt{0.625(0.375)/64}\approx0.0605\)</span>; the sample has 40 successes and 24
failures, so the success-failure condition holds. Increasing the sample size
from 64 to 256 would halve both SEs if the spread remained similar. These SEs
describe random sample-to-sample variation, not bias created by an
unrepresentative sampling frame. The mean procedure has <span class="math inline">\(64-1=63\)</span> degrees
of freedom.</p>
</details>
<p>Continue to <a href="b09.html#b09">Lecture 9: Confidence intervals and tests against zero</a>.</p>
</div>
</div>

</div>
            </section>

          </div>
        </div>
      </div>
<a href="b08.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="b09.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
  "sharing": null,
  "fontsettings": {
    "theme": "white",
    "family": "sans",
    "size": 2
  },
  "edit": null,
  "history": {
    "link": null,
    "text": null
  },
  "view": {
    "link": null,
    "text": null
  },
  "download": null,
  "search": {
    "engine": "fuse",
    "options": null
  },
  "toc": {
    "collapse": "section",
    "scroll_highlight": true
  },
  "toolbar": {
    "position": "fixed"
  }
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
