<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Tutorial 1: Evidence and probability foundations | Online Textbook for the Learning Line “Quantitative Methods to Understand E&amp;BI”</title>
  <meta name="description" content="An online textbook for the learning line Quantitative Methods within Entrepreneurship and Business Innovation Bachelor Program at Tilburg University." />
  <meta name="generator" content="bookdown 0.47 and GitBook 2.6.7" />

  <meta property="og:title" content="Tutorial 1: Evidence and probability foundations | Online Textbook for the Learning Line “Quantitative Methods to Understand E&amp;BI”" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="An online textbook for the learning line Quantitative Methods within Entrepreneurship and Business Innovation Bachelor Program at Tilburg University." />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Tutorial 1: Evidence and probability foundations | Online Textbook for the Learning Line “Quantitative Methods to Understand E&amp;BI”" />
  
  <meta name="twitter:description" content="An online textbook for the learning line Quantitative Methods within Entrepreneurship and Business Innovation Bachelor Program at Tilburg University." />
  




  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="b03.html"/>
<link rel="next" href="b04.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

<link rel="stylesheet" href="styles.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="book-title"><a href="./">QM to Understand E&amp;BI</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Welcome</a></li>
<li class="part"><span><b>I QM Basic</b></span></li>
<li class="chapter" data-level="" data-path="basic-course.html"><a href="basic-course.html"><i class="fa fa-check"></i>QM Basic: Course overview</a></li>
<li class="chapter" data-level="" data-path="b01.html"><a href="b01.html"><i class="fa fa-check"></i>Lecture 1: Introduction to Data Analysis</a></li>
<li class="chapter" data-level="" data-path="b02.html"><a href="b02.html"><i class="fa fa-check"></i>Lecture 2: Probability foundations and random variables</a></li>
<li class="chapter" data-level="" data-path="b03.html"><a href="b03.html"><i class="fa fa-check"></i>Lecture 3: Discrete distributions and expectation</a></li>
<li class="chapter" data-level="" data-path="b-ep01.html"><a href="b-ep01.html"><i class="fa fa-check"></i>Tutorial 1: Evidence and probability foundations</a></li>
<li class="chapter" data-level="" data-path="b04.html"><a href="b04.html"><i class="fa fa-check"></i>Lecture 4: Variance, conditioning, and belief updating</a></li>
<li class="chapter" data-level="" data-path="b05.html"><a href="b05.html"><i class="fa fa-check"></i>Lecture 5: Joint random variables, covariance, and correlation</a></li>
<li class="chapter" data-level="" data-path="b-ep02.html"><a href="b-ep02.html"><i class="fa fa-check"></i>Tutorial 2: Conditioning and relationships</a></li>
<li class="chapter" data-level="" data-path="b06.html"><a href="b06.html"><i class="fa fa-check"></i>Lecture 6: Continuous distributions and the normal model</a></li>
<li class="chapter" data-level="" data-path="b07.html"><a href="b07.html"><i class="fa fa-check"></i>Lecture 7: Samples, parameters, and estimators</a></li>
<li class="chapter" data-level="" data-path="b08.html"><a href="b08.html"><i class="fa fa-check"></i>Lecture 8: Sampling distributions and the central limit theorem</a></li>
<li class="chapter" data-level="" data-path="b-ep03.html"><a href="b-ep03.html"><i class="fa fa-check"></i>Tutorial 3: Sampling and standard errors</a></li>
<li class="chapter" data-level="" data-path="b09.html"><a href="b09.html"><i class="fa fa-check"></i>Lecture 9: Confidence intervals and tests against zero</a></li>
<li class="chapter" data-level="" data-path="b10.html"><a href="b10.html"><i class="fa fa-check"></i>Lecture 10: Hypothesis testing, errors, and power</a></li>
<li class="chapter" data-level="" data-path="b-ep04.html"><a href="b-ep04.html"><i class="fa fa-check"></i>Tutorial 4: Inference and tests against zero</a></li>
<li class="chapter" data-level="" data-path="formula-sheet.html"><a href="formula-sheet.html"><i class="fa fa-check"></i>QM Basic Formula Sheet</a></li>
<li class="chapter" data-level="" data-path="basic-mock-exam.html"><a href="basic-mock-exam.html"><i class="fa fa-check"></i>Mock Exam: QM Basic</a></li>
<li class="part"><span><b>II QM Intermediate</b></span></li>
<li class="chapter" data-level="" data-path="intermediate-course.html"><a href="intermediate-course.html"><i class="fa fa-check"></i>QM Intermediate: Course overview</a></li>
<li class="chapter" data-level="" data-path="i01.html"><a href="i01.html"><i class="fa fa-check"></i>Lecture 1: Simple linear regression</a></li>
<li class="chapter" data-level="" data-path="i02.html"><a href="i02.html"><i class="fa fa-check"></i>Lecture 2: Regression assumptions and coefficient inference</a></li>
<li class="chapter" data-level="" data-path="i03.html"><a href="i03.html"><i class="fa fa-check"></i>Lecture 3: Model fit and overall usefulness</a></li>
<li class="chapter" data-level="" data-path="i-ep01.html"><a href="i-ep01.html"><i class="fa fa-check"></i>Tutorial 1: Simple regression and model usefulness</a></li>
<li class="chapter" data-level="" data-path="i04.html"><a href="i04.html"><i class="fa fa-check"></i>Lecture 4: Multiple linear regression and controls</a></li>
<li class="chapter" data-level="" data-path="i05.html"><a href="i05.html"><i class="fa fa-check"></i>Lecture 5: Dummy predictors and joint usefulness</a></li>
<li class="chapter" data-level="" data-path="i06.html"><a href="i06.html"><i class="fa fa-check"></i>Lecture 6: Interactions and polynomial terms</a></li>
<li class="chapter" data-level="" data-path="i-ep02.html"><a href="i-ep02.html"><i class="fa fa-check"></i>Tutorial 2: Multiple regression and extensions</a></li>
<li class="chapter" data-level="" data-path="intermediate-code-sheet.html"><a href="intermediate-code-sheet.html"><i class="fa fa-check"></i>QM Intermediate Code Sheet</a></li>
<li class="chapter" data-level="" data-path="intermediate-mock-exam.html"><a href="intermediate-mock-exam.html"><i class="fa fa-check"></i>Mock Exam: QM Intermediate</a></li>
<li class="part"><span><b>III QM Advanced</b></span></li>
<li class="chapter" data-level="" data-path="advanced-course.html"><a href="advanced-course.html"><i class="fa fa-check"></i>QM Advanced: Course overview</a></li>
<li class="part"><span><b>IV Supplementary resources</b></span></li>
<li class="chapter" data-level="" data-path="r-refresher.html"><a href="r-refresher.html"><i class="fa fa-check"></i>R Refresher</a></li>
<li class="chapter" data-level="" data-path="math-refresher.html"><a href="math-refresher.html"><i class="fa fa-check"></i>Mathematics Refresher</a></li>
<li class="chapter" data-level="" data-path="videos.html"><a href="videos.html"><i class="fa fa-check"></i>External Video Guide</a></li>
<li class="divider"></li>
<li class="book-footer">Quantitative Methods learning line</li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Online Textbook for the Learning Line “Quantitative Methods to Understand E&amp;BI”</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="b-ep01" class="section level1 hasAnchor">
<h1>Tutorial 1: Evidence and probability foundations<a href="b-ep01.html#b-ep01" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<div class="outcomes">
<span class="label">By the end of Tutorial 1, you can</span>
<ul>
<li>
distinguish data, events, random variables, and distributions;
</li>
<li>
apply probability rules to the Shark Tank record-selection experiment;
</li>
<li>
calculate and interpret a Bernoulli PMF, CDF, and expectation;
</li>
<li>
write a concise interpretation of supplied R output.
</li>
</ul>
</div>
<div id="before-class-3" class="section level2 hasAnchor course-phase phase-before">
<h2>Before class<a href="b-ep01.html#before-class-3" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Bring your after-class work from Lectures 1–3. Without reopening the chapters,
complete these definitions:</p>
<p>Use the cumulative <a href="formula-sheet.html#formula-l3">formula sheet through Lecture 3</a>.</p>
<p>Review <a href="math-refresher.html#math-refresher">Mathematics Refresher: sets, fractions, and sums</a> if
the notation is slowing you down.</p>
<ol style="list-style-type: decimal">
<li>An observational unit is …</li>
<li>An event is …</li>
<li>A random variable is …</li>
<li>A PMF is …</li>
</ol>
<details>
<summary>
Check your preparation
</summary>
<ol style="list-style-type: decimal">
<li>An observational unit is the entity represented by one row of the data.</li>
<li>An event is a specified subset of the sample space.</li>
<li>A random variable is a real-valued function on the sample space.</li>
<li>A PMF assigns probability <span class="math inline">\(P(X=x)\)</span> to each value in the support of a
discrete random variable; its masses are non-negative and sum to 1.</li>
</ol>
</details>
</div>
<div id="in-class-3" class="section level2 hasAnchor course-phase phase-in-class">
<h2>In class<a href="b-ep01.html#in-class-3" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Attempt each task before opening its answer. A complete written answer should
name the quantity, show the calculation, report the value and units, interpret
it in context, and state an important model or measurement boundary.</p>
<div id="task-1-data-and-measurement" class="section level3 hasAnchor">
<h3>Task 1 — Data and measurement<a href="b-ep01.html#task-1-data-and-measurement" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>R reports:</p>
<pre><code>##                     rows                  columns                    deals 
##             1441.0000000               19.0000000              882.0000000 
##          deal_proportion median_description_words 
##                0.6120749                5.0000000</code></pre>
<ol style="list-style-type: decimal">
<li>What is the observational unit?</li>
<li>Verify the deal proportion from 882 deals and 559 non-deals.</li>
<li>Explain why the mean of <code>deal_on_show</code> is a proportion.</li>
<li>Evaluate: “The data contain 1,441 successful companies.”</li>
<li>What exactly does <code>description_words</code> measure?</li>
</ol>
<details>
<summary>
Check your answer
</summary>
<p>One row is one recorded televised pitch. There are <span class="math inline">\(882+559=1441\)</span> records and
<span class="math inline">\(882/1441\approx0.612\)</span>, so 61.2% reached an on-air agreement. The mean of a 0/1
indicator equals the share coded 1 because its sum counts the 1s. “Successful
companies” is incorrect: the outcome is an agreement made on the show, not
completed funding or later venture performance. Word count describes the
written text in the source dataset, not the spoken pitch.</p>
</details>
</div>
<div id="task-2-events-and-probability-rules" class="section level3 hasAnchor">
<h3>Task 2 — Events and probability rules<a href="b-ep01.html#task-2-events-and-probability-rules" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The experiment selects one of the 1,441 records uniformly. Let:</p>
<ul>
<li><span class="math inline">\(D\)</span>: the selected record has an on-air deal;</li>
<li><span class="math inline">\(L\)</span>: the selected record is from Seasons 9–16.</li>
</ul>
<p>R reports:</p>
<pre><code>##       P_D       P_L P_D_and_L 
## 0.6120749 0.5093685 0.3504511</code></pre>
<ol style="list-style-type: decimal">
<li>Define <span class="math inline">\(\Omega\)</span>, and distinguish an outcome from event <span class="math inline">\(D\)</span>.</li>
<li>Translate <span class="math inline">\(D^c\)</span>, <span class="math inline">\(D\cap L\)</span>, and <span class="math inline">\(D\cup L\)</span> into words.</li>
<li>Calculate <span class="math inline">\(P(D^c)\)</span>.</li>
<li>Calculate <span class="math inline">\(P(D\cup L)\)</span> using the addition rule.</li>
<li>Explain why these probabilities do not automatically apply to a future US
entrepreneur.</li>
</ol>
<details>
<summary>
Check your answer
</summary>
<p>The sample space is the set of 1,441 complete pitch records; one selected record
is an outcome, while <span class="math inline">\(D\)</span> is the subset of 882 deal records. The complement is
no on-air deal, the intersection is a late-season deal, and the union is
late-season, deal, or both. <span class="math inline">\(P(D^c)=1-882/1441=559/1441\approx0.388\)</span>.
The union is <span class="math inline">\(P(D)+P(L)-P(D\cap L)\approx0.771\)</span>. Future use requires a
defined target population and comparable selection, time period, and outcome.</p>
</details>
</div>
<div id="task-3-pmf-cdf-and-expectation" class="section level3 hasAnchor">
<h3>Task 3 — PMF, CDF, and expectation<a href="b-ep01.html#task-3-pmf-cdf-and-expectation" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Let <span class="math inline">\(X=1\)</span> for an on-air deal and <span class="math inline">\(X=0\)</span> otherwise. Use
<span class="math inline">\(p=882/1441\)</span>.</p>
<ol style="list-style-type: decimal">
<li>Write the PMF and verify that its masses sum to 1.</li>
<li>Write the full piecewise CDF <span class="math inline">\(F_X(a)\)</span>.</li>
<li>Calculate <span class="math inline">\(E[X]\)</span> from the PMF.</li>
<li>Explain why <span class="math inline">\(E[X]\)</span> equals the observed proportion of 1s.</li>
<li>Explain the difference between the random variable <span class="math inline">\(X\)</span> and a realised
value <span class="math inline">\(x=1\)</span>.</li>
</ol>
<details>
<summary>
Check your answer
</summary>
<p><span class="math display">\[
p_X(0)=1-p,\qquad p_X(1)=p,
\]</span></p>
<p>and the masses total <span class="math inline">\(1-p+p=1\)</span>.</p>
<p><span class="math display">\[
F_X(a)=
\begin{cases}
0,&amp;a&lt;0,\\
1-p,&amp;0\le a&lt;1,\\
1,&amp;a\ge1.
\end{cases}
\]</span></p>
<p>The expectation is <span class="math inline">\(E[X]=0(1-p)+1p=p\approx0.612\)</span>. Because the indicator
contains 882 ones among 1,441 observations, its mean is also <span class="math inline">\(882/1441\)</span>.
<span class="math inline">\(X\)</span> is the mapping defined before selection; <span class="math inline">\(x=1\)</span> is one possible
realised value.</p>
</details>
</div>
</div>
<div id="after-class-3" class="section level2 hasAnchor course-phase phase-after">
<h2>After class<a href="b-ep01.html#after-class-3" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="timed-individual-practice-10-minutes" class="section level3 hasAnchor">
<h3>Timed individual practice — 10 minutes<a href="b-ep01.html#timed-individual-practice-10-minutes" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>An output block describes word count:</p>
<pre><code>##      mean    median   minimum        q1        q3   maximum 
##  4.995142  5.000000  1.000000  4.000000  6.000000 13.000000</code></pre>
<p>Write no more than 100 words. Compare mean and median, calculate the IQR,
calculate the range, and state the measurement boundary. Then explain
which value equals the expectation if the empirical distribution gives mass
<span class="math inline">\(1/1441\)</span> to each record.</p>
<details>
<summary>
Check a model answer
</summary>
<p>The written descriptions have a mean length of about 5.0 words and a median
of 5 words. Their IQR is <span class="math inline">\(6-4=2\)</span> words, and their range is
<span class="math inline">\(13-1=12\)</span> words. The thin upper tail is consistent with the mildly
right-skewed histogram seen in Lecture 2. If each record receives probability
<span class="math inline">\(1/1441\)</span>, the empirical expectation is the mean, about 5.0 words. These values
describe written dataset text, not spoken-pitch length or quality.</p>
</details>
</div>
<div id="check-your-understanding" class="section level3 hasAnchor">
<h3>Check your understanding<a href="b-ep01.html#check-your-understanding" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Complete from memory:</p>
<ol style="list-style-type: decimal">
<li>An event is …</li>
<li>A PMF must …</li>
<li>A CDF at <span class="math inline">\(a\)</span> reports …</li>
<li>Expectation is …</li>
</ol>
<details>
<summary>
Check your answers
</summary>
<ol style="list-style-type: decimal">
<li>An event is a specified subset of the sample space.</li>
<li>A PMF is non-negative and sums to 1 over the support.</li>
<li><span class="math inline">\(F_X(a)=P(X\le a)\)</span>.</li>
<li><span class="math inline">\(E[X]=\sum_x x p_X(x)\)</span>, the probability-weighted average of the possible
values.</li>
</ol>
</details>
<p>Continue to <a href="b04.html#b04">Lecture 4: Variance, conditioning, and belief updating</a>.</p>
</div>
</div>

</div>
            </section>

          </div>
        </div>
      </div>
<a href="b03.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="b04.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
  "sharing": null,
  "fontsettings": {
    "theme": "white",
    "family": "sans",
    "size": 2
  },
  "edit": null,
  "history": {
    "link": null,
    "text": null
  },
  "view": {
    "link": null,
    "text": null
  },
  "download": null,
  "search": {
    "engine": "fuse",
    "options": null
  },
  "toc": {
    "collapse": "section",
    "scroll_highlight": true
  },
  "toolbar": {
    "position": "fixed"
  }
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
