<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Lecture 3: Discrete distributions and expectation | Online Textbook for the Learning Line “Quantitative Methods to Understand E&amp;BI”</title>
  <meta name="description" content="An online textbook for the learning line Quantitative Methods within Entrepreneurship and Business Innovation Bachelor Program at Tilburg University." />
  <meta name="generator" content="bookdown 0.47 and GitBook 2.6.7" />

  <meta property="og:title" content="Lecture 3: Discrete distributions and expectation | Online Textbook for the Learning Line “Quantitative Methods to Understand E&amp;BI”" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="An online textbook for the learning line Quantitative Methods within Entrepreneurship and Business Innovation Bachelor Program at Tilburg University." />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Lecture 3: Discrete distributions and expectation | Online Textbook for the Learning Line “Quantitative Methods to Understand E&amp;BI”" />
  
  <meta name="twitter:description" content="An online textbook for the learning line Quantitative Methods within Entrepreneurship and Business Innovation Bachelor Program at Tilburg University." />
  




  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="b02.html"/>
<link rel="next" href="b-ep01.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

<link rel="stylesheet" href="styles.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="book-title"><a href="./">QM to Understand E&amp;BI</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Welcome</a></li>
<li class="part"><span><b>I QM Basic</b></span></li>
<li class="chapter" data-level="" data-path="basic-course.html"><a href="basic-course.html"><i class="fa fa-check"></i>QM Basic: Course overview</a></li>
<li class="chapter" data-level="" data-path="b01.html"><a href="b01.html"><i class="fa fa-check"></i>Lecture 1: Introduction to Data Analysis</a></li>
<li class="chapter" data-level="" data-path="b02.html"><a href="b02.html"><i class="fa fa-check"></i>Lecture 2: Probability foundations and random variables</a></li>
<li class="chapter" data-level="" data-path="b03.html"><a href="b03.html"><i class="fa fa-check"></i>Lecture 3: Discrete distributions and expectation</a></li>
<li class="chapter" data-level="" data-path="b-ep01.html"><a href="b-ep01.html"><i class="fa fa-check"></i>Tutorial 1: Evidence and probability foundations</a></li>
<li class="chapter" data-level="" data-path="b04.html"><a href="b04.html"><i class="fa fa-check"></i>Lecture 4: Variance, conditioning, and belief updating</a></li>
<li class="chapter" data-level="" data-path="b05.html"><a href="b05.html"><i class="fa fa-check"></i>Lecture 5: Joint random variables, covariance, and correlation</a></li>
<li class="chapter" data-level="" data-path="b-ep02.html"><a href="b-ep02.html"><i class="fa fa-check"></i>Tutorial 2: Conditioning and relationships</a></li>
<li class="chapter" data-level="" data-path="b06.html"><a href="b06.html"><i class="fa fa-check"></i>Lecture 6: Continuous distributions and the normal model</a></li>
<li class="chapter" data-level="" data-path="b07.html"><a href="b07.html"><i class="fa fa-check"></i>Lecture 7: Samples, parameters, and estimators</a></li>
<li class="chapter" data-level="" data-path="b08.html"><a href="b08.html"><i class="fa fa-check"></i>Lecture 8: Sampling distributions and the central limit theorem</a></li>
<li class="chapter" data-level="" data-path="b-ep03.html"><a href="b-ep03.html"><i class="fa fa-check"></i>Tutorial 3: Sampling and standard errors</a></li>
<li class="chapter" data-level="" data-path="b09.html"><a href="b09.html"><i class="fa fa-check"></i>Lecture 9: Confidence intervals and tests against zero</a></li>
<li class="chapter" data-level="" data-path="b10.html"><a href="b10.html"><i class="fa fa-check"></i>Lecture 10: Hypothesis testing, errors, and power</a></li>
<li class="chapter" data-level="" data-path="b-ep04.html"><a href="b-ep04.html"><i class="fa fa-check"></i>Tutorial 4: Inference and tests against zero</a></li>
<li class="chapter" data-level="" data-path="formula-sheet.html"><a href="formula-sheet.html"><i class="fa fa-check"></i>QM Basic Formula Sheet</a></li>
<li class="chapter" data-level="" data-path="basic-mock-exam.html"><a href="basic-mock-exam.html"><i class="fa fa-check"></i>Mock Exam: QM Basic</a></li>
<li class="part"><span><b>II QM Intermediate</b></span></li>
<li class="chapter" data-level="" data-path="intermediate-course.html"><a href="intermediate-course.html"><i class="fa fa-check"></i>QM Intermediate: Course overview</a></li>
<li class="chapter" data-level="" data-path="i01.html"><a href="i01.html"><i class="fa fa-check"></i>Lecture 1: Simple linear regression</a></li>
<li class="chapter" data-level="" data-path="i02.html"><a href="i02.html"><i class="fa fa-check"></i>Lecture 2: Regression assumptions and coefficient inference</a></li>
<li class="chapter" data-level="" data-path="i03.html"><a href="i03.html"><i class="fa fa-check"></i>Lecture 3: Model fit and overall usefulness</a></li>
<li class="chapter" data-level="" data-path="i-ep01.html"><a href="i-ep01.html"><i class="fa fa-check"></i>Tutorial 1: Simple regression and model usefulness</a></li>
<li class="chapter" data-level="" data-path="i04.html"><a href="i04.html"><i class="fa fa-check"></i>Lecture 4: Multiple linear regression and controls</a></li>
<li class="chapter" data-level="" data-path="i05.html"><a href="i05.html"><i class="fa fa-check"></i>Lecture 5: Dummy predictors and joint usefulness</a></li>
<li class="chapter" data-level="" data-path="i06.html"><a href="i06.html"><i class="fa fa-check"></i>Lecture 6: Interactions and polynomial terms</a></li>
<li class="chapter" data-level="" data-path="i-ep02.html"><a href="i-ep02.html"><i class="fa fa-check"></i>Tutorial 2: Multiple regression and extensions</a></li>
<li class="chapter" data-level="" data-path="intermediate-code-sheet.html"><a href="intermediate-code-sheet.html"><i class="fa fa-check"></i>QM Intermediate Code Sheet</a></li>
<li class="chapter" data-level="" data-path="intermediate-mock-exam.html"><a href="intermediate-mock-exam.html"><i class="fa fa-check"></i>Mock Exam: QM Intermediate</a></li>
<li class="part"><span><b>III QM Advanced</b></span></li>
<li class="chapter" data-level="" data-path="advanced-course.html"><a href="advanced-course.html"><i class="fa fa-check"></i>QM Advanced: Course overview</a></li>
<li class="part"><span><b>IV Supplementary resources</b></span></li>
<li class="chapter" data-level="" data-path="r-refresher.html"><a href="r-refresher.html"><i class="fa fa-check"></i>R Refresher</a></li>
<li class="chapter" data-level="" data-path="math-refresher.html"><a href="math-refresher.html"><i class="fa fa-check"></i>Mathematics Refresher</a></li>
<li class="chapter" data-level="" data-path="videos.html"><a href="videos.html"><i class="fa fa-check"></i>External Video Guide</a></li>
<li class="divider"></li>
<li class="book-footer">Quantitative Methods learning line</li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Online Textbook for the Learning Line “Quantitative Methods to Understand E&amp;BI”</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="b03" class="section level1 hasAnchor">
<h1>Lecture 3: Discrete distributions and expectation<a href="b03.html#b03" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<div class="outcomes">
<span class="label">By the end of Lecture 3, you can</span>
<ul>
<li>
construct, check, and interpret a probability mass function;
</li>
<li>
construct and interpret a discrete cumulative distribution function;
</li>
<li>
calculate and interpret expectation and the expectation of a function;
</li>
<li>
connect model expectation to an empirical mean without confusing them.
</li>
</ul>
</div>
<div id="before-class-2" class="section level2 hasAnchor course-phase phase-before">
<h2>Before class<a href="b03.html#before-class-2" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div class="video-prep">
<p><span class="label">Video preparation</span><br>
Watch
<a href="https://ocw.mit.edu/courses/res-6-012-introduction-to-probability-spring-2018/resources/probability-mass-functions/">Probability Mass Functions</a>,
<a href="https://www.youtube.com/watch?v=4QeL1ma_XJ0">Cumulative Distribution
Functions</a>, and
<a href="https://www.youtube.com/watch?v=_yJsO5955ZE">Expectation</a>.
Be ready to explain what <span class="math inline">\(p_X(x)\)</span> and <span class="math inline">\(F_X(a)\)</span> measure and why an expected
value need not be a possible realised value. All links are also listed in the
<a href="videos.html#videos">External Video Guide</a>.</p>
</div>
<p>If functions, support, or summation notation are unfamiliar, review
<a href="math-refresher.html#math-refresher">Mathematics Refresher: functions and sums</a>.</p>
<p>Lecture 2 ended with random variables. Suppose one pitch record is selected
uniformly from the dataset. Define <span class="math inline">\(X=1\)</span> if it reached an on-air deal and
<span class="math inline">\(X=0\)</span> otherwise. Define <span class="math inline">\(S\)</span> as its season number.</p>
<p>After watching, answer:</p>
<ol style="list-style-type: decimal">
<li>What are the possible values of <span class="math inline">\(X\)</span> and <span class="math inline">\(S\)</span>?</li>
<li>Do these possible values tell us how likely each value is?</li>
</ol>
<details>
<summary>
Check your preparation
</summary>
<ol style="list-style-type: decimal">
<li><span class="math inline">\(X\)</span> can take the values 0 and 1. <span class="math inline">\(S\)</span> can take the values
<span class="math inline">\(1,2,\ldots,16\)</span>.</li>
<li>No. The support lists the possible values. A probability distribution must
also assign probability to them.</li>
</ol>
</details>
</div>
<div id="in-class-2" class="section level2 hasAnchor course-phase phase-in-class">
<h2>In class<a href="b03.html#in-class-2" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="a-pmf-assigns-probability-to-each-possible-value" class="section level3 hasAnchor">
<h3>A PMF assigns probability to each possible value<a href="b03.html#a-pmf-assigns-probability-to-each-possible-value" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p class="concept-video">
<strong>MIT explanation (review):</strong>
<a href="https://ocw.mit.edu/courses/res-6-012-introduction-to-probability-spring-2018/resources/probability-mass-functions/">05.3 Probability Mass Functions</a>.
</p>
<p>A random variable identifies the numerical values that may be observed. Its
distribution adds the missing information: how probability is divided among
those values.</p>
<p>For a discrete random variable <span class="math inline">\(X\)</span>, the <strong>probability mass function (PMF)</strong>
is</p>
<p><span class="math display">\[
p_X(x)=P(X=x).
\]</span></p>
<p>Read this notation in parts:</p>
<table>
<thead>
<tr class="header">
<th>Symbol</th>
<th>Meaning</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(X\)</span></td>
<td>the random variable</td>
</tr>
<tr class="even">
<td><span class="math inline">\(x\)</span></td>
<td>one possible numerical value</td>
</tr>
<tr class="odd">
<td><span class="math inline">\(p_X\)</span></td>
<td>the PMF belonging to <span class="math inline">\(X\)</span></td>
</tr>
<tr class="even">
<td><span class="math inline">\(p_X(x)\)</span></td>
<td>the probability that <span class="math inline">\(X\)</span> equals exactly <span class="math inline">\(x\)</span></td>
</tr>
</tbody>
</table>
<p>A valid PMF must satisfy</p>
<p><span class="math display">\[
p_X(x)\ge 0\quad\text{for every }x,
\qquad
\sum_{x\in\mathcal X}p_X(x)=1,
\]</span></p>
<p>where <span class="math inline">\(\mathcal X\)</span> is the support of <span class="math inline">\(X\)</span>. The first rule prevents negative
probability. The second says that one of the possible values must occur.</p>
<p>For the deal indicator, <span class="math inline">\(X\in\{0,1\}\)</span>:</p>
<p><span class="math display">\[
p_X(0)=\frac{559}{1441},
\qquad
p_X(1)=\frac{882}{1441}.
\]</span></p>
<div class="sourceCode" id="cb37"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb37-1"><a href="b03.html#cb37-1" tabindex="-1"></a>deal_pmf <span class="ot">&lt;-</span> <span class="fu">prop.table</span>(</span>
<span id="cb37-2"><a href="b03.html#cb37-2" tabindex="-1"></a>  <span class="fu">table</span>(<span class="fu">factor</span>(sharks<span class="sc">$</span>deal_on_show, <span class="at">levels =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>)))</span>
<span id="cb37-3"><a href="b03.html#cb37-3" tabindex="-1"></a>)</span>
<span id="cb37-4"><a href="b03.html#cb37-4" tabindex="-1"></a><span class="fu">names</span>(deal_pmf) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;0: no on-air deal&quot;</span>, <span class="st">&quot;1: on-air deal&quot;</span>)</span>
<span id="cb37-5"><a href="b03.html#cb37-5" tabindex="-1"></a>deal_pmf</span></code></pre></div>
<pre><code>## 0: no on-air deal    1: on-air deal 
##         0.3879251         0.6120749</code></pre>
<div class="sourceCode" id="cb39"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb39-1"><a href="b03.html#cb39-1" tabindex="-1"></a><span class="fu">sum</span>(deal_pmf)</span></code></pre></div>
<pre><code>## [1] 1</code></pre>
<p>For season <span class="math inline">\(S\)</span>, the empirical PMF assigns each season its relative frequency
under the uniform record-selection experiment:</p>
<div class="sourceCode" id="cb41"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb41-1"><a href="b03.html#cb41-1" tabindex="-1"></a>season_pmf</span></code></pre></div>
<pre><code>## 
##          1          2          3          4          5          6          7 
## 0.04441360 0.02498265 0.04163775 0.07147814 0.08049965 0.08049965 0.08049965 
##          8          9         10         11         12         13         14 
## 0.06662040 0.06662040 0.06384455 0.06662040 0.06939625 0.06662040 0.06037474 
##         15         16 
## 0.06037474 0.05551700</code></pre>
<div class="sourceCode" id="cb43"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb43-1"><a href="b03.html#cb43-1" tabindex="-1"></a><span class="fu">sum</span>(season_pmf)</span></code></pre></div>
<pre><code>## [1] 1</code></pre>
<p><img src="B03-relationships_files/figure-html/b03-season-pmf-plot-1.png" width="672" /></p>
<p>The bar above season 5 has height
<span class="math inline">\(p_S(5)=P(S=5)=116/1441\approx0.080\)</span>. A PMF is represented by separated
probability masses because <span class="math inline">\(S\)</span> can take only the listed discrete values.
The term <strong>probability density function (PDF)</strong> is reserved for continuous
random variables and is introduced later in the course.</p>
</div>
<div id="a-cdf-accumulates-probability-up-to-a-threshold" class="section level3 hasAnchor">
<h3>A CDF accumulates probability up to a threshold<a href="b03.html#a-cdf-accumulates-probability-up-to-a-threshold" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p class="concept-video">
<strong>MIT explanation (review):</strong>
<a href="https://ocw.mit.edu/courses/res-6-012-introduction-to-probability-spring-2018/resources/cumulative-distribution-functions/">08.7 Cumulative Distribution Functions</a>.
</p>
<p>The PMF asks about one exact value. The <strong>cumulative distribution function
(CDF)</strong> asks how much probability has accumulated at or below a chosen
threshold. Imagine moving from left to right across the PMF and keeping a
running total.</p>
<p>For any random variable <span class="math inline">\(X\)</span>,</p>
<p><span class="math display">\[
F_X(a)=P(X\le a).
\]</span></p>
<p>Here <span class="math inline">\(a\)</span> is a threshold, not necessarily a value in the support. For a
discrete random variable,</p>
<p><span class="math display">\[
F_X(a)=\sum_{x\le a}p_X(x).
\]</span></p>
<p>For season, each CDF value is the current PMF value plus all earlier PMF
values:</p>
<div class="sourceCode" id="cb45"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb45-1"><a href="b03.html#cb45-1" tabindex="-1"></a>s_values <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(<span class="fu">names</span>(season_pmf))</span>
<span id="cb45-2"><a href="b03.html#cb45-2" tabindex="-1"></a>p_values <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(season_pmf)</span>
<span id="cb45-3"><a href="b03.html#cb45-3" tabindex="-1"></a>season_distribution <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb45-4"><a href="b03.html#cb45-4" tabindex="-1"></a>  <span class="at">season =</span> s_values,</span>
<span id="cb45-5"><a href="b03.html#cb45-5" tabindex="-1"></a>  <span class="at">pmf =</span> p_values,</span>
<span id="cb45-6"><a href="b03.html#cb45-6" tabindex="-1"></a>  <span class="at">cdf =</span> <span class="fu">cumsum</span>(p_values)</span>
<span id="cb45-7"><a href="b03.html#cb45-7" tabindex="-1"></a>)</span>
<span id="cb45-8"><a href="b03.html#cb45-8" tabindex="-1"></a>season_distribution</span></code></pre></div>
<pre><code>##    season        pmf        cdf
## 1       1 0.04441360 0.04441360
## 2       2 0.02498265 0.06939625
## 3       3 0.04163775 0.11103400
## 4       4 0.07147814 0.18251214
## 5       5 0.08049965 0.26301180
## 6       6 0.08049965 0.34351145
## 7       7 0.08049965 0.42401110
## 8       8 0.06662040 0.49063151
## 9       9 0.06662040 0.55725191
## 10     10 0.06384455 0.62109646
## 11     11 0.06662040 0.68771686
## 12     12 0.06939625 0.75711312
## 13     13 0.06662040 0.82373352
## 14     14 0.06037474 0.88410826
## 15     15 0.06037474 0.94448300
## 16     16 0.05551700 1.00000000</code></pre>
<p>For example,</p>
<p><span class="math display">\[
F_S(3)=P(S\le3)
=p_S(1)+p_S(2)+p_S(3)
=\frac{160}{1441}\approx0.111.
\]</span></p>
<p><img src="B03-relationships_files/figure-html/b03-season-cdf-1.png" width="672" /></p>
<p>A CDF accumulates probability as the threshold moves from left to right. It
can stay flat or rise, but it cannot fall. It begins near 0 before any possible
values and reaches 1 after all possible values have been included.</p>
<p>For a discrete variable, the CDF is a step graph. It stays flat between
possible values and jumps at each value that has positive probability. A
larger jump means that more probability is attached to that value.</p>
<p>For the deal indicator:</p>
<p><span class="math display">\[
F_X(a)=
\begin{cases}
0, &amp; a&lt;0,\\
1-p, &amp; 0\le a&lt;1,\\
1, &amp; a\ge1,
\end{cases}
\]</span></p>
<p>where <span class="math inline">\(p=P(X=1)\)</span>. Thus <span class="math inline">\(p_X(1)=P(X=1)=p\)</span>, while
<span class="math inline">\(F_X(1)=P(X\le1)=1\)</span>. The PMF measures mass at exactly 1; the CDF includes
all mass through 1.</p>
</div>
<div id="expectation-is-the-distributions-weighted-centre" class="section level3 hasAnchor">
<h3>Expectation is the distribution’s weighted centre<a href="b03.html#expectation-is-the-distributions-weighted-centre" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p class="concept-video">
<strong>MIT explanation (review):</strong>
<a href="https://ocw.mit.edu/courses/res-6-012-introduction-to-probability-spring-2018/resources/expectation/">05.8 Expectation</a>.
</p>
<p>A distribution can contain many possible values and probabilities.
<strong>Expectation</strong> summarises its centre in one number. Values with larger
probabilities receive more weight:</p>
<p><span class="math display">\[
E[X]=\sum_{x\in\mathcal X}x\,p_X(x).
\]</span></p>
<p>This definition applies when the probability-weighted sum is well defined and
finite.</p>
<p>The notation <span class="math inline">\(E[X]\)</span> is read “the expected value of <span class="math inline">\(X\)</span>.” The calculation
multiplies each possible value by its probability and adds the contributions.
It can also be viewed as the balance point of the probability distribution.</p>
<p>Expectation is a property of the specified distribution, not a prediction
that one observation will equal that number. It need not belong to the
support. The empirical expected season is about 8.8, for example, but there is
no Season 8.8.</p>
<p>For the deal indicator,</p>
<p><span class="math display">\[
E[X]=0(1-p)+1(p)=p.
\]</span></p>
<p>This identity explains why the mean of a 0/1 variable equals its proportion of
1s.</p>
<div class="sourceCode" id="cb47"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb47-1"><a href="b03.html#cb47-1" tabindex="-1"></a>s <span class="ot">&lt;-</span> season_distribution<span class="sc">$</span>season</span>
<span id="cb47-2"><a href="b03.html#cb47-2" tabindex="-1"></a>p_s <span class="ot">&lt;-</span> season_distribution<span class="sc">$</span>pmf</span>
<span id="cb47-3"><a href="b03.html#cb47-3" tabindex="-1"></a></span>
<span id="cb47-4"><a href="b03.html#cb47-4" tabindex="-1"></a><span class="fu">c</span>(</span>
<span id="cb47-5"><a href="b03.html#cb47-5" tabindex="-1"></a>  <span class="at">E_X =</span> <span class="dv">0</span> <span class="sc">*</span> (<span class="dv">1</span> <span class="sc">-</span> p_hat) <span class="sc">+</span> <span class="dv">1</span> <span class="sc">*</span> p_hat,</span>
<span id="cb47-6"><a href="b03.html#cb47-6" tabindex="-1"></a>  <span class="at">E_S_from_pmf =</span> <span class="fu">sum</span>(s <span class="sc">*</span> p_s),</span>
<span id="cb47-7"><a href="b03.html#cb47-7" tabindex="-1"></a>  <span class="at">observed_mean_season =</span> <span class="fu">mean</span>(sharks<span class="sc">$</span>season)</span>
<span id="cb47-8"><a href="b03.html#cb47-8" tabindex="-1"></a>)</span></code></pre></div>
<pre><code>##                  E_X         E_S_from_pmf observed_mean_season 
##            0.6120749            8.7959750            8.7959750</code></pre>
<p>Under independent repetitions of the same distribution, provided
<span class="math inline">\(E[|X|]&lt;\infty\)</span>, the sample average tends to become close to <span class="math inline">\(E[X]\)</span> as the
number of observations grows. This long-run interpretation does not make the
expected value a guarantee for a single observation.</p>
</div>
<div id="expectation-after-transforming-a-variable" class="section level3 hasAnchor">
<h3>Expectation after transforming a variable<a href="b03.html#expectation-after-transforming-a-variable" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>If <span class="math inline">\(g\)</span> transforms each possible value of <span class="math inline">\(X\)</span>, the expected transformed
value is</p>
<p><span class="math display">\[
E[g(X)]=\sum_{x\in\mathcal X}g(x)p_X(x).
\]</span></p>
<p>The probabilities do not change: apply <span class="math inline">\(g\)</span> to each possible value, weight
the transformed values by the original PMF, and add. For example,</p>
<p><span class="math display">\[
E[S^2]=\sum_s s^2p_S(s).
\]</span></p>
<div class="sourceCode" id="cb49"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb49-1"><a href="b03.html#cb49-1" tabindex="-1"></a><span class="fu">c</span>(</span>
<span id="cb49-2"><a href="b03.html#cb49-2" tabindex="-1"></a>  <span class="at">E_S =</span> <span class="fu">sum</span>(s <span class="sc">*</span> p_s),</span>
<span id="cb49-3"><a href="b03.html#cb49-3" tabindex="-1"></a>  <span class="at">E_S_squared =</span> <span class="fu">sum</span>(s<span class="sc">^</span><span class="dv">2</span> <span class="sc">*</span> p_s)</span>
<span id="cb49-4"><a href="b03.html#cb49-4" tabindex="-1"></a>)</span></code></pre></div>
<pre><code>##         E_S E_S_squared 
##    8.795975   95.505205</code></pre>
<p>Lecture 4 uses this rule to measure spread around <span class="math inline">\(E[X]\)</span>.</p>
</div>
<div id="model-expectation-and-the-sample-mean" class="section level3 hasAnchor">
<h3>Model expectation and the sample mean<a href="b03.html#model-expectation-and-the-sample-mean" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>For observed values <span class="math inline">\(x_1,\ldots,x_n\)</span>, the sample mean is</p>
<p><span class="math display">\[
\bar{x}=\frac{1}{n}\sum_{i=1}^n x_i.
\]</span></p>
<p>If the empirical distribution assigns probability <span class="math inline">\(1/n\)</span> to every observed
row, its expectation is</p>
<p><span class="math display">\[
\sum_{i=1}^n x_i\frac{1}{n}=\bar{x}.
\]</span></p>
<p>The numerical answers agree, but the terms identify different objects.
Expectation describes a probability distribution; the sample mean summarises
observed data.</p>
<div class="sourceCode" id="cb51"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb51-1"><a href="b03.html#cb51-1" tabindex="-1"></a>w <span class="ot">&lt;-</span> sharks<span class="sc">$</span>description_words</span>
<span id="cb51-2"><a href="b03.html#cb51-2" tabindex="-1"></a><span class="fu">c</span>(</span>
<span id="cb51-3"><a href="b03.html#cb51-3" tabindex="-1"></a>  <span class="at">mean_words =</span> <span class="fu">mean</span>(w),</span>
<span id="cb51-4"><a href="b03.html#cb51-4" tabindex="-1"></a>  <span class="at">empirical_expectation =</span> <span class="fu">sum</span>(w <span class="sc">*</span> <span class="fu">rep</span>(<span class="dv">1</span> <span class="sc">/</span> <span class="fu">length</span>(w), <span class="fu">length</span>(w)))</span>
<span id="cb51-5"><a href="b03.html#cb51-5" tabindex="-1"></a>)</span></code></pre></div>
<pre><code>##            mean_words empirical_expectation 
##              4.995142              4.995142</code></pre>
<p>Both calculations give about 5.0 words for these 1,441 records. Treating this
as the expected description length for future pitches requires additional
population and stability assumptions.</p>
</div>
</div>
<div id="after-class-2" class="section level2 hasAnchor course-phase phase-after">
<h2>After class<a href="b03.html#after-class-2" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="retrieval-1" class="section level3 hasAnchor">
<h3>Retrieval<a href="b03.html#retrieval-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<ol style="list-style-type: decimal">
<li>What information does a PMF add to the support of a random variable?</li>
<li>What two requirements must every PMF satisfy?</li>
<li>What is the difference between <span class="math inline">\(p_X(x)\)</span> and <span class="math inline">\(F_X(x)\)</span>?</li>
<li>Why can an expectation be a value the random variable never takes?</li>
<li>What does <span class="math inline">\(E[g(X)]\)</span> average?</li>
<li>When does an empirical expectation equal the sample mean?</li>
</ol>
<details>
<summary>
Check your answers
</summary>
<ol style="list-style-type: decimal">
<li>The support lists possible values; the PMF assigns probability to each
value.</li>
<li>Every probability mass is non-negative, and the masses sum to 1.</li>
<li><span class="math inline">\(p_X(x)=P(X=x)\)</span> is the mass at exactly <span class="math inline">\(x\)</span>;
<span class="math inline">\(F_X(x)=P(X\le x)\)</span> is all probability accumulated through <span class="math inline">\(x\)</span>.</li>
<li>Expectation is a probability-weighted average and need not belong to the
support.</li>
<li>It averages the transformed values <span class="math inline">\(g(x)\)</span>, weighted by <span class="math inline">\(p_X(x)\)</span>.</li>
<li>They are equal when the empirical distribution assigns mass <span class="math inline">\(1/n\)</span> to
each of the <span class="math inline">\(n\)</span> observed values.</li>
</ol>
</details>
</div>
<div id="practice-1" class="section level3 hasAnchor">
<h3>Practice<a href="b03.html#practice-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Let <span class="math inline">\(Y\)</span> have support <span class="math inline">\(\{0,1,2\}\)</span> and PMF
<span class="math inline">\(p_Y(0)=0.2\)</span>, <span class="math inline">\(p_Y(1)=0.5\)</span>, and <span class="math inline">\(p_Y(2)=0.3\)</span>.</p>
<ol style="list-style-type: decimal">
<li>Verify that this is a valid PMF.</li>
<li>Calculate <span class="math inline">\(F_Y(0.5)\)</span> and <span class="math inline">\(F_Y(1)\)</span>.</li>
<li>Calculate <span class="math inline">\(E[Y]\)</span> and <span class="math inline">\(E[Y^2]\)</span>.</li>
<li>For the deal indicator with <span class="math inline">\(p=882/1441\)</span>, calculate <span class="math inline">\(F_X(0.4)\)</span>.</li>
<li>Use the season CDF to calculate <span class="math inline">\(P(3&lt;S\le6)\)</span>.</li>
</ol>
<details>
<summary>
Check your answers
</summary>
<ol style="list-style-type: decimal">
<li>All masses are non-negative and <span class="math inline">\(0.2+0.5+0.3=1\)</span>.</li>
<li><span class="math inline">\(F_Y(0.5)=P(Y=0)=0.2\)</span>, while
<span class="math inline">\(F_Y(1)=P(Y\le1)=0.2+0.5=0.7\)</span>.</li>
<li><span class="math inline">\(E[Y]=0(0.2)+1(0.5)+2(0.3)=1.1\)</span>, and
<span class="math inline">\(E[Y^2]=0^2(0.2)+1^2(0.5)+2^2(0.3)=1.7\)</span>.</li>
<li>Because <span class="math inline">\(0\le0.4&lt;1\)</span>,
<span class="math inline">\(F_X(0.4)=P(X=0)=559/1441\approx0.388\)</span>.</li>
<li><span class="math inline">\(P(3&lt;S\le6)=F_S(6)-F_S(3)=335/1441\approx0.232\)</span>.</li>
</ol>
</details>
</div>
<div id="worked-exam-interpretation-1" class="section level3 hasAnchor">
<h3>Worked exam interpretation<a href="b03.html#worked-exam-interpretation-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p><strong>Question.</strong> R reports <code>mean(deal_on_show) = 0.612</code>. Explain this
number as both a sample mean and an empirical expectation.</p>
<details>
<summary>
Check a model answer
</summary>
<p>Because the indicator equals 1 for an on-air agreement, its sample mean is the
observed deal proportion: 61.2% of the 1,441 records. If the empirical
distribution assigns mass <span class="math inline">\(1/1441\)</span> to each record, its expectation is the same
weighted average, 0.612. This does not show later venture success or guarantee
the probability for a future pitch.</p>
</details>
<p>Practise now in <a href="b-ep01.html#b-ep01">Tutorial 1</a>, then continue to
<a href="b04.html#b04">Lecture 4: Variance, conditioning, and belief updating</a>.</p>
<p>Formula sheet: <a href="formula-sheet.html#formula-l3">Lecture 3 formulas</a>.</p>
<p>For a more formal explanation, consult
<a href="https://tilburguniversity.on.worldcat.org/oclc/317545871">Nieuwenhuis, <em>Statistical Methods for Business and Economics</em></a>,
Chapter 8.</p>
</div>
</div>

</div>
            </section>

          </div>
        </div>
      </div>
<a href="b02.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="b-ep01.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
  "sharing": null,
  "fontsettings": {
    "theme": "white",
    "family": "sans",
    "size": 2
  },
  "edit": null,
  "history": {
    "link": null,
    "text": null
  },
  "view": {
    "link": null,
    "text": null
  },
  "download": null,
  "search": {
    "engine": "fuse",
    "options": null
  },
  "toc": {
    "collapse": "section",
    "scroll_highlight": true
  },
  "toolbar": {
    "position": "fixed"
  }
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
