<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Lecture 7: Samples, parameters, and estimators | Online Textbook for the Learning Line “Quantitative Methods to Understand E&amp;BI”</title>
  <meta name="description" content="An online textbook for the learning line Quantitative Methods within Entrepreneurship and Business Innovation Bachelor Program at Tilburg University." />
  <meta name="generator" content="bookdown 0.47 and GitBook 2.6.7" />

  <meta property="og:title" content="Lecture 7: Samples, parameters, and estimators | Online Textbook for the Learning Line “Quantitative Methods to Understand E&amp;BI”" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="An online textbook for the learning line Quantitative Methods within Entrepreneurship and Business Innovation Bachelor Program at Tilburg University." />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Lecture 7: Samples, parameters, and estimators | Online Textbook for the Learning Line “Quantitative Methods to Understand E&amp;BI”" />
  
  <meta name="twitter:description" content="An online textbook for the learning line Quantitative Methods within Entrepreneurship and Business Innovation Bachelor Program at Tilburg University." />
  




  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="b06.html"/>
<link rel="next" href="b08.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

<link rel="stylesheet" href="styles.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="book-title"><a href="./">QM to Understand E&amp;BI</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Welcome</a></li>
<li class="part"><span><b>I QM Basic</b></span></li>
<li class="chapter" data-level="" data-path="basic-course.html"><a href="basic-course.html"><i class="fa fa-check"></i>QM Basic: Course overview</a></li>
<li class="chapter" data-level="" data-path="b01.html"><a href="b01.html"><i class="fa fa-check"></i>Lecture 1: Introduction to Data Analysis</a></li>
<li class="chapter" data-level="" data-path="b02.html"><a href="b02.html"><i class="fa fa-check"></i>Lecture 2: Probability foundations and random variables</a></li>
<li class="chapter" data-level="" data-path="b03.html"><a href="b03.html"><i class="fa fa-check"></i>Lecture 3: Discrete distributions and expectation</a></li>
<li class="chapter" data-level="" data-path="b-ep01.html"><a href="b-ep01.html"><i class="fa fa-check"></i>Tutorial 1: Evidence and probability foundations</a></li>
<li class="chapter" data-level="" data-path="b04.html"><a href="b04.html"><i class="fa fa-check"></i>Lecture 4: Variance, conditioning, and belief updating</a></li>
<li class="chapter" data-level="" data-path="b05.html"><a href="b05.html"><i class="fa fa-check"></i>Lecture 5: Joint random variables, covariance, and correlation</a></li>
<li class="chapter" data-level="" data-path="b-ep02.html"><a href="b-ep02.html"><i class="fa fa-check"></i>Tutorial 2: Conditioning and relationships</a></li>
<li class="chapter" data-level="" data-path="b06.html"><a href="b06.html"><i class="fa fa-check"></i>Lecture 6: Continuous distributions and the normal model</a></li>
<li class="chapter" data-level="" data-path="b07.html"><a href="b07.html"><i class="fa fa-check"></i>Lecture 7: Samples, parameters, and estimators</a></li>
<li class="chapter" data-level="" data-path="b08.html"><a href="b08.html"><i class="fa fa-check"></i>Lecture 8: Sampling distributions and the central limit theorem</a></li>
<li class="chapter" data-level="" data-path="b-ep03.html"><a href="b-ep03.html"><i class="fa fa-check"></i>Tutorial 3: Sampling and standard errors</a></li>
<li class="chapter" data-level="" data-path="b09.html"><a href="b09.html"><i class="fa fa-check"></i>Lecture 9: Confidence intervals and tests against zero</a></li>
<li class="chapter" data-level="" data-path="b10.html"><a href="b10.html"><i class="fa fa-check"></i>Lecture 10: Hypothesis testing, errors, and power</a></li>
<li class="chapter" data-level="" data-path="b-ep04.html"><a href="b-ep04.html"><i class="fa fa-check"></i>Tutorial 4: Inference and tests against zero</a></li>
<li class="chapter" data-level="" data-path="formula-sheet.html"><a href="formula-sheet.html"><i class="fa fa-check"></i>QM Basic Formula Sheet</a></li>
<li class="chapter" data-level="" data-path="basic-mock-exam.html"><a href="basic-mock-exam.html"><i class="fa fa-check"></i>Mock Exam: QM Basic</a></li>
<li class="part"><span><b>II QM Intermediate</b></span></li>
<li class="chapter" data-level="" data-path="intermediate-course.html"><a href="intermediate-course.html"><i class="fa fa-check"></i>QM Intermediate: Course overview</a></li>
<li class="chapter" data-level="" data-path="i01.html"><a href="i01.html"><i class="fa fa-check"></i>Lecture 1: Simple linear regression</a></li>
<li class="chapter" data-level="" data-path="i02.html"><a href="i02.html"><i class="fa fa-check"></i>Lecture 2: Regression assumptions and coefficient inference</a></li>
<li class="chapter" data-level="" data-path="i03.html"><a href="i03.html"><i class="fa fa-check"></i>Lecture 3: Model fit and overall usefulness</a></li>
<li class="chapter" data-level="" data-path="i-ep01.html"><a href="i-ep01.html"><i class="fa fa-check"></i>Tutorial 1: Simple regression and model usefulness</a></li>
<li class="chapter" data-level="" data-path="i04.html"><a href="i04.html"><i class="fa fa-check"></i>Lecture 4: Multiple linear regression and controls</a></li>
<li class="chapter" data-level="" data-path="i05.html"><a href="i05.html"><i class="fa fa-check"></i>Lecture 5: Dummy predictors and joint usefulness</a></li>
<li class="chapter" data-level="" data-path="i06.html"><a href="i06.html"><i class="fa fa-check"></i>Lecture 6: Interactions and polynomial terms</a></li>
<li class="chapter" data-level="" data-path="i-ep02.html"><a href="i-ep02.html"><i class="fa fa-check"></i>Tutorial 2: Multiple regression and extensions</a></li>
<li class="chapter" data-level="" data-path="intermediate-code-sheet.html"><a href="intermediate-code-sheet.html"><i class="fa fa-check"></i>QM Intermediate Code Sheet</a></li>
<li class="chapter" data-level="" data-path="intermediate-mock-exam.html"><a href="intermediate-mock-exam.html"><i class="fa fa-check"></i>Mock Exam: QM Intermediate</a></li>
<li class="part"><span><b>III QM Advanced</b></span></li>
<li class="chapter" data-level="" data-path="advanced-course.html"><a href="advanced-course.html"><i class="fa fa-check"></i>QM Advanced: Course overview</a></li>
<li class="part"><span><b>IV Supplementary resources</b></span></li>
<li class="chapter" data-level="" data-path="r-refresher.html"><a href="r-refresher.html"><i class="fa fa-check"></i>R Refresher</a></li>
<li class="chapter" data-level="" data-path="math-refresher.html"><a href="math-refresher.html"><i class="fa fa-check"></i>Mathematics Refresher</a></li>
<li class="chapter" data-level="" data-path="videos.html"><a href="videos.html"><i class="fa fa-check"></i>External Video Guide</a></li>
<li class="divider"></li>
<li class="book-footer">Quantitative Methods learning line</li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Online Textbook for the Learning Line “Quantitative Methods to Understand E&amp;BI”</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="b07" class="section level1 hasAnchor">
<h1>Lecture 7: Samples, parameters, and estimators<a href="b07.html#b07" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<div class="outcomes">
<span class="label">By the end of Lecture 7, you can</span>
<ul>
<li>
distinguish a population, sampling frame, sample, and target population;
</li>
<li>
explain simple random sampling with and without replacement;
</li>
<li>
distinguish parameters, estimators, and estimates;
</li>
<li>
calculate sample means, proportions, variances, and standard deviations;
</li>
<li>
explain the <span class="math inline">\(n-1\)</span> degrees of freedom in a sample variance;
</li>
<li>
explain why random sampling supports generalisation but does not guarantee it.
</li>
</ul>
</div>
<div id="before-class-8" class="section level2 hasAnchor course-phase phase-before">
<h2>Before class<a href="b07.html#before-class-8" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div class="video-prep">
<p><span class="label">Video preparation</span><br>
Watch <a href="https://www.youtube.com/watch?v=nuXDb9B3y0M">The Sample
Mean and Some Terminology</a>. Be ready to distinguish a population quantity
from a statistic calculated after a sample is observed.</p>
</div>
<p>If subscripts or summation notation are not secure, review
<a href="math-refresher.html#math-refresher">Mathematics Refresher: indices and sums</a>.</p>
<p>Suppose we want the mean initial equity offered across the 1,441 recorded
pitches in completed Seasons 1–16, but can inspect only 100 randomly selected
records. Identify:</p>
<ol style="list-style-type: decimal">
<li>the finite population;</li>
<li>the population variable;</li>
<li>the sample;</li>
<li>the parameter of interest;</li>
<li>a statistic that could estimate it.</li>
</ol>
<details>
<summary>
Check your preparation
</summary>
<p>The finite population is the 1,441 recorded pitches; the variable is initial
equity offered; the sample is the 100 selected records; the parameter is the
population mean equity offer; and the sample mean is a suitable estimator.</p>
</details>
</div>
<div id="in-class-8" class="section level2 hasAnchor course-phase phase-in-class">
<h2>In class<a href="b07.html#in-class-8" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p class="concept-video">
<strong>MIT explanation (review):</strong>
<a href="https://ocw.mit.edu/courses/res-6-012-introduction-to-probability-spring-2018/resources/the-sample-mean-and-some-terminology/">20.3 The Sample Mean and Some Terminology</a>.
</p>
<div id="define-the-population-before-calculating" class="section level3 hasAnchor">
<h3>Define the population before calculating<a href="b07.html#define-the-population-before-calculating" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>A <strong>population</strong> is the complete set of units about which a question is asked.
A <strong>sample</strong> is the subset observed for analysis. A <strong>sampling frame</strong> is the
list or mechanism from which the sample is selected. The <strong>target population</strong>
is the broader group to which we hope to generalise.</p>
<p>These sets need not coincide. The teaching file is a near-census of recorded
US <em>Shark Tank</em> pitches from completed Seasons 1–16, but it is not a random
sample of all entrepreneurs, all funding pitches, or even all applicants to
the show. Randomly sampling rows from this file supports inference to the
1,441-file population. It does not remove the show’s selection process.</p>
</div>
<div id="simple-random-sampling" class="section level3 hasAnchor">
<h3>Simple random sampling<a href="b07.html#simple-random-sampling" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>In a simple random sample of size <span class="math inline">\(n\)</span>, every set of <span class="math inline">\(n\)</span> population units
has the same chance of selection.</p>
<ul>
<li><strong>With replacement:</strong> a selected unit is returned before the next draw.
Draws are independent and each draw has the same distribution.</li>
<li><strong>Without replacement:</strong> a unit cannot be selected twice. Draws are
dependent, although every draw has the same marginal distribution.</li>
</ul>
<p>When a without-replacement sample is a small fraction of a large population,
the dependence is weak. This course uses the 10% condition as a practical
check: if <span class="math inline">\(n\le0.10N\)</span>, the usual independent-sample standard-error formulas
are a good approximation.</p>
<div class="sourceCode" id="cb104"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb104-1"><a href="b07.html#cb104-1" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb104-2"><a href="b07.html#cb104-2" tabindex="-1"></a>sample_rows <span class="ot">&lt;-</span> <span class="fu">sample</span>(<span class="fu">seq_len</span>(<span class="fu">nrow</span>(sharks)), <span class="at">size =</span> <span class="dv">100</span>, <span class="at">replace =</span> <span class="cn">FALSE</span>)</span>
<span id="cb104-3"><a href="b07.html#cb104-3" tabindex="-1"></a>pitch_sample <span class="ot">&lt;-</span> sharks[sample_rows, ]</span>
<span id="cb104-4"><a href="b07.html#cb104-4" tabindex="-1"></a></span>
<span id="cb104-5"><a href="b07.html#cb104-5" tabindex="-1"></a><span class="fu">nrow</span>(pitch_sample)</span></code></pre></div>
<pre><code>## [1] 100</code></pre>
<p>Here <span class="math inline">\(100/1441\approx0.069&lt;0.10\)</span>.</p>
</div>
<div id="sampling-method-determines-the-evidence-boundary" class="section level3 hasAnchor">
<h3>Sampling method determines the evidence boundary<a href="b07.html#sampling-method-determines-the-evidence-boundary" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The number of rows does not identify the sampling design. Ask how units entered
the data:</p>
<table>
<colgroup>
<col width="33%" />
<col width="33%" />
<col width="33%" />
</colgroup>
<thead>
<tr class="header">
<th>Method</th>
<th>How units enter</th>
<th>Main implication</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Simple random sample</td>
<td>selected by a known random mechanism</td>
<td>supports design-based generalisation to the frame</td>
</tr>
<tr class="even">
<td>Stratified random sample</td>
<td>randomly selected within defined groups</td>
<td>can guarantee representation of important groups</td>
</tr>
<tr class="odd">
<td>Convenience sample</td>
<td>selected because they are easy to reach</td>
<td>vulnerable to selection bias</td>
</tr>
<tr class="even">
<td>Voluntary-response sample</td>
<td>units choose whether to respond</td>
<td>people with stronger views may be over-represented</td>
</tr>
<tr class="odd">
<td>Census of a frame</td>
<td>every unit in the available frame is recorded</td>
<td>no sampling error for that frame, but coverage error can remain</td>
</tr>
</tbody>
</table>
<p>The Shark Tank teaching file is close to a census of its recorded-pitch frame.
When we draw 100 rows for an inference exercise, the randomisation is created
by our row-sampling procedure. It does not make the television programme’s
selection of pitches random.</p>
</div>
<div id="parameters-estimators-and-estimates" class="section level3 hasAnchor">
<h3>Parameters, estimators, and estimates<a href="b07.html#parameters-estimators-and-estimates" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>A <strong>parameter</strong> is a fixed numerical property of a population, usually
unknown. An <strong>estimator</strong> is a rule based on random sample variables. Its value
changes from sample to sample. An <strong>estimate</strong> is the number obtained from one
realised sample.</p>
<p>For a random sample <span class="math inline">\(X_1,\ldots,X_n\)</span>:</p>
<p><span class="math display">\[
\bar X=\frac{1}{n}\sum_{i=1}^{n}X_i
\]</span></p>
<p>is an estimator of the population mean <span class="math inline">\(\mu\)</span>. After observing values
<span class="math inline">\(x_1,\ldots,x_n\)</span>,</p>
<p><span class="math display">\[
\bar x=\frac{1}{n}\sum_{i=1}^{n}x_i
\]</span></p>
<p>is the realised estimate. Capital letters describe random quantities before
sampling; lower-case letters describe observed values.</p>
<p>For a 0/1 variable, the sample proportion is a sample mean:</p>
<p><span class="math display">\[
\widehat P=\frac{1}{n}\sum_{i=1}^{n}X_i.
\]</span></p>
<p>Its realised value is written <span class="math inline">\(\hat p\)</span>.</p>
<p>The usual sample variance and standard deviation are</p>
<p><span class="math display">\[
S^2=\frac{1}{n-1}\sum_{i=1}^{n}(X_i-\bar X)^2,
\qquad S=\sqrt{S^2}.
\]</span></p>
<p>The denominator <span class="math inline">\(n-1\)</span> makes <span class="math inline">\(S^2\)</span> an unbiased estimator of population
variance under independent random sampling.</p>
</div>
<div id="why-the-sample-variance-has-n-1-degrees-of-freedom" class="section level3 hasAnchor">
<h3>Why the sample variance has <span class="math inline">\(n-1\)</span> degrees of freedom<a href="b07.html#why-the-sample-variance-has-n-1-degrees-of-freedom" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Once <span class="math inline">\(\bar X\)</span> has been calculated from the same sample, the deviations must
satisfy</p>
<p><span class="math display">\[
\sum_{i=1}^{n}(X_i-\bar X)=0.
\]</span></p>
<p>If <span class="math inline">\(n-1\)</span> deviations are known, the final deviation is forced to make the sum
zero. Only <span class="math inline">\(n-1\)</span> deviations can vary freely: the sample variance has
<span class="math inline">\(n-1\)</span> <strong>degrees of freedom</strong>.</p>
<p>For example, suppose three deviations from a sample mean begin with <span class="math inline">\(2\)</span> and
<span class="math inline">\(-5\)</span>. The third cannot be chosen freely; it must be <span class="math inline">\(3\)</span>. There are three
deviations but only two degrees of freedom.</p>
<p>Using the fitted sample mean makes squared deviations around <span class="math inline">\(\bar X\)</span>
slightly too small on average as a measure of population spread. Dividing by
<span class="math inline">\(n-1\)</span>, rather than <span class="math inline">\(n\)</span>, corrects that downward bias under the random-sample
model. Degrees of freedom count remaining independent information; they are
not a percentage or a probability.</p>
<div class="sourceCode" id="cb106"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb106-1"><a href="b07.html#cb106-1" tabindex="-1"></a><span class="fu">c</span>(</span>
<span id="cb106-2"><a href="b07.html#cb106-2" tabindex="-1"></a>  <span class="at">sample_mean_equity =</span> <span class="fu">mean</span>(pitch_sample<span class="sc">$</span>equity_offered_pct),</span>
<span id="cb106-3"><a href="b07.html#cb106-3" tabindex="-1"></a>  <span class="at">sample_sd_equity =</span> <span class="fu">sd</span>(pitch_sample<span class="sc">$</span>equity_offered_pct),</span>
<span id="cb106-4"><a href="b07.html#cb106-4" tabindex="-1"></a>  <span class="at">sample_deal_proportion =</span> <span class="fu">mean</span>(pitch_sample<span class="sc">$</span>deal_on_show)</span>
<span id="cb106-5"><a href="b07.html#cb106-5" tabindex="-1"></a>)</span></code></pre></div>
<pre><code>##     sample_mean_equity       sample_sd_equity sample_deal_proportion 
##              12.760000               7.707887               0.640000</code></pre>
<p>For this realised sample, <span class="math inline">\(\bar x=12.76\)</span> percentage points,
<span class="math inline">\(s=7.71\)</span> percentage points, and <span class="math inline">\(\hat p=0.64\)</span>.</p>
</div>
<div id="sampling-variability-is-visible" class="section level3 hasAnchor">
<h3>Sampling variability is visible<a href="b07.html#sampling-variability-is-visible" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p><img src="B07-samples-estimators_files/figure-html/b07-population-sample-plot-1.png" width="672" /></p>
<p>The horizontal axis gives equity intervals in percentage points. The vertical
axis is density so the differently sized datasets can be compared by shape;
area over an interval represents a proportion. The pale bars describe all
1,441 records, while the connected points describe the realised sample of 100.
The sample resembles the population but does not reproduce it exactly. A
different random sample would give different estimates. This random
sample-to-sample variation is the uncertainty that sampling distributions
describe.</p>
</div>
<div id="what-random-sampling-can-and-cannot-do" class="section level3 hasAnchor">
<h3>What random sampling can and cannot do<a href="b07.html#what-random-sampling-can-and-cannot-do" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Random selection reduces systematic over-representation within the sampling
frame. It does not guarantee that one realised sample is perfectly balanced.
By chance, a sample can contain unusually many large values or unusually many
deals. Larger samples reduce this random instability.</p>
<p>Random sampling supports generalisation from sample to frame. Random
assignment supports causal comparisons. They answer different design
questions and should not be confused.</p>
</div>
</div>
<div id="after-class-8" class="section level2 hasAnchor course-phase phase-after">
<h2>After class<a href="b07.html#after-class-8" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="retrieval-5" class="section level3 hasAnchor">
<h3>Retrieval<a href="b07.html#retrieval-5" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<ol style="list-style-type: decimal">
<li>What is the difference between a target population and a sampling frame?</li>
<li>Why are draws without replacement dependent?</li>
<li>What is the difference between an estimator and an estimate?</li>
<li>Why is a sample proportion a sample mean?</li>
<li>Why does the sample variance have <span class="math inline">\(n-1\)</span> degrees of freedom?</li>
<li>What does random sampling support that random assignment does not?</li>
</ol>
<details>
<summary>
Check your answers
</summary>
<ol style="list-style-type: decimal">
<li>The target population is the group of substantive interest; the sampling
frame is the set from which units can actually be selected.</li>
<li>Selecting one unit changes which units remain available.</li>
<li>An estimator is a random rule before data are observed; an estimate is its
realised numerical value.</li>
<li>A 0/1 indicator sums to the number of successes, so its mean is the success
proportion.</li>
<li>Estimating the sample mean imposes one constraint: all deviations from it
must sum to zero. Only <span class="math inline">\(n-1\)</span> deviations can vary freely.</li>
<li>Random sampling supports generalisation to the sampling frame; random
assignment supports causal comparison of treatments.</li>
</ol>
</details>
</div>
<div id="practice-5" class="section level3 hasAnchor">
<h3>Practice<a href="b07.html#practice-5" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<ol style="list-style-type: decimal">
<li>For a population of <span class="math inline">\(N=20{,}000\)</span> customers and a simple random sample of
<span class="math inline">\(n=500\)</span>, check the 10% condition.</li>
<li>Write the estimator and realised estimate for the population deal
proportion.</li>
<li>Explain why <span class="math inline">\(\mu\)</span> is fixed while <span class="math inline">\(\bar X\)</span> is random.</li>
<li>Using <code>pitch_sample</code>, calculate the sample mean and sample SD of
<code>description_words</code>.</li>
<li>Explain why this random sample cannot justify conclusions about all US
entrepreneurs.</li>
<li>For a sample of five observations, state the degrees of freedom used to
estimate variance and explain the number.</li>
</ol>
<details>
<summary>
Check your answers
</summary>
<ol style="list-style-type: decimal">
<li><span class="math inline">\(500/20{,}000=0.025&lt;0.10\)</span>, so the condition is satisfied.</li>
<li>The estimator is
<span class="math inline">\(\widehat P=n^{-1}\sum_iX_i\)</span>; the realised estimate is
<span class="math inline">\(\hat p=n^{-1}\sum_ix_i\)</span>.</li>
<li>The population and its mean are treated as fixed; the selected observations,
and therefore their mean, vary across possible samples.</li>
<li><code>mean(pitch_sample$description_words)</code> and
<code>sd(pitch_sample$description_words)</code> give the requested estimates.</li>
<li>The sample was selected from televised records, not from all US
entrepreneurs; random row selection cannot repair that coverage gap.</li>
<li>The degrees of freedom are <span class="math inline">\(5-1=4\)</span>. Once the sample mean is estimated,
four deviations may vary freely and the fifth is fixed by their zero sum.</li>
</ol>
</details>
<p>Continue to <a href="b08.html#b08">Lecture 8: Sampling distributions and the central limit theorem</a>.</p>
<p>Formula sheet: <a href="formula-sheet.html#formula-l7">Lecture 7 formulas</a>.</p>
<p>For a more formal explanation, consult
<a href="https://tilburguniversity.on.worldcat.org/oclc/317545871">Nieuwenhuis, <em>Statistical Methods for Business and Economics</em></a>,
Chapter 12.</p>
</div>
</div>

</div>
            </section>

          </div>
        </div>
      </div>
<a href="b06.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="b08.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
  "sharing": null,
  "fontsettings": {
    "theme": "white",
    "family": "sans",
    "size": 2
  },
  "edit": null,
  "history": {
    "link": null,
    "text": null
  },
  "view": {
    "link": null,
    "text": null
  },
  "download": null,
  "search": {
    "engine": "fuse",
    "options": null
  },
  "toc": {
    "collapse": "section",
    "scroll_highlight": true
  },
  "toolbar": {
    "position": "fixed"
  }
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
