<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Lecture 9: Confidence intervals and tests against zero | Online Textbook for the Learning Line “Quantitative Methods to Understand E&amp;BI”</title>
  <meta name="description" content="An online textbook for the learning line Quantitative Methods within Entrepreneurship and Business Innovation Bachelor Program at Tilburg University." />
  <meta name="generator" content="bookdown 0.47 and GitBook 2.6.7" />

  <meta property="og:title" content="Lecture 9: Confidence intervals and tests against zero | Online Textbook for the Learning Line “Quantitative Methods to Understand E&amp;BI”" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="An online textbook for the learning line Quantitative Methods within Entrepreneurship and Business Innovation Bachelor Program at Tilburg University." />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Lecture 9: Confidence intervals and tests against zero | Online Textbook for the Learning Line “Quantitative Methods to Understand E&amp;BI”" />
  
  <meta name="twitter:description" content="An online textbook for the learning line Quantitative Methods within Entrepreneurship and Business Innovation Bachelor Program at Tilburg University." />
  




  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="b-ep03.html"/>
<link rel="next" href="b10.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

<link rel="stylesheet" href="styles.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="book-title"><a href="./">QM to Understand E&amp;BI</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Welcome</a></li>
<li class="part"><span><b>I QM Basic</b></span></li>
<li class="chapter" data-level="" data-path="basic-course.html"><a href="basic-course.html"><i class="fa fa-check"></i>QM Basic: Course overview</a></li>
<li class="chapter" data-level="" data-path="b01.html"><a href="b01.html"><i class="fa fa-check"></i>Lecture 1: Introduction to Data Analysis</a></li>
<li class="chapter" data-level="" data-path="b02.html"><a href="b02.html"><i class="fa fa-check"></i>Lecture 2: Probability foundations and random variables</a></li>
<li class="chapter" data-level="" data-path="b03.html"><a href="b03.html"><i class="fa fa-check"></i>Lecture 3: Discrete distributions and expectation</a></li>
<li class="chapter" data-level="" data-path="b-ep01.html"><a href="b-ep01.html"><i class="fa fa-check"></i>Tutorial 1: Evidence and probability foundations</a></li>
<li class="chapter" data-level="" data-path="b04.html"><a href="b04.html"><i class="fa fa-check"></i>Lecture 4: Variance, conditioning, and belief updating</a></li>
<li class="chapter" data-level="" data-path="b05.html"><a href="b05.html"><i class="fa fa-check"></i>Lecture 5: Joint random variables, covariance, and correlation</a></li>
<li class="chapter" data-level="" data-path="b-ep02.html"><a href="b-ep02.html"><i class="fa fa-check"></i>Tutorial 2: Conditioning and relationships</a></li>
<li class="chapter" data-level="" data-path="b06.html"><a href="b06.html"><i class="fa fa-check"></i>Lecture 6: Continuous distributions and the normal model</a></li>
<li class="chapter" data-level="" data-path="b07.html"><a href="b07.html"><i class="fa fa-check"></i>Lecture 7: Samples, parameters, and estimators</a></li>
<li class="chapter" data-level="" data-path="b08.html"><a href="b08.html"><i class="fa fa-check"></i>Lecture 8: Sampling distributions and the central limit theorem</a></li>
<li class="chapter" data-level="" data-path="b-ep03.html"><a href="b-ep03.html"><i class="fa fa-check"></i>Tutorial 3: Sampling and standard errors</a></li>
<li class="chapter" data-level="" data-path="b09.html"><a href="b09.html"><i class="fa fa-check"></i>Lecture 9: Confidence intervals and tests against zero</a></li>
<li class="chapter" data-level="" data-path="b10.html"><a href="b10.html"><i class="fa fa-check"></i>Lecture 10: Hypothesis testing, errors, and power</a></li>
<li class="chapter" data-level="" data-path="b-ep04.html"><a href="b-ep04.html"><i class="fa fa-check"></i>Tutorial 4: Inference and tests against zero</a></li>
<li class="chapter" data-level="" data-path="formula-sheet.html"><a href="formula-sheet.html"><i class="fa fa-check"></i>QM Basic Formula Sheet</a></li>
<li class="chapter" data-level="" data-path="basic-mock-exam.html"><a href="basic-mock-exam.html"><i class="fa fa-check"></i>Mock Exam: QM Basic</a></li>
<li class="part"><span><b>II QM Intermediate</b></span></li>
<li class="chapter" data-level="" data-path="intermediate-course.html"><a href="intermediate-course.html"><i class="fa fa-check"></i>QM Intermediate: Course overview</a></li>
<li class="chapter" data-level="" data-path="i01.html"><a href="i01.html"><i class="fa fa-check"></i>Lecture 1: Simple linear regression</a></li>
<li class="chapter" data-level="" data-path="i02.html"><a href="i02.html"><i class="fa fa-check"></i>Lecture 2: Regression assumptions and coefficient inference</a></li>
<li class="chapter" data-level="" data-path="i03.html"><a href="i03.html"><i class="fa fa-check"></i>Lecture 3: Model fit and overall usefulness</a></li>
<li class="chapter" data-level="" data-path="i-ep01.html"><a href="i-ep01.html"><i class="fa fa-check"></i>Tutorial 1: Simple regression and model usefulness</a></li>
<li class="chapter" data-level="" data-path="i04.html"><a href="i04.html"><i class="fa fa-check"></i>Lecture 4: Multiple linear regression and controls</a></li>
<li class="chapter" data-level="" data-path="i05.html"><a href="i05.html"><i class="fa fa-check"></i>Lecture 5: Dummy predictors and joint usefulness</a></li>
<li class="chapter" data-level="" data-path="i06.html"><a href="i06.html"><i class="fa fa-check"></i>Lecture 6: Interactions and polynomial terms</a></li>
<li class="chapter" data-level="" data-path="i-ep02.html"><a href="i-ep02.html"><i class="fa fa-check"></i>Tutorial 2: Multiple regression and extensions</a></li>
<li class="chapter" data-level="" data-path="intermediate-code-sheet.html"><a href="intermediate-code-sheet.html"><i class="fa fa-check"></i>QM Intermediate Code Sheet</a></li>
<li class="chapter" data-level="" data-path="intermediate-mock-exam.html"><a href="intermediate-mock-exam.html"><i class="fa fa-check"></i>Mock Exam: QM Intermediate</a></li>
<li class="part"><span><b>III QM Advanced</b></span></li>
<li class="chapter" data-level="" data-path="advanced-course.html"><a href="advanced-course.html"><i class="fa fa-check"></i>QM Advanced: Course overview</a></li>
<li class="part"><span><b>IV Supplementary resources</b></span></li>
<li class="chapter" data-level="" data-path="r-refresher.html"><a href="r-refresher.html"><i class="fa fa-check"></i>R Refresher</a></li>
<li class="chapter" data-level="" data-path="math-refresher.html"><a href="math-refresher.html"><i class="fa fa-check"></i>Mathematics Refresher</a></li>
<li class="chapter" data-level="" data-path="videos.html"><a href="videos.html"><i class="fa fa-check"></i>External Video Guide</a></li>
<li class="divider"></li>
<li class="book-footer">Quantitative Methods learning line</li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Online Textbook for the Learning Line “Quantitative Methods to Understand E&amp;BI”</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="b09" class="section level1 hasAnchor">
<h1>Lecture 9: Confidence intervals and tests against zero<a href="b09.html#b09" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<div class="outcomes">
<span class="label">By the end of Lecture 9, you can</span>
<ul>
<li>
construct a t confidence interval for a population mean;
</li>
<li>
express comparison with a benchmark as a parameter equal to zero;
</li>
<li>
state a two-sided null and alternative hypothesis;
</li>
<li>
calculate and interpret a t statistic and two-sided p-value;
</li>
<li>
connect a 95% confidence interval to a 5% two-sided test.
</li>
</ul>
</div>
<div id="before-class-11" class="section level2 hasAnchor course-phase phase-before">
<h2>Before class<a href="b09.html#before-class-11" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div class="video-prep">
<p><span class="label">Video preparation</span><br>
Watch <a href="https://www.youtube.com/watch?v=NInNhFm046w">Confidence
Intervals</a>,
<a href="https://www.youtube.com/watch?v=MzvRQFYUEFU">Confidence Intervals
When the Variance Is Unknown</a>, and
<a href="https://www.youtube.com/watch?v=ti9NFdjf3sM">Introduction to
Hypothesis Testing</a>. Focus on repeated-sampling coverage, the t reference
distribution, and the role of the null value.</p>
</div>
<p>Review <a href="math-refresher.html#math-refresher">Mathematics Refresher: intervals, standardisation, and degrees of
freedom</a> if needed.</p>
<p>Let <span class="math inline">\(X\)</span> be initial equity offered and define the <strong>equity gap</strong></p>
<p><span class="math display">\[
D=X-15.
\]</span></p>
<p>Write two-sided hypotheses for the question: “Does population mean initial
equity differ from 15 percentage points?”</p>
<details>
<summary>
Check your preparation
</summary>
<p>Let <span class="math inline">\(\delta=E[D]=\mu_X-15\)</span>. Then</p>
<p><span class="math display">\[
H_0:\delta=0
\qquad\text{versus}\qquad
H_1:\delta\ne0.
\]</span></p>
<p>This is equivalent to testing <span class="math inline">\(H_0:\mu_X=15\)</span> against
<span class="math inline">\(H_1:\mu_X\ne15\)</span>. Writing the contrast as <span class="math inline">\(\delta\)</span> makes the central
question “is the difference zero?”—the same structure later used for
regression coefficients.</p>
</details>
</div>
<div id="in-class-11" class="section level2 hasAnchor course-phase phase-in-class">
<h2>In class<a href="b09.html#in-class-11" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p class="concept-video">
<strong>Video explanations (review):</strong>
<a href="https://ocw.mit.edu/courses/res-6-012-introduction-to-probability-spring-2018/resources/confidence-intervals/">20.5 Confidence Intervals</a>,
<a href="https://ocw.mit.edu/courses/res-6-012-introduction-to-probability-spring-2018/resources/confidence-intervals-for-the-mean-when-the-variance-is-unknown/">20.7 Confidence Intervals with Unknown Variance</a>, and
<a href="https://www.youtube.com/watch?v=ti9NFdjf3sM">Introduction to Hypothesis Testing</a>.
</p>
<div id="confidence-intervals-combine-estimate-and-uncertainty" class="section level3 hasAnchor">
<h3>Confidence intervals combine estimate and uncertainty<a href="b09.html#confidence-intervals-combine-estimate-and-uncertainty" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The general form is</p>
<p><span class="math display">\[
\text{estimate}
\ \pm\
\text{critical value}\times\text{standard error}.
\]</span></p>
<p>The product is the <strong>margin of error</strong>. A confidence interval becomes:</p>
<ul>
<li>wider when the confidence level increases;</li>
<li>wider when observations are more variable;</li>
<li>narrower when the sample size increases, all else equal.</li>
</ul>
<p>For an independent normal sample with unknown population SD,</p>
<p><span class="math display">\[
\bar X\pm t_{1-\alpha/2,n-1}\frac{S}{\sqrt n}
\]</span></p>
<p>is a <span class="math inline">\(100(1-\alpha)\%\)</span> confidence interval for <span class="math inline">\(\mu\)</span>. For a large
independent sample, the interval is also an approximation when the population
is not normal.</p>
<p>The degrees of freedom are <span class="math inline">\(n-1\)</span>: one degree of freedom was used to estimate
the sample mean before estimating spread. Lower degrees of freedom produce a
larger critical value because the t distribution has heavier tails.</p>
</div>
<div id="check-conditions-before-calculating" class="section level3 hasAnchor">
<h3>Check conditions before calculating<a href="b09.html#check-conditions-before-calculating" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The formula is justified by the sampling design and distributional conditions,
not by the presence of an R command.</p>
<ul>
<li>The 100 rows were selected randomly from the 1,441-record frame.</li>
<li>Sampling without replacement creates weak dependence, but
<span class="math inline">\(100/1441&lt;0.10\)</span>, so the usual independent-sample SE is a reasonable
approximation.</li>
<li>The pitch-level equity variable is right-skewed, but <span class="math inline">\(n=100\)</span> makes the
t approximation for the sample mean much more credible than it would be for
a very small sample. We should still check for data errors or observations
that dominate the mean.</li>
</ul>
<p>These conditions support inference to the recorded-pitch frame. They do not
make televised pitches representative of all entrepreneurs.</p>
</div>
<div id="estimate-a-difference-from-a-benchmark" class="section level3 hasAnchor">
<h3>Estimate a difference from a benchmark<a href="b09.html#estimate-a-difference-from-a-benchmark" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>In the reproducible sample,</p>
<div class="sourceCode" id="cb108"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb108-1"><a href="b09.html#cb108-1" tabindex="-1"></a><span class="fu">c</span>(</span>
<span id="cb108-2"><a href="b09.html#cb108-2" tabindex="-1"></a>  <span class="at">sample_mean_equity =</span> <span class="fu">mean</span>(pitch_sample<span class="sc">$</span>equity_offered_pct),</span>
<span id="cb108-3"><a href="b09.html#cb108-3" tabindex="-1"></a>  <span class="at">sample_mean_gap =</span> gap_bar,</span>
<span id="cb108-4"><a href="b09.html#cb108-4" tabindex="-1"></a>  <span class="at">sample_sd_gap =</span> gap_sd,</span>
<span id="cb108-5"><a href="b09.html#cb108-5" tabindex="-1"></a>  <span class="at">standard_error_gap =</span> gap_se,</span>
<span id="cb108-6"><a href="b09.html#cb108-6" tabindex="-1"></a>  <span class="at">degrees_of_freedom =</span> df</span>
<span id="cb108-7"><a href="b09.html#cb108-7" tabindex="-1"></a>)</span></code></pre></div>
<pre><code>## sample_mean_equity    sample_mean_gap      sample_sd_gap standard_error_gap 
##         12.7600000         -2.2400000          7.7078866          0.7707887 
## degrees_of_freedom 
##         99.0000000</code></pre>
<p>The estimated population mean gap is <span class="math inline">\(-2.24\)</span> percentage points: the sample
mean equity offer is 2.24 percentage points below the 15-point benchmark.</p>
<div class="sourceCode" id="cb110"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb110-1"><a href="b09.html#cb110-1" tabindex="-1"></a>critical_t <span class="ot">&lt;-</span> <span class="fu">qt</span>(<span class="fl">0.975</span>, <span class="at">df =</span> df)</span>
<span id="cb110-2"><a href="b09.html#cb110-2" tabindex="-1"></a>gap_ci <span class="ot">&lt;-</span> gap_bar <span class="sc">+</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">1</span>, <span class="dv">1</span>) <span class="sc">*</span> critical_t <span class="sc">*</span> gap_se</span>
<span id="cb110-3"><a href="b09.html#cb110-3" tabindex="-1"></a>mean_ci <span class="ot">&lt;-</span> benchmark <span class="sc">+</span> gap_ci</span>
<span id="cb110-4"><a href="b09.html#cb110-4" tabindex="-1"></a></span>
<span id="cb110-5"><a href="b09.html#cb110-5" tabindex="-1"></a><span class="fu">c</span>(<span class="at">gap_lower =</span> gap_ci[<span class="dv">1</span>], <span class="at">gap_upper =</span> gap_ci[<span class="dv">2</span>])</span></code></pre></div>
<pre><code>##  gap_lower  gap_upper 
## -3.7694119 -0.7105881</code></pre>
<div class="sourceCode" id="cb112"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb112-1"><a href="b09.html#cb112-1" tabindex="-1"></a><span class="fu">c</span>(<span class="at">mean_lower =</span> mean_ci[<span class="dv">1</span>], <span class="at">mean_upper =</span> mean_ci[<span class="dv">2</span>])</span></code></pre></div>
<pre><code>## mean_lower mean_upper 
##   11.23059   14.28941</code></pre>
<p>The 95% interval for the mean gap is approximately
<span class="math inline">\((-3.77,-0.71)\)</span> percentage points. Adding 15 to both endpoints gives the
equivalent interval <span class="math inline">\((11.23,14.29)\)</span> for mean initial equity.</p>
</div>
<div id="a-hypothesis-test-starts-with-a-null-model" class="section level3 hasAnchor">
<h3>A hypothesis test starts with a null model<a href="b09.html#a-hypothesis-test-starts-with-a-null-model" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>For a two-sided test,</p>
<p><span class="math display">\[
H_0:\delta=0
\qquad\text{versus}\qquad
H_1:\delta\ne0.
\]</span></p>
<p>The null says there is no population mean difference from the benchmark. The
alternative allows a difference in either direction. Choose the two-sided
alternative from the research question before inspecting the sample estimate.</p>
<p>Standardise the estimated gap using the SE:</p>
<p><span class="math display">\[
T=
\frac{\widehat\delta-0}
{\operatorname{SE}(\widehat\delta)}
=
\frac{\bar D}{S_D/\sqrt n}.
\]</span></p>
<div class="sourceCode" id="cb114"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb114-1"><a href="b09.html#cb114-1" tabindex="-1"></a>t_value <span class="ot">&lt;-</span> gap_bar <span class="sc">/</span> gap_se</span>
<span id="cb114-2"><a href="b09.html#cb114-2" tabindex="-1"></a>p_value <span class="ot">&lt;-</span> <span class="dv">2</span> <span class="sc">*</span> <span class="fu">pt</span>(<span class="sc">-</span><span class="fu">abs</span>(t_value), <span class="at">df =</span> df)</span>
<span id="cb114-3"><a href="b09.html#cb114-3" tabindex="-1"></a></span>
<span id="cb114-4"><a href="b09.html#cb114-4" tabindex="-1"></a><span class="fu">c</span>(</span>
<span id="cb114-5"><a href="b09.html#cb114-5" tabindex="-1"></a>  <span class="at">estimate =</span> gap_bar,</span>
<span id="cb114-6"><a href="b09.html#cb114-6" tabindex="-1"></a>  <span class="at">standard_error =</span> gap_se,</span>
<span id="cb114-7"><a href="b09.html#cb114-7" tabindex="-1"></a>  <span class="at">t_statistic =</span> t_value,</span>
<span id="cb114-8"><a href="b09.html#cb114-8" tabindex="-1"></a>  <span class="at">degrees_of_freedom =</span> df,</span>
<span id="cb114-9"><a href="b09.html#cb114-9" tabindex="-1"></a>  <span class="at">two_sided_p_value =</span> p_value</span>
<span id="cb114-10"><a href="b09.html#cb114-10" tabindex="-1"></a>)</span></code></pre></div>
<pre><code>##           estimate     standard_error        t_statistic degrees_of_freedom 
##       -2.240000000        0.770788656       -2.906114385       99.000000000 
##  two_sided_p_value 
##        0.004515396</code></pre>
<p>The observed statistic is approximately <span class="math inline">\(-2.91\)</span>. Its sign records direction;
its absolute value records distance from zero in standard-error units.</p>
</div>
<div id="a-two-sided-p-value-uses-both-tails" class="section level3 hasAnchor">
<h3>A two-sided p-value uses both tails<a href="b09.html#a-two-sided-p-value-uses-both-tails" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The <strong>p-value</strong> is the probability, assuming <span class="math inline">\(H_0\)</span>, of obtaining a test
statistic at least as far from zero as the observed statistic in either
direction:</p>
<p><span class="math display">\[
p=P\!\left(|T_{99}|\ge|t_{obs}|\mid H_0\right).
\]</span></p>
<p><img src="B09-confidence-intervals_files/figure-html/b09-two-sided-p-plot-1.png" width="672" /></p>
<p>The horizontal axis gives possible t statistics if the null is true, and the
vertical axis is density. The dashed lines mark statistics as far from zero as
the observed value. The two orange tail areas beyond them sum to about 0.0046.
This is not the probability that <span class="math inline">\(H_0\)</span> is true and not the size of the mean
gap.</p>
<p>At <span class="math inline">\(\alpha=0.05\)</span>, reject <span class="math inline">\(H_0\)</span> because <span class="math inline">\(p&lt;0.05\)</span>. The random sample
provides evidence that mean initial equity in the recorded-pitch frame differs
from 15 percentage points. The negative estimate indicates that it is lower.</p>
</div>
<div id="the-confidence-interval-and-test-tell-the-same-story" class="section level3 hasAnchor">
<h3>The confidence interval and test tell the same story<a href="b09.html#the-confidence-interval-and-test-tell-the-same-story" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>For the same two-sided t procedure:</p>
<ul>
<li>reject <span class="math inline">\(H_0:\delta=0\)</span> at level <span class="math inline">\(\alpha\)</span> exactly when the
<span class="math inline">\(100(1-\alpha)\%\)</span> confidence interval excludes zero;</li>
<li>do not reject when the interval includes zero.</li>
</ul>
<p>Here the gap interval <span class="math inline">\((-3.77,-0.71)\)</span> excludes zero, matching the test
decision. The interval adds information the p-value does not: it displays the
direction, plausible magnitude, and precision of the difference.</p>
</div>
<div id="interpret-95-confidence-correctly" class="section level3 hasAnchor">
<h3>Interpret 95% confidence correctly<a href="b09.html#interpret-95-confidence-correctly" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The parameter is fixed; interval endpoints vary from sample to sample. If the
same valid procedure were repeated many times, about 95% of the resulting
intervals would contain the parameter.</p>
<p>Do not say that this realised interval has a 95% probability of containing the
fixed parameter. Also remember that a narrow interval does not repair
selection bias, dependence, measurement error, or a wrong model.</p>
</div>
</div>
<div id="after-class-11" class="section level2 hasAnchor course-phase phase-after">
<h2>After class<a href="b09.html#after-class-11" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="retrieval-7" class="section level3 hasAnchor">
<h3>Retrieval<a href="b09.html#retrieval-7" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<ol style="list-style-type: decimal">
<li>What are the three pieces of a confidence interval?</li>
<li>Why does a one-sample t procedure use <span class="math inline">\(n-1\)</span> degrees of freedom?</li>
<li>What do <span class="math inline">\(H_0:\delta=0\)</span> and <span class="math inline">\(H_1:\delta\ne0\)</span> say?</li>
<li>Why does a two-sided p-value use two tails?</li>
<li>What is the exact decision link between a 95% t interval and a 5%
two-sided t-test?</li>
<li>Why should an estimate and interval accompany a p-value?</li>
</ol>
<details>
<summary>
Check your answers
</summary>
<ol style="list-style-type: decimal">
<li>Estimate, critical value, and standard error.</li>
<li>Estimating the sample mean imposes one constraint before spread is
estimated, leaving <span class="math inline">\(n-1\)</span> freely varying deviations.</li>
<li>The null states that the population contrast is zero; the alternative
allows a non-zero contrast in either direction.</li>
<li>Values equally far below and above zero are both evidence against a
two-sided null.</li>
<li>The test rejects exactly when the interval excludes zero, provided both use
the same model and SE.</li>
<li>The estimate and interval show direction, magnitude, and precision; a
p-value alone does not.</li>
</ol>
</details>
</div>
<div id="practice-7" class="section level3 hasAnchor">
<h3>Practice<a href="b09.html#practice-7" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<ol style="list-style-type: decimal">
<li>A sample has <span class="math inline">\(n=64\)</span>, <span class="math inline">\(\bar x=80\)</span>, and <span class="math inline">\(s=16\)</span>. Define
<span class="math inline">\(\delta=\mu-75\)</span>. Construct a 95% interval for <span class="math inline">\(\delta\)</span>.</li>
<li>Test <span class="math inline">\(H_0:\delta=0\)</span> against <span class="math inline">\(H_1:\delta\ne0\)</span> at 5%. Report the
statistic, degrees of freedom, approximate p-value, decision, and
contextual conclusion.</li>
<li>A coefficient-like estimate is 0.42 percentage points per €100,000, with
SE 0.18 and <span class="math inline">\(df=120\)</span>. Test a two-sided zero null and construct a 95%
interval.</li>
<li>Rewrite this claim correctly: “There is a 95% chance that the population
mean is in my interval.”</li>
<li>Explain why a statistically significant mean gap need not be practically
important or causal.</li>
</ol>
<details>
<summary>
Check your answers
</summary>
<ol style="list-style-type: decimal">
<li>The estimated gap is <span class="math inline">\(80-75=5\)</span>, its SE is <span class="math inline">\(16/\sqrt{64}=2\)</span>, and
<span class="math inline">\(t_{0.975,63}\approx2.00\)</span>. The interval is approximately
<span class="math inline">\(5\pm2.00(2)=(1,9)\)</span>.</li>
<li><span class="math inline">\(t=5/2=2.50\)</span>, <span class="math inline">\(df=63\)</span>, and the two-sided p-value is about 0.015.
Reject <span class="math inline">\(H_0\)</span>: the data provide evidence that the population mean differs
from 75; the positive estimate places it above 75.</li>
<li><span class="math inline">\(t=0.42/0.18\approx2.33\)</span>, with a two-sided p-value about 0.021.
The 95% interval is approximately
<span class="math inline">\(0.42\pm1.98(0.18)=(0.064,0.776)\)</span> percentage points per €100,000.</li>
<li>“The interval was produced by a procedure that captures the fixed
population mean in about 95% of repeated valid samples.”</li>
<li>Statistical significance concerns precision relative to zero. Practical
importance depends on the magnitude and decision context, while causality
requires an appropriate design and assumptions.</li>
</ol>
</details>
<p>Continue to <a href="b10.html#b10">Lecture 10: Hypothesis testing, errors, and power</a>.</p>
<p>Formula sheet: <a href="formula-sheet.html#formula-l9">Lecture 9 formulas</a>.</p>
<p>For a more formal explanation, consult
<a href="https://tilburguniversity.on.worldcat.org/oclc/317545871">Nieuwenhuis, <em>Statistical Methods for Business and Economics</em></a>,
Chapters 15 and 16.</p>
</div>
</div>

</div>
            </section>

          </div>
        </div>
      </div>
<a href="b-ep03.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="b10.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
  "sharing": null,
  "fontsettings": {
    "theme": "white",
    "family": "sans",
    "size": 2
  },
  "edit": null,
  "history": {
    "link": null,
    "text": null
  },
  "view": {
    "link": null,
    "text": null
  },
  "download": null,
  "search": {
    "engine": "fuse",
    "options": null
  },
  "toc": {
    "collapse": "section",
    "scroll_highlight": true
  },
  "toolbar": {
    "position": "fixed"
  }
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
