<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Lecture 10: Hypothesis testing, errors, and power | Online Textbook for the Learning Line “Quantitative Methods to Understand E&amp;BI”</title>
  <meta name="description" content="An online textbook for the learning line Quantitative Methods within Entrepreneurship and Business Innovation Bachelor Program at Tilburg University." />
  <meta name="generator" content="bookdown 0.47 and GitBook 2.6.7" />

  <meta property="og:title" content="Lecture 10: Hypothesis testing, errors, and power | Online Textbook for the Learning Line “Quantitative Methods to Understand E&amp;BI”" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="An online textbook for the learning line Quantitative Methods within Entrepreneurship and Business Innovation Bachelor Program at Tilburg University." />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Lecture 10: Hypothesis testing, errors, and power | Online Textbook for the Learning Line “Quantitative Methods to Understand E&amp;BI”" />
  
  <meta name="twitter:description" content="An online textbook for the learning line Quantitative Methods within Entrepreneurship and Business Innovation Bachelor Program at Tilburg University." />
  




  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="b09.html"/>
<link rel="next" href="b-ep04.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

<link rel="stylesheet" href="styles.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="book-title"><a href="./">QM to Understand E&amp;BI</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Welcome</a></li>
<li class="part"><span><b>I QM Basic</b></span></li>
<li class="chapter" data-level="" data-path="basic-course.html"><a href="basic-course.html"><i class="fa fa-check"></i>QM Basic: Course overview</a></li>
<li class="chapter" data-level="" data-path="b01.html"><a href="b01.html"><i class="fa fa-check"></i>Lecture 1: Introduction to Data Analysis</a></li>
<li class="chapter" data-level="" data-path="b02.html"><a href="b02.html"><i class="fa fa-check"></i>Lecture 2: Probability foundations and random variables</a></li>
<li class="chapter" data-level="" data-path="b03.html"><a href="b03.html"><i class="fa fa-check"></i>Lecture 3: Discrete distributions and expectation</a></li>
<li class="chapter" data-level="" data-path="b-ep01.html"><a href="b-ep01.html"><i class="fa fa-check"></i>Tutorial 1: Evidence and probability foundations</a></li>
<li class="chapter" data-level="" data-path="b04.html"><a href="b04.html"><i class="fa fa-check"></i>Lecture 4: Variance, conditioning, and belief updating</a></li>
<li class="chapter" data-level="" data-path="b05.html"><a href="b05.html"><i class="fa fa-check"></i>Lecture 5: Joint random variables, covariance, and correlation</a></li>
<li class="chapter" data-level="" data-path="b-ep02.html"><a href="b-ep02.html"><i class="fa fa-check"></i>Tutorial 2: Conditioning and relationships</a></li>
<li class="chapter" data-level="" data-path="b06.html"><a href="b06.html"><i class="fa fa-check"></i>Lecture 6: Continuous distributions and the normal model</a></li>
<li class="chapter" data-level="" data-path="b07.html"><a href="b07.html"><i class="fa fa-check"></i>Lecture 7: Samples, parameters, and estimators</a></li>
<li class="chapter" data-level="" data-path="b08.html"><a href="b08.html"><i class="fa fa-check"></i>Lecture 8: Sampling distributions and the central limit theorem</a></li>
<li class="chapter" data-level="" data-path="b-ep03.html"><a href="b-ep03.html"><i class="fa fa-check"></i>Tutorial 3: Sampling and standard errors</a></li>
<li class="chapter" data-level="" data-path="b09.html"><a href="b09.html"><i class="fa fa-check"></i>Lecture 9: Confidence intervals and tests against zero</a></li>
<li class="chapter" data-level="" data-path="b10.html"><a href="b10.html"><i class="fa fa-check"></i>Lecture 10: Hypothesis testing, errors, and power</a></li>
<li class="chapter" data-level="" data-path="b-ep04.html"><a href="b-ep04.html"><i class="fa fa-check"></i>Tutorial 4: Inference and tests against zero</a></li>
<li class="chapter" data-level="" data-path="formula-sheet.html"><a href="formula-sheet.html"><i class="fa fa-check"></i>QM Basic Formula Sheet</a></li>
<li class="chapter" data-level="" data-path="basic-mock-exam.html"><a href="basic-mock-exam.html"><i class="fa fa-check"></i>Mock Exam: QM Basic</a></li>
<li class="part"><span><b>II QM Intermediate</b></span></li>
<li class="chapter" data-level="" data-path="intermediate-course.html"><a href="intermediate-course.html"><i class="fa fa-check"></i>QM Intermediate: Course overview</a></li>
<li class="chapter" data-level="" data-path="i01.html"><a href="i01.html"><i class="fa fa-check"></i>Lecture 1: Simple linear regression</a></li>
<li class="chapter" data-level="" data-path="i02.html"><a href="i02.html"><i class="fa fa-check"></i>Lecture 2: Regression assumptions and coefficient inference</a></li>
<li class="chapter" data-level="" data-path="i03.html"><a href="i03.html"><i class="fa fa-check"></i>Lecture 3: Model fit and overall usefulness</a></li>
<li class="chapter" data-level="" data-path="i-ep01.html"><a href="i-ep01.html"><i class="fa fa-check"></i>Tutorial 1: Simple regression and model usefulness</a></li>
<li class="chapter" data-level="" data-path="i04.html"><a href="i04.html"><i class="fa fa-check"></i>Lecture 4: Multiple linear regression and controls</a></li>
<li class="chapter" data-level="" data-path="i05.html"><a href="i05.html"><i class="fa fa-check"></i>Lecture 5: Dummy predictors and joint usefulness</a></li>
<li class="chapter" data-level="" data-path="i06.html"><a href="i06.html"><i class="fa fa-check"></i>Lecture 6: Interactions and polynomial terms</a></li>
<li class="chapter" data-level="" data-path="i-ep02.html"><a href="i-ep02.html"><i class="fa fa-check"></i>Tutorial 2: Multiple regression and extensions</a></li>
<li class="chapter" data-level="" data-path="intermediate-code-sheet.html"><a href="intermediate-code-sheet.html"><i class="fa fa-check"></i>QM Intermediate Code Sheet</a></li>
<li class="chapter" data-level="" data-path="intermediate-mock-exam.html"><a href="intermediate-mock-exam.html"><i class="fa fa-check"></i>Mock Exam: QM Intermediate</a></li>
<li class="part"><span><b>III QM Advanced</b></span></li>
<li class="chapter" data-level="" data-path="advanced-course.html"><a href="advanced-course.html"><i class="fa fa-check"></i>QM Advanced: Course overview</a></li>
<li class="part"><span><b>IV Supplementary resources</b></span></li>
<li class="chapter" data-level="" data-path="r-refresher.html"><a href="r-refresher.html"><i class="fa fa-check"></i>R Refresher</a></li>
<li class="chapter" data-level="" data-path="math-refresher.html"><a href="math-refresher.html"><i class="fa fa-check"></i>Mathematics Refresher</a></li>
<li class="chapter" data-level="" data-path="videos.html"><a href="videos.html"><i class="fa fa-check"></i>External Video Guide</a></li>
<li class="divider"></li>
<li class="book-footer">Quantitative Methods learning line</li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Online Textbook for the Learning Line “Quantitative Methods to Understand E&amp;BI”</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="b10" class="section level1 hasAnchor">
<h1>Lecture 10: Hypothesis testing, errors, and power<a href="b10.html#b10" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<div class="outcomes">
<span class="label">By the end of Lecture 10, you can</span>
<ul>
<li>
complete and communicate a two-sided test against zero;
</li>
<li>
distinguish a p-value, significance level, and test decision;
</li>
<li>
describe Type I error, Type II error, and power in context;
</li>
<li>
separate statistical significance from magnitude, practical importance, and causality;
</li>
<li>
interpret the zero-null test printed for a regression coefficient.
</li>
</ul>
</div>
<div id="before-class-12" class="section level2 hasAnchor course-phase phase-before">
<h2>Before class<a href="b10.html#before-class-12" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div class="video-prep">
<p><span class="label">Video preparation</span><br>
Review <a href="https://www.youtube.com/watch?v=ti9NFdjf3sM">Introduction to
Hypothesis Testing</a> and watch
<a href="https://www.youtube.com/watch?v=JNOWWJeZBTc">Examples Identifying
Type I and Type II Errors</a>. Focus on two-sided tests, decision errors, and
why “do not reject” is not “accept.”</p>
</div>
<p>Review <a href="math-refresher.html#math-refresher">Mathematics Refresher: zero contrasts, inequalities, and
standardisation</a> if needed.</p>
<p>Suppose R reports the following coefficient row:</p>
<table>
<thead>
<tr class="header">
<th align="right">Estimate</th>
<th align="right">SE</th>
<th align="right">t</th>
<th align="right">p-value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">-0.290</td>
<td align="right">0.058</td>
<td align="right">-5.00</td>
<td align="right">&lt; 0.001</td>
</tr>
</tbody>
</table>
<p>State the hypotheses and give a careful one-sentence statistical conclusion.</p>
<details>
<summary>
Check your preparation
</summary>
<p>The default two-sided coefficient test is
<span class="math inline">\(H_0:\beta=0\)</span> against <span class="math inline">\(H_1:\beta\ne0\)</span>. Because the p-value is below
0.05, reject <span class="math inline">\(H_0\)</span>: the data provide evidence that the population-model
coefficient differs from zero. A full interpretation still needs the outcome,
predictor, units, held-fixed variables, population, and causal limit.</p>
</details>
</div>
<div id="in-class-12" class="section level2 hasAnchor course-phase phase-in-class">
<h2>In class<a href="b10.html#in-class-12" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p class="concept-video">
<strong>Video explanations (review):</strong>
<a href="https://www.youtube.com/watch?v=ti9NFdjf3sM">Introduction to Hypothesis Testing</a> and
<a href="https://www.youtube.com/watch?v=JNOWWJeZBTc">Type I and Type II Errors</a>.
</p>
<div id="why-zero-is-the-central-benchmark" class="section level3 hasAnchor">
<h3>Why zero is the central benchmark<a href="b10.html#why-zero-is-the-central-benchmark" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Many empirical questions ask whether a population contrast is absent:</p>
<ul>
<li>difference from a target: <span class="math inline">\(\delta=\mu-15\)</span>;</li>
<li>difference in probabilities: <span class="math inline">\(\delta_p=p-0.50\)</span>;</li>
<li>difference between two group means: <span class="math inline">\(\mu_1-\mu_0\)</span>;</li>
<li>regression slope: <span class="math inline">\(\beta_j\)</span>.</li>
</ul>
<p>In every case, “no difference” or “no linear association” becomes</p>
<p><span class="math display">\[
H_0:\theta=0
\qquad\text{versus}\qquad
H_1:\theta\ne0.
\]</span></p>
<p>Testing a non-zero benchmark can therefore be rewritten as a test of a
zero-valued contrast. This common structure is the bridge from Basic inference
to regression inference.</p>
</div>
<div id="a-complete-two-sided-testing-workflow" class="section level3 hasAnchor">
<h3>A complete two-sided testing workflow<a href="b10.html#a-complete-two-sided-testing-workflow" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Use the same sequence every time:</p>
<ol style="list-style-type: decimal">
<li>Define the population parameter and its units.</li>
<li>State <span class="math inline">\(H_0\)</span> and the two-sided <span class="math inline">\(H_1\)</span> before inspecting the result.</li>
<li>Check the sampling and model conditions.</li>
<li>Calculate the estimate and its SE under the null model.</li>
<li>Standardise: <span class="math inline">\((\text{estimate}-0)/\text{SE}\)</span>.</li>
<li>Calculate the two-sided p-value and compare it with the pre-specified
significance level <span class="math inline">\(\alpha\)</span>.</li>
<li>Report the estimate, uncertainty, decision, contextual meaning, and limits.</li>
</ol>
<p>The significance level is a long-run decision threshold, commonly 0.05. The
p-value is calculated from the observed data under <span class="math inline">\(H_0\)</span>. They are not the
same object.</p>
</div>
<div id="example-a-deal-proportion-contrast" class="section level3 hasAnchor">
<h3>Example: a deal-proportion contrast<a href="b10.html#example-a-deal-proportion-contrast" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Define</p>
<p><span class="math display">\[
\delta_p=p-0.50.
\]</span></p>
<p>The question is whether the finite-frame deal proportion differs from 50%:</p>
<p><span class="math display">\[
H_0:\delta_p=0
\qquad\text{versus}\qquad
H_1:\delta_p\ne0.
\]</span></p>
<p>Under the null, <span class="math inline">\(p_0=0.50\)</span>, so</p>
<p><span class="math display">\[
Z=
\frac{\widehat\delta_p-0}
{\sqrt{p_0(1-p_0)/n}}
=
\frac{\hat p-0.50}
{\sqrt{0.50(0.50)/n}}.
\]</span></p>
<div class="sourceCode" id="cb120"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb120-1"><a href="b10.html#cb120-1" tabindex="-1"></a>null_se <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(p0 <span class="sc">*</span> (<span class="dv">1</span> <span class="sc">-</span> p0) <span class="sc">/</span> n)</span>
<span id="cb120-2"><a href="b10.html#cb120-2" tabindex="-1"></a>z_value <span class="ot">&lt;-</span> deal_gap <span class="sc">/</span> null_se</span>
<span id="cb120-3"><a href="b10.html#cb120-3" tabindex="-1"></a>two_sided_p <span class="ot">&lt;-</span> <span class="dv">2</span> <span class="sc">*</span> <span class="fu">pnorm</span>(<span class="sc">-</span><span class="fu">abs</span>(z_value))</span>
<span id="cb120-4"><a href="b10.html#cb120-4" tabindex="-1"></a></span>
<span id="cb120-5"><a href="b10.html#cb120-5" tabindex="-1"></a><span class="fu">c</span>(</span>
<span id="cb120-6"><a href="b10.html#cb120-6" tabindex="-1"></a>  <span class="at">sample_proportion =</span> phat,</span>
<span id="cb120-7"><a href="b10.html#cb120-7" tabindex="-1"></a>  <span class="at">estimated_gap =</span> deal_gap,</span>
<span id="cb120-8"><a href="b10.html#cb120-8" tabindex="-1"></a>  <span class="at">null_standard_error =</span> null_se,</span>
<span id="cb120-9"><a href="b10.html#cb120-9" tabindex="-1"></a>  <span class="at">z_statistic =</span> z_value,</span>
<span id="cb120-10"><a href="b10.html#cb120-10" tabindex="-1"></a>  <span class="at">two_sided_p_value =</span> two_sided_p</span>
<span id="cb120-11"><a href="b10.html#cb120-11" tabindex="-1"></a>)</span></code></pre></div>
<pre><code>##   sample_proportion       estimated_gap null_standard_error         z_statistic 
##         0.640000000         0.140000000         0.050000000         2.800000000 
##   two_sided_p_value 
##         0.005110261</code></pre>
<p>The estimate is <span class="math inline">\(\widehat\delta_p=0.14\)</span>, or 14 percentage points. The
test statistic is <span class="math inline">\(z=2.80\)</span> and the two-sided p-value is about 0.0051.
Reject the zero-gap null at 5%: the random sample provides evidence that the
recorded-pitch-frame deal proportion differs from 50%. Its positive estimate
places it above 50%.</p>
<p>The success-failure condition is checked under the null for this test:
<span class="math inline">\(np_0=50\)</span> and <span class="math inline">\(n(1-p_0)=50\)</span>, both at least 10.</p>
</div>
<div id="interval-and-test-report-both" class="section level3 hasAnchor">
<h3>Interval and test: report both<a href="b10.html#interval-and-test-report-both" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>A large-sample 95% interval for the proportion uses the estimated SE:</p>
<p><span class="math display">\[
\hat p\pm1.96
\sqrt{\frac{\hat p(1-\hat p)}{n}}.
\]</span></p>
<div class="sourceCode" id="cb122"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb122-1"><a href="b10.html#cb122-1" tabindex="-1"></a>estimated_se <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(phat <span class="sc">*</span> (<span class="dv">1</span> <span class="sc">-</span> phat) <span class="sc">/</span> n)</span>
<span id="cb122-2"><a href="b10.html#cb122-2" tabindex="-1"></a>proportion_ci <span class="ot">&lt;-</span> phat <span class="sc">+</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">1</span>, <span class="dv">1</span>) <span class="sc">*</span> <span class="fl">1.96</span> <span class="sc">*</span> estimated_se</span>
<span id="cb122-3"><a href="b10.html#cb122-3" tabindex="-1"></a>gap_ci <span class="ot">&lt;-</span> proportion_ci <span class="sc">-</span> p0</span>
<span id="cb122-4"><a href="b10.html#cb122-4" tabindex="-1"></a></span>
<span id="cb122-5"><a href="b10.html#cb122-5" tabindex="-1"></a><span class="fu">c</span>(<span class="at">proportion_lower =</span> proportion_ci[<span class="dv">1</span>],</span>
<span id="cb122-6"><a href="b10.html#cb122-6" tabindex="-1"></a>  <span class="at">proportion_upper =</span> proportion_ci[<span class="dv">2</span>])</span></code></pre></div>
<pre><code>## proportion_lower proportion_upper 
##          0.54592          0.73408</code></pre>
<div class="sourceCode" id="cb124"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb124-1"><a href="b10.html#cb124-1" tabindex="-1"></a><span class="fu">c</span>(<span class="at">gap_lower =</span> gap_ci[<span class="dv">1</span>], <span class="at">gap_upper =</span> gap_ci[<span class="dv">2</span>])</span></code></pre></div>
<pre><code>## gap_lower gap_upper 
##   0.04592   0.23408</code></pre>
<p>The proportion interval is approximately <span class="math inline">\((0.546,0.734)\)</span>; the equivalent
gap interval is <span class="math inline">\((0.046,0.234)\)</span>, which excludes zero. It agrees with the
test decision here.</p>
<p>The manual interval estimates its SE with <span class="math inline">\(\hat p\)</span>, while the test uses
<span class="math inline">\(p_0\)</span>. Because these are not exactly the same procedure, confidence-interval
and test decisions need not match perfectly near a boundary. Exact equivalence
requires a confidence interval obtained by inverting the same test.</p>
</div>
<div id="what-a-p-value-does-and-does-not-mean" class="section level3 hasAnchor">
<h3>What a p-value does and does not mean<a href="b10.html#what-a-p-value-does-and-does-not-mean" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The two-sided p-value is</p>
<p><span class="math display">\[
P\!\left(|\text{test statistic}|
\ge|\text{observed statistic}|\mid H_0\right).
\]</span></p>
<p>It is not:</p>
<ul>
<li><span class="math inline">\(P(H_0\mid\text{data})\)</span>;</li>
<li>the probability that the result occurred “by chance”;</li>
<li>the size or importance of the estimated contrast;</li>
<li>evidence that the relationship is causal.</li>
</ul>
<p>If <span class="math inline">\(p\le\alpha\)</span>, reject <span class="math inline">\(H_0\)</span>. If <span class="math inline">\(p&gt;\alpha\)</span>, <strong>do not reject</strong>
<span class="math inline">\(H_0\)</span>. Do not say “accept <span class="math inline">\(H_0\)</span>”: an imprecise study may simply lack
power to detect a meaningful non-zero parameter.</p>
</div>
<div id="type-i-error-type-ii-error-and-power" class="section level3 hasAnchor">
<h3>Type I error, Type II error, and power<a href="b10.html#type-i-error-type-ii-error-and-power" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<table>
<thead>
<tr class="header">
<th>Reality</th>
<th>Reject <span class="math inline">\(H_0\)</span></th>
<th>Do not reject <span class="math inline">\(H_0\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(H_0\)</span> true</td>
<td>Type I error</td>
<td>Correct decision</td>
</tr>
<tr class="even">
<td><span class="math inline">\(H_1\)</span> true</td>
<td>Correct decision</td>
<td>Type II error</td>
</tr>
</tbody>
</table>
<p>The significance level controls</p>
<p><span class="math display">\[
P(\text{reject }H_0\mid H_0\text{ true})=\alpha.
\]</span></p>
<p>Power is</p>
<p><span class="math display">\[
P(\text{reject }H_0\mid H_1\text{ true}).
\]</span></p>
<p><img src="B10-hypothesis-testing_files/figure-html/b10-errors-power-plot-1.png" width="672" /></p>
<p>In both panels, the horizontal axis is the possible z statistic and the
vertical axis is density; probability is area. The dashed vertical lines mark
the same two-sided critical values. In the left panel, the two orange rejection
regions have total probability <span class="math inline">\(\alpha=0.05\)</span> when the null is true. In the
right panel, the distribution has shifted because a particular positive
alternative is true; the green area is the probability of correctly rejecting
under that alternative, which is the power.</p>
<p>Power increases with:</p>
<ul>
<li>a larger true distance from zero;</li>
<li>a larger sample;</li>
<li>lower unexplained variation;</li>
<li>a larger <span class="math inline">\(\alpha\)</span>, although that also raises Type I error.</li>
</ul>
</div>
<div id="statistical-significance-is-not-substantive-importance" class="section level3 hasAnchor">
<h3>Statistical significance is not substantive importance<a href="b10.html#statistical-significance-is-not-substantive-importance" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>A tiny effect can be statistically significant in a large sample. A meaningful
effect can be non-significant in a small or noisy sample. Always report:</p>
<ul>
<li>the estimate in substantive units;</li>
<li>a confidence interval;</li>
<li>the p-value or decision;</li>
<li>whether the magnitude matters for the business question;</li>
<li>the sampling, measurement, and causal limits.</li>
</ul>
</div>
<div id="preview-the-test-attached-to-a-regression-slope" class="section level3 hasAnchor">
<h3>Preview: the test attached to a regression slope<a href="b10.html#preview-the-test-attached-to-a-regression-slope" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>R applies the same zero-null logic to every regression coefficient. Consider
the simple model of initial equity offered on season:</p>
<div class="sourceCode" id="cb126"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb126-1"><a href="b10.html#cb126-1" tabindex="-1"></a>preview_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(equity_offered_pct <span class="sc">~</span> season, <span class="at">data =</span> sharks)</span>
<span id="cb126-2"><a href="b10.html#cb126-2" tabindex="-1"></a><span class="fu">summary</span>(preview_model)<span class="sc">$</span>coefficients</span></code></pre></div>
<pre><code>##               Estimate Std. Error   t value      Pr(&gt;|t|)
## (Intercept) 20.4565874 0.46442667  44.04697 4.922706e-269
## season      -0.8241241 0.04752298 -17.34159  2.514546e-61</code></pre>
<div class="sourceCode" id="cb128"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb128-1"><a href="b10.html#cb128-1" tabindex="-1"></a><span class="fu">confint</span>(preview_model)</span></code></pre></div>
<pre><code>##                  2.5 %     97.5 %
## (Intercept) 19.5455616 21.3676132
## season      -0.9173458 -0.7309023</code></pre>
<p>The season slope is approximately <span class="math inline">\(-0.824\)</span> percentage points per season.
Its t statistic divides that estimate by its SE. The printed two-sided test is</p>
<p><span class="math display">\[
H_0:\beta_1=0
\qquad\text{versus}\qquad
H_1:\beta_1\ne0.
\]</span></p>
<p>The interval excludes zero and the p-value is below 0.001, so the data provide
evidence of a non-zero population-model slope. This is an observational time
association, not a causal effect of moving a pitch to a later season.</p>
<p>Intermediate begins from this familiar estimate–SE–t–p-value structure and
adds careful coefficient interpretation, multiple predictors, and model
diagnostics.</p>
</div>
</div>
<div id="after-class-12" class="section level2 hasAnchor course-phase phase-after">
<h2>After class<a href="b10.html#after-class-12" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="retrieval-8" class="section level3 hasAnchor">
<h3>Retrieval<a href="b10.html#retrieval-8" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<ol style="list-style-type: decimal">
<li>Why can most comparison hypotheses be written as a parameter equal to zero?</li>
<li>What is the difference between <span class="math inline">\(\alpha\)</span> and a p-value?</li>
<li>What is a Type I error?</li>
<li>What is a Type II error?</li>
<li>Name three factors that increase power.</li>
<li>Why is “do not reject” different from “accept”?</li>
<li>What does <span class="math inline">\(H_0:\beta_j=0\)</span> mean in a regression model?</li>
</ol>
<details>
<summary>
Check your answers
</summary>
<ol style="list-style-type: decimal">
<li>Subtracting the benchmark or reference value creates a contrast; no
difference corresponds to a zero contrast.</li>
<li><span class="math inline">\(\alpha\)</span> is a pre-specified long-run decision threshold; the p-value is
calculated from the observed statistic under the null.</li>
<li>Rejecting <span class="math inline">\(H_0\)</span> when it is true.</li>
<li>Not rejecting <span class="math inline">\(H_0\)</span> when a specified alternative is true.</li>
<li>Any three of larger sample size, larger true effect, lower noise, or larger
<span class="math inline">\(\alpha\)</span>.</li>
<li>A non-significant result may be too imprecise to distinguish a meaningful
parameter from zero.</li>
<li>Holding the other included predictors fixed, the population-model
coefficient for predictor <span class="math inline">\(j\)</span> is zero.</li>
</ol>
</details>
</div>
<div id="practice-8" class="section level3 hasAnchor">
<h3>Practice<a href="b10.html#practice-8" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<ol style="list-style-type: decimal">
<li>A sample of <span class="math inline">\(n=49\)</span> difference scores has <span class="math inline">\(\bar d=3\)</span> and <span class="math inline">\(s_d=14\)</span>.
Test <span class="math inline">\(H_0:\delta=0\)</span> against <span class="math inline">\(H_1:\delta\ne0\)</span> at 5%.</li>
<li>In 200 trials there are 120 successes. Define
<span class="math inline">\(\delta_p=p-0.50\)</span> and perform a two-sided test against zero.</li>
<li>A multiple-regression coefficient is <span class="math inline">\(-0.290\)</span> percentage points per
€100,000, with SE 0.058 and <span class="math inline">\(df=1437\)</span>. Calculate its t statistic,
approximate 95% interval, and interpretation.</li>
<li>Describe Type I and Type II errors for Question 2.</li>
<li>A coefficient estimate is economically negligible but has <span class="math inline">\(p&lt;0.001\)</span>.
Explain how both facts can be true.</li>
<li>State two reasons the regression preview cannot support a causal conclusion.</li>
</ol>
<details>
<summary>
Check your answers
</summary>
<ol style="list-style-type: decimal">
<li>The SE is <span class="math inline">\(14/\sqrt{49}=2\)</span>, so <span class="math inline">\(t=3/2=1.50\)</span>, with <span class="math inline">\(df=48\)</span>.
The two-sided p-value is about 0.140. Do not reject the zero mean-difference
null at 5%.</li>
<li><span class="math inline">\(\hat p=0.60\)</span>, <span class="math inline">\(\widehat\delta_p=0.10\)</span>, and the null SE is
<span class="math inline">\(\sqrt{0.50(0.50)/200}\approx0.0354\)</span>. Thus <span class="math inline">\(z\approx2.83\)</span> and the
two-sided p-value is about 0.0047. Reject the zero-gap null.</li>
<li><span class="math inline">\(t=-0.290/0.058=-5.00\)</span>. With a large <span class="math inline">\(df\)</span>, the 95% interval is
approximately <span class="math inline">\(-0.290\pm1.96(0.058)=(-0.404,-0.176)\)</span> percentage points
per €100,000. Holding the other included predictors fixed, an additional
€100,000 is associated with between about 0.176 and 0.404 percentage points
less fitted outcome.</li>
<li>Type I: conclude that the population success proportion differs from 0.50
when it equals 0.50. Type II: fail to detect a genuine specified difference
from 0.50.</li>
<li>A large sample or low SE can estimate a very small coefficient precisely.
Statistical precision does not determine practical importance.</li>
<li>The predictor was not randomly assigned, and omitted factors, selection,
reverse direction, or measurement error can remain.</li>
</ol>
</details>
<p>Continue to <a href="b-ep04.html#b-ep04">Tutorial 4: Inference and tests against zero</a>.</p>
<p>Formula sheet: <a href="formula-sheet.html#formula-l10">Lecture 10 formulas</a>.</p>
<p>For a more formal explanation, consult
<a href="https://tilburguniversity.on.worldcat.org/oclc/317545871">Nieuwenhuis, <em>Statistical Methods for Business and Economics</em></a>,
Chapters 15 and 16.</p>
</div>
</div>

</div>
            </section>

          </div>
        </div>
      </div>
<a href="b09.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="b-ep04.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
  "sharing": null,
  "fontsettings": {
    "theme": "white",
    "family": "sans",
    "size": 2
  },
  "edit": null,
  "history": {
    "link": null,
    "text": null
  },
  "view": {
    "link": null,
    "text": null
  },
  "download": null,
  "search": {
    "engine": "fuse",
    "options": null
  },
  "toc": {
    "collapse": "section",
    "scroll_highlight": true
  },
  "toolbar": {
    "position": "fixed"
  }
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
