<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Tutorial 2: Multiple regression and extensions | Online Textbook for the Learning Line “Quantitative Methods to Understand E&amp;BI”</title>
  <meta name="description" content="An online textbook for the learning line Quantitative Methods within Entrepreneurship and Business Innovation Bachelor Program at Tilburg University." />
  <meta name="generator" content="bookdown 0.47 and GitBook 2.6.7" />

  <meta property="og:title" content="Tutorial 2: Multiple regression and extensions | Online Textbook for the Learning Line “Quantitative Methods to Understand E&amp;BI”" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="An online textbook for the learning line Quantitative Methods within Entrepreneurship and Business Innovation Bachelor Program at Tilburg University." />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Tutorial 2: Multiple regression and extensions | Online Textbook for the Learning Line “Quantitative Methods to Understand E&amp;BI”" />
  
  <meta name="twitter:description" content="An online textbook for the learning line Quantitative Methods within Entrepreneurship and Business Innovation Bachelor Program at Tilburg University." />
  




  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="i06.html"/>
<link rel="next" href="intermediate-code-sheet.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

<link rel="stylesheet" href="styles.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="book-title"><a href="./">QM to Understand E&amp;BI</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Welcome</a></li>
<li class="part"><span><b>I QM Basic</b></span></li>
<li class="chapter" data-level="" data-path="basic-course.html"><a href="basic-course.html"><i class="fa fa-check"></i>QM Basic: Course overview</a></li>
<li class="chapter" data-level="" data-path="b01.html"><a href="b01.html"><i class="fa fa-check"></i>Lecture 1: Introduction to Data Analysis</a></li>
<li class="chapter" data-level="" data-path="b02.html"><a href="b02.html"><i class="fa fa-check"></i>Lecture 2: Probability foundations and random variables</a></li>
<li class="chapter" data-level="" data-path="b03.html"><a href="b03.html"><i class="fa fa-check"></i>Lecture 3: Discrete distributions and expectation</a></li>
<li class="chapter" data-level="" data-path="b-ep01.html"><a href="b-ep01.html"><i class="fa fa-check"></i>Tutorial 1: Evidence and probability foundations</a></li>
<li class="chapter" data-level="" data-path="b04.html"><a href="b04.html"><i class="fa fa-check"></i>Lecture 4: Variance, conditioning, and belief updating</a></li>
<li class="chapter" data-level="" data-path="b05.html"><a href="b05.html"><i class="fa fa-check"></i>Lecture 5: Joint random variables, covariance, and correlation</a></li>
<li class="chapter" data-level="" data-path="b-ep02.html"><a href="b-ep02.html"><i class="fa fa-check"></i>Tutorial 2: Conditioning and relationships</a></li>
<li class="chapter" data-level="" data-path="b06.html"><a href="b06.html"><i class="fa fa-check"></i>Lecture 6: Continuous distributions and the normal model</a></li>
<li class="chapter" data-level="" data-path="b07.html"><a href="b07.html"><i class="fa fa-check"></i>Lecture 7: Samples, parameters, and estimators</a></li>
<li class="chapter" data-level="" data-path="b08.html"><a href="b08.html"><i class="fa fa-check"></i>Lecture 8: Sampling distributions and the central limit theorem</a></li>
<li class="chapter" data-level="" data-path="b-ep03.html"><a href="b-ep03.html"><i class="fa fa-check"></i>Tutorial 3: Sampling and standard errors</a></li>
<li class="chapter" data-level="" data-path="b09.html"><a href="b09.html"><i class="fa fa-check"></i>Lecture 9: Confidence intervals and tests against zero</a></li>
<li class="chapter" data-level="" data-path="b10.html"><a href="b10.html"><i class="fa fa-check"></i>Lecture 10: Hypothesis testing, errors, and power</a></li>
<li class="chapter" data-level="" data-path="b-ep04.html"><a href="b-ep04.html"><i class="fa fa-check"></i>Tutorial 4: Inference and tests against zero</a></li>
<li class="chapter" data-level="" data-path="formula-sheet.html"><a href="formula-sheet.html"><i class="fa fa-check"></i>QM Basic Formula Sheet</a></li>
<li class="chapter" data-level="" data-path="basic-mock-exam.html"><a href="basic-mock-exam.html"><i class="fa fa-check"></i>Mock Exam: QM Basic</a></li>
<li class="part"><span><b>II QM Intermediate</b></span></li>
<li class="chapter" data-level="" data-path="intermediate-course.html"><a href="intermediate-course.html"><i class="fa fa-check"></i>QM Intermediate: Course overview</a></li>
<li class="chapter" data-level="" data-path="i01.html"><a href="i01.html"><i class="fa fa-check"></i>Lecture 1: Simple linear regression</a></li>
<li class="chapter" data-level="" data-path="i02.html"><a href="i02.html"><i class="fa fa-check"></i>Lecture 2: Regression assumptions and coefficient inference</a></li>
<li class="chapter" data-level="" data-path="i03.html"><a href="i03.html"><i class="fa fa-check"></i>Lecture 3: Model fit and overall usefulness</a></li>
<li class="chapter" data-level="" data-path="i-ep01.html"><a href="i-ep01.html"><i class="fa fa-check"></i>Tutorial 1: Simple regression and model usefulness</a></li>
<li class="chapter" data-level="" data-path="i04.html"><a href="i04.html"><i class="fa fa-check"></i>Lecture 4: Multiple linear regression and controls</a></li>
<li class="chapter" data-level="" data-path="i05.html"><a href="i05.html"><i class="fa fa-check"></i>Lecture 5: Dummy predictors and joint usefulness</a></li>
<li class="chapter" data-level="" data-path="i06.html"><a href="i06.html"><i class="fa fa-check"></i>Lecture 6: Interactions and polynomial terms</a></li>
<li class="chapter" data-level="" data-path="i-ep02.html"><a href="i-ep02.html"><i class="fa fa-check"></i>Tutorial 2: Multiple regression and extensions</a></li>
<li class="chapter" data-level="" data-path="intermediate-code-sheet.html"><a href="intermediate-code-sheet.html"><i class="fa fa-check"></i>QM Intermediate Code Sheet</a></li>
<li class="chapter" data-level="" data-path="intermediate-mock-exam.html"><a href="intermediate-mock-exam.html"><i class="fa fa-check"></i>Mock Exam: QM Intermediate</a></li>
<li class="part"><span><b>III QM Advanced</b></span></li>
<li class="chapter" data-level="" data-path="advanced-course.html"><a href="advanced-course.html"><i class="fa fa-check"></i>QM Advanced: Course overview</a></li>
<li class="part"><span><b>IV Supplementary resources</b></span></li>
<li class="chapter" data-level="" data-path="r-refresher.html"><a href="r-refresher.html"><i class="fa fa-check"></i>R Refresher</a></li>
<li class="chapter" data-level="" data-path="math-refresher.html"><a href="math-refresher.html"><i class="fa fa-check"></i>Mathematics Refresher</a></li>
<li class="chapter" data-level="" data-path="videos.html"><a href="videos.html"><i class="fa fa-check"></i>External Video Guide</a></li>
<li class="divider"></li>
<li class="book-footer">Quantitative Methods learning line</li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Online Textbook for the Learning Line “Quantitative Methods to Understand E&amp;BI”</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="i-ep02" class="section level1 hasAnchor">
<h1>Tutorial 2: Multiple regression and extensions<a href="i-ep02.html#i-ep02" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<div class="outcomes">
<span class="label">By the end of Tutorial 2, you can</span>
<ul>
<li>
fit and interpret multiple regression in R;
</li>
<li>
test individual and grouped coefficients against zero;
</li>
<li>
interpret dummy, interaction, and polynomial terms correctly;
</li>
<li>
compare nested models;
</li>
<li>
write a complete TestVision-ready analysis with design limits.
</li>
</ul>
</div>
<div id="before-class-21" class="section level2 hasAnchor course-phase phase-before">
<h2>Before class<a href="i-ep02.html#before-class-21" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Complete the after-class practice from Intermediate Lectures 4–6. Review
<a href="math-refresher.html#math-refresher">Mathematics Refresher: multivariable equations, indicators, products, and powers</a>
if needed. Use the complete
<a href="intermediate-code-sheet.html#intermediate-code-sheet">QM Intermediate Code Sheet</a> while working.</p>
<p>Complete from memory:</p>
<ol style="list-style-type: decimal">
<li>A multiple-regression slope is interpreted while …</li>
<li>A dummy coefficient compares …</li>
<li>An interaction coefficient is a difference in …</li>
<li>A partial F-test compares …</li>
</ol>
<details>
<summary>
Check your preparation
</summary>
<ol style="list-style-type: decimal">
<li>Holding the other included predictors fixed.</li>
<li>A category with the reference category.</li>
<li>Slopes.</li>
<li>A reduced nested model with a complete model on the same observations.</li>
</ol>
</details>
</div>
<div id="in-class-21" class="section level2 hasAnchor course-phase phase-in-class">
<h2>In class<a href="i-ep02.html#in-class-21" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Attempt each task in R before opening the answer.</p>
<div id="task-1-multiple-regression-coefficients" class="section level3 hasAnchor">
<h3>Task 1 — Multiple-regression coefficients<a href="i-ep02.html#task-1-multiple-regression-coefficients" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Fit:</p>
<div class="sourceCode" id="cb187"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb187-1"><a href="i-ep02.html#cb187-1" tabindex="-1"></a>m1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(</span>
<span id="cb187-2"><a href="i-ep02.html#cb187-2" tabindex="-1"></a>  equity_offered_pct <span class="sc">~</span> season <span class="sc">+</span> ask_100k <span class="sc">+</span> description_words,</span>
<span id="cb187-3"><a href="i-ep02.html#cb187-3" tabindex="-1"></a>  <span class="at">data =</span> sharks</span>
<span id="cb187-4"><a href="i-ep02.html#cb187-4" tabindex="-1"></a>)</span>
<span id="cb187-5"><a href="i-ep02.html#cb187-5" tabindex="-1"></a><span class="fu">summary</span>(m1)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = equity_offered_pct ~ season + ask_100k + description_words, 
##     data = sharks)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -15.295  -4.776  -1.283   3.288  82.106 
## 
## Coefficients:
##                   Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)       22.02493    0.88785  24.807  &lt; 2e-16 ***
## season            -0.83615    0.05098 -16.401  &lt; 2e-16 ***
## ask_100k          -0.28975    0.05771  -5.021 5.79e-07 ***
## description_words -0.12834    0.11375  -1.128    0.259    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 7.619 on 1437 degrees of freedom
## Multiple R-squared:  0.1876, Adjusted R-squared:  0.1859 
## F-statistic: 110.6 on 3 and 1437 DF,  p-value: &lt; 2.2e-16</code></pre>
<ol style="list-style-type: decimal">
<li>Interpret all three slopes.</li>
<li>Identify which 95% coefficient interval includes zero.</li>
<li>Interpret adjusted <span class="math inline">\(R^2\)</span> and the overall F-test.</li>
<li>State two threats to causal interpretation.</li>
</ol>
<details>
<summary>
Check your answer
</summary>
<p>At fixed values of the other included predictors, one later season is
associated with about 0.836 percentage points less initial equity; an extra
$100,000 requested with about 0.290 percentage points less equity; and one
additional description word with about 0.128 percentage points less equity.
The description-word interval includes zero. Adjusted <span class="math inline">\(R^2\approx0.186\)</span>, and
the overall F-test rejects the joint zero-slope null. Selection into the show,
unmeasured venture quality, reverse relationships, and measurement choices are
possible causal threats.</p>
</details>
</div>
<div id="task-2-dummy-variables-and-a-partial-f-test" class="section level3 hasAnchor">
<h3>Task 2 — Dummy variables and a partial F-test<a href="i-ep02.html#task-2-dummy-variables-and-a-partial-f-test" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div class="sourceCode" id="cb189"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb189-1"><a href="i-ep02.html#cb189-1" tabindex="-1"></a>reduced <span class="ot">&lt;-</span> <span class="fu">lm</span>(equity_offered_pct <span class="sc">~</span> season <span class="sc">+</span> ask_100k,</span>
<span id="cb189-2"><a href="i-ep02.html#cb189-2" tabindex="-1"></a>              <span class="at">data =</span> known_gender)</span>
<span id="cb189-3"><a href="i-ep02.html#cb189-3" tabindex="-1"></a>complete <span class="ot">&lt;-</span> <span class="fu">lm</span>(equity_offered_pct <span class="sc">~</span> season <span class="sc">+</span> ask_100k <span class="sc">+</span> gender,</span>
<span id="cb189-4"><a href="i-ep02.html#cb189-4" tabindex="-1"></a>               <span class="at">data =</span> known_gender)</span>
<span id="cb189-5"><a href="i-ep02.html#cb189-5" tabindex="-1"></a><span class="fu">summary</span>(complete)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = equity_offered_pct ~ season + ask_100k + gender, 
##     data = known_gender)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -16.118  -4.778  -1.100   3.220  82.590 
## 
## Coefficients:
##                 Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)     20.83883    0.50649  41.143  &lt; 2e-16 ***
## season          -0.82389    0.04780 -17.238  &lt; 2e-16 ***
## ask_100k        -0.26613    0.05822  -4.571 5.28e-06 ***
## genderall_women  1.28352    0.48102   2.668  0.00771 ** 
## gendermixed      0.12093    0.54115   0.223  0.82320    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 7.612 on 1429 degrees of freedom
## Multiple R-squared:  0.1913, Adjusted R-squared:  0.189 
## F-statistic: 84.49 on 4 and 1429 DF,  p-value: &lt; 2.2e-16</code></pre>
<div class="sourceCode" id="cb191"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb191-1"><a href="i-ep02.html#cb191-1" tabindex="-1"></a><span class="fu">anova</span>(reduced, complete)</span></code></pre></div>
<pre><code>## Analysis of Variance Table
## 
## Model 1: equity_offered_pct ~ season + ask_100k
## Model 2: equity_offered_pct ~ season + ask_100k + gender
##   Res.Df   RSS Df Sum of Sq      F Pr(&gt;F)  
## 1   1431 83228                             
## 2   1429 82792  2    436.25 3.7649 0.0234 *
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<ol style="list-style-type: decimal">
<li>Name the reference category.</li>
<li>Interpret both dummy coefficients.</li>
<li>State and decide the partial F-test.</li>
<li>Explain why the partial test and individual t-tests answer different
questions.</li>
</ol>
<details>
<summary>
Check your answer
</summary>
<p>The reference is all-men. At fixed season and request, all-women teams are
fitted about 1.28 percentage points higher and mixed teams about 0.12 points
higher than all-men teams. The partial null is that both dummy coefficients
equal zero; <span class="math inline">\(p\approx0.023\)</span>, so reject at 5%. The F-test asks whether the two
terms are jointly useful; each t-test asks about one reference-group contrast.
The source coding and observational design prohibit a causal gender claim.</p>
</details>
</div>
<div id="task-3-interaction" class="section level3 hasAnchor">
<h3>Task 3 — Interaction<a href="i-ep02.html#task-3-interaction" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div class="sourceCode" id="cb193"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb193-1"><a href="i-ep02.html#cb193-1" tabindex="-1"></a>m_interaction <span class="ot">&lt;-</span> <span class="fu">lm</span>(</span>
<span id="cb193-2"><a href="i-ep02.html#cb193-2" tabindex="-1"></a>  equity_offered_pct <span class="sc">~</span> season_c <span class="sc">*</span> women <span class="sc">+</span> ask_100k,</span>
<span id="cb193-3"><a href="i-ep02.html#cb193-3" tabindex="-1"></a>  <span class="at">data =</span> known_gender</span>
<span id="cb193-4"><a href="i-ep02.html#cb193-4" tabindex="-1"></a>)</span>
<span id="cb193-5"><a href="i-ep02.html#cb193-5" tabindex="-1"></a><span class="fu">summary</span>(m_interaction)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = equity_offered_pct ~ season_c * women + ask_100k, 
##     data = known_gender)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -15.871  -4.742  -1.290   3.412  82.689 
## 
## Coefficients:
##                Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)    13.62479    0.33545  40.616  &lt; 2e-16 ***
## season_c       -0.79938    0.06632 -12.053  &lt; 2e-16 ***
## women           0.80697    0.41171   1.960   0.0502 .  
## ask_100k       -0.26776    0.05834  -4.590 4.83e-06 ***
## season_c:women -0.06146    0.09557  -0.643   0.5203    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 7.62 on 1429 degrees of freedom
## Multiple R-squared:  0.1894, Adjusted R-squared:  0.1871 
## F-statistic: 83.47 on 4 and 1429 DF,  p-value: &lt; 2.2e-16</code></pre>
<ol style="list-style-type: decimal">
<li>Write the fitted line for <code>women = 0</code> and <code>women = 1</code> at a fixed request.</li>
<li>Calculate both season slopes.</li>
<li>Interpret the interaction estimate and p-value.</li>
<li>Explain the role of centering.</li>
</ol>
<details>
<summary>
Check your answer
</summary>
<p>For all-men teams, the season slope is about <span class="math inline">\(-0.799\)</span>. For teams with women
represented, it is <span class="math inline">\(-0.799-0.061=-0.861\)</span>. The estimated slope difference is
<span class="math inline">\(-0.061\)</span> percentage points per season, with <span class="math inline">\(p\approx0.520\)</span>; this model does
not provide evidence of different season trends. Centering makes the lower-order
group coefficient compare groups at the average season instead of Season 0.</p>
</details>
</div>
<div id="task-4-polynomial-term" class="section level3 hasAnchor">
<h3>Task 4 — Polynomial term<a href="i-ep02.html#task-4-polynomial-term" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div class="sourceCode" id="cb195"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb195-1"><a href="i-ep02.html#cb195-1" tabindex="-1"></a>m_linear <span class="ot">&lt;-</span> <span class="fu">lm</span>(equity_offered_pct <span class="sc">~</span> season <span class="sc">+</span> ask_100k, <span class="at">data =</span> sharks)</span>
<span id="cb195-2"><a href="i-ep02.html#cb195-2" tabindex="-1"></a>m_quadratic <span class="ot">&lt;-</span> <span class="fu">lm</span>(</span>
<span id="cb195-3"><a href="i-ep02.html#cb195-3" tabindex="-1"></a>  equity_offered_pct <span class="sc">~</span> season <span class="sc">+</span> <span class="fu">I</span>(season<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> ask_100k,</span>
<span id="cb195-4"><a href="i-ep02.html#cb195-4" tabindex="-1"></a>  <span class="at">data =</span> sharks</span>
<span id="cb195-5"><a href="i-ep02.html#cb195-5" tabindex="-1"></a>)</span>
<span id="cb195-6"><a href="i-ep02.html#cb195-6" tabindex="-1"></a><span class="fu">summary</span>(m_quadratic)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = equity_offered_pct ~ season + I(season^2) + ask_100k, 
##     data = sharks)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -16.154  -4.549  -1.011   3.390  82.000 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) 24.17168    0.82057  29.457  &lt; 2e-16 ***
## season      -1.71323    0.20567  -8.330  &lt; 2e-16 ***
## I(season^2)  0.05103    0.01137   4.489 7.74e-06 ***
## ask_100k    -0.27108    0.05740  -4.723 2.56e-06 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 7.57 on 1437 degrees of freedom
## Multiple R-squared:  0.1981, Adjusted R-squared:  0.1965 
## F-statistic: 118.3 on 3 and 1437 DF,  p-value: &lt; 2.2e-16</code></pre>
<div class="sourceCode" id="cb197"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb197-1"><a href="i-ep02.html#cb197-1" tabindex="-1"></a><span class="fu">anova</span>(m_linear, m_quadratic)</span></code></pre></div>
<pre><code>## Analysis of Variance Table
## 
## Model 1: equity_offered_pct ~ season + ask_100k
## Model 2: equity_offered_pct ~ season + I(season^2) + ask_100k
##   Res.Df   RSS Df Sum of Sq      F    Pr(&gt;F)    
## 1   1438 83493                                  
## 2   1437 82338  1    1154.5 20.149 7.737e-06 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<ol style="list-style-type: decimal">
<li>Why must <code>I(season^2)</code> be used in the R formula?</li>
<li>Decide whether the quadratic term adds fit under the classical test.</li>
<li>Calculate the fitted change from Season 10 to 11.</li>
<li>State why the curve should not be extrapolated beyond Season 16.</li>
</ol>
<details>
<summary>
Check your answer
</summary>
<p><code>I()</code> tells R to treat the expression arithmetically rather than as formula
syntax. The partial F-test has <span class="math inline">\(p&lt;0.001\)</span>, so the quadratic term adds detectable
fit. With <span class="math inline">\(b_1\approx-1.713\)</span> and <span class="math inline">\(b_2\approx0.0510\)</span>, the change from 10 to
11 is <span class="math inline">\(b_1+b_2(21)\approx-0.642\)</span> percentage points. Quadratics can turn
sharply outside the observed range and have no data support there.</p>
</details>
</div>
</div>
<div id="after-class-21" class="section level2 hasAnchor course-phase phase-after">
<h2>After class<a href="i-ep02.html#after-class-21" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="timed-integrated-task-30-minutes" class="section level3 hasAnchor">
<h3>Timed integrated task — 30 minutes<a href="i-ep02.html#timed-integrated-task-30-minutes" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Develop one model of <code>equity_offered_pct</code> using season, requested amount, the
three known source gender groups, and one justified extension.</p>
<p>Your submission must include:</p>
<ol style="list-style-type: decimal">
<li>a precise research question;</li>
<li>reproducible data preparation;</li>
<li>one pre-model visual;</li>
<li>the R formula and model summary;</li>
<li>coefficient interpretations with units and reference groups;</li>
<li>an individual t-test and an overall or partial F-test;</li>
<li><span class="math inline">\(R^2\)</span>, adjusted <span class="math inline">\(R^2\)</span>, and residual diagnostics;</li>
<li>one graph of fitted conditional predictions;</li>
<li>a 150-word conclusion separating association, uncertainty, and causal
limits.</li>
</ol>
<details>
<summary>
Check a model structure
</summary>
<p>A defensible solution could fit</p>
<div class="sourceCode" id="cb199"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb199-1"><a href="i-ep02.html#cb199-1" tabindex="-1"></a>m <span class="ot">&lt;-</span> <span class="fu">lm</span>(</span>
<span id="cb199-2"><a href="i-ep02.html#cb199-2" tabindex="-1"></a>  equity_offered_pct <span class="sc">~</span> season <span class="sc">*</span> gender <span class="sc">+</span> ask_100k,</span>
<span id="cb199-3"><a href="i-ep02.html#cb199-3" tabindex="-1"></a>  <span class="at">data =</span> known_gender</span>
<span id="cb199-4"><a href="i-ep02.html#cb199-4" tabindex="-1"></a>)</span></code></pre></div>
<p>or a quadratic-season model with group dummies. Keep lower-order terms, name
the reference group, interpret combined slopes or fitted contrasts, compare a
nested reduced model with <code>anova(reduced, complete)</code>, inspect residuals, and
plot predictions within Seasons 1–16. The conclusion must state that the
source’s broad presenter classification and selected televised records do not
identify a causal effect of gender or season.</p>
</details>
<p>QM Intermediate is complete. Review the
<a href="intermediate-code-sheet.html#intermediate-code-sheet">QM Intermediate Code Sheet</a>, attempt the
<a href="intermediate-mock-exam.html#intermediate-mock-exam">QM Intermediate Mock Exam</a>, then return to the
<a href="r-refresher.html#r-refresher">R Refresher</a>, <a href="math-refresher.html#math-refresher">Mathematics Refresher</a>, or
<a href="videos.html#videos">External Video Guide</a> whenever you need a targeted review.</p>
</div>
</div>

</div>
            </section>

          </div>
        </div>
      </div>
<a href="i06.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="intermediate-code-sheet.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
  "sharing": null,
  "fontsettings": {
    "theme": "white",
    "family": "sans",
    "size": 2
  },
  "edit": null,
  "history": {
    "link": null,
    "text": null
  },
  "view": {
    "link": null,
    "text": null
  },
  "download": null,
  "search": {
    "engine": "fuse",
    "options": null
  },
  "toc": {
    "collapse": "section",
    "scroll_highlight": true
  },
  "toolbar": {
    "position": "fixed"
  }
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
