<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Lecture 1: Simple linear regression | Online Textbook for the Learning Line “Quantitative Methods to Understand E&amp;BI”</title>
  <meta name="description" content="An online textbook for the learning line Quantitative Methods within Entrepreneurship and Business Innovation Bachelor Program at Tilburg University." />
  <meta name="generator" content="bookdown 0.47 and GitBook 2.6.7" />

  <meta property="og:title" content="Lecture 1: Simple linear regression | Online Textbook for the Learning Line “Quantitative Methods to Understand E&amp;BI”" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="An online textbook for the learning line Quantitative Methods within Entrepreneurship and Business Innovation Bachelor Program at Tilburg University." />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Lecture 1: Simple linear regression | Online Textbook for the Learning Line “Quantitative Methods to Understand E&amp;BI”" />
  
  <meta name="twitter:description" content="An online textbook for the learning line Quantitative Methods within Entrepreneurship and Business Innovation Bachelor Program at Tilburg University." />
  




  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="intermediate-course.html"/>
<link rel="next" href="i02.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

<link rel="stylesheet" href="styles.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="book-title"><a href="./">QM to Understand E&amp;BI</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Welcome</a></li>
<li class="part"><span><b>I QM Basic</b></span></li>
<li class="chapter" data-level="" data-path="basic-course.html"><a href="basic-course.html"><i class="fa fa-check"></i>QM Basic: Course overview</a></li>
<li class="chapter" data-level="" data-path="b01.html"><a href="b01.html"><i class="fa fa-check"></i>Lecture 1: Introduction to Data Analysis</a></li>
<li class="chapter" data-level="" data-path="b02.html"><a href="b02.html"><i class="fa fa-check"></i>Lecture 2: Probability foundations and random variables</a></li>
<li class="chapter" data-level="" data-path="b03.html"><a href="b03.html"><i class="fa fa-check"></i>Lecture 3: Discrete distributions and expectation</a></li>
<li class="chapter" data-level="" data-path="b-ep01.html"><a href="b-ep01.html"><i class="fa fa-check"></i>Tutorial 1: Evidence and probability foundations</a></li>
<li class="chapter" data-level="" data-path="b04.html"><a href="b04.html"><i class="fa fa-check"></i>Lecture 4: Variance, conditioning, and belief updating</a></li>
<li class="chapter" data-level="" data-path="b05.html"><a href="b05.html"><i class="fa fa-check"></i>Lecture 5: Joint random variables, covariance, and correlation</a></li>
<li class="chapter" data-level="" data-path="b-ep02.html"><a href="b-ep02.html"><i class="fa fa-check"></i>Tutorial 2: Conditioning and relationships</a></li>
<li class="chapter" data-level="" data-path="b06.html"><a href="b06.html"><i class="fa fa-check"></i>Lecture 6: Continuous distributions and the normal model</a></li>
<li class="chapter" data-level="" data-path="b07.html"><a href="b07.html"><i class="fa fa-check"></i>Lecture 7: Samples, parameters, and estimators</a></li>
<li class="chapter" data-level="" data-path="b08.html"><a href="b08.html"><i class="fa fa-check"></i>Lecture 8: Sampling distributions and the central limit theorem</a></li>
<li class="chapter" data-level="" data-path="b-ep03.html"><a href="b-ep03.html"><i class="fa fa-check"></i>Tutorial 3: Sampling and standard errors</a></li>
<li class="chapter" data-level="" data-path="b09.html"><a href="b09.html"><i class="fa fa-check"></i>Lecture 9: Confidence intervals and tests against zero</a></li>
<li class="chapter" data-level="" data-path="b10.html"><a href="b10.html"><i class="fa fa-check"></i>Lecture 10: Hypothesis testing, errors, and power</a></li>
<li class="chapter" data-level="" data-path="b-ep04.html"><a href="b-ep04.html"><i class="fa fa-check"></i>Tutorial 4: Inference and tests against zero</a></li>
<li class="chapter" data-level="" data-path="formula-sheet.html"><a href="formula-sheet.html"><i class="fa fa-check"></i>QM Basic Formula Sheet</a></li>
<li class="chapter" data-level="" data-path="basic-mock-exam.html"><a href="basic-mock-exam.html"><i class="fa fa-check"></i>Mock Exam: QM Basic</a></li>
<li class="part"><span><b>II QM Intermediate</b></span></li>
<li class="chapter" data-level="" data-path="intermediate-course.html"><a href="intermediate-course.html"><i class="fa fa-check"></i>QM Intermediate: Course overview</a></li>
<li class="chapter" data-level="" data-path="i01.html"><a href="i01.html"><i class="fa fa-check"></i>Lecture 1: Simple linear regression</a></li>
<li class="chapter" data-level="" data-path="i02.html"><a href="i02.html"><i class="fa fa-check"></i>Lecture 2: Regression assumptions and coefficient inference</a></li>
<li class="chapter" data-level="" data-path="i03.html"><a href="i03.html"><i class="fa fa-check"></i>Lecture 3: Model fit and overall usefulness</a></li>
<li class="chapter" data-level="" data-path="i-ep01.html"><a href="i-ep01.html"><i class="fa fa-check"></i>Tutorial 1: Simple regression and model usefulness</a></li>
<li class="chapter" data-level="" data-path="i04.html"><a href="i04.html"><i class="fa fa-check"></i>Lecture 4: Multiple linear regression and controls</a></li>
<li class="chapter" data-level="" data-path="i05.html"><a href="i05.html"><i class="fa fa-check"></i>Lecture 5: Dummy predictors and joint usefulness</a></li>
<li class="chapter" data-level="" data-path="i06.html"><a href="i06.html"><i class="fa fa-check"></i>Lecture 6: Interactions and polynomial terms</a></li>
<li class="chapter" data-level="" data-path="i-ep02.html"><a href="i-ep02.html"><i class="fa fa-check"></i>Tutorial 2: Multiple regression and extensions</a></li>
<li class="chapter" data-level="" data-path="intermediate-mock-exam.html"><a href="intermediate-mock-exam.html"><i class="fa fa-check"></i>Mock Exam: QM Intermediate</a></li>
<li class="part"><span><b>III QM Advanced</b></span></li>
<li class="chapter" data-level="" data-path="advanced-course.html"><a href="advanced-course.html"><i class="fa fa-check"></i>QM Advanced: Course overview</a></li>
<li class="part"><span><b>IV Supplementary resources</b></span></li>
<li class="chapter" data-level="" data-path="r-refresher.html"><a href="r-refresher.html"><i class="fa fa-check"></i>R Refresher</a></li>
<li class="chapter" data-level="" data-path="math-refresher.html"><a href="math-refresher.html"><i class="fa fa-check"></i>Mathematics Refresher</a></li>
<li class="chapter" data-level="" data-path="videos.html"><a href="videos.html"><i class="fa fa-check"></i>External Video Guide</a></li>
<li class="divider"></li>
<li class="book-footer">Quantitative Methods learning line</li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Online Textbook for the Learning Line “Quantitative Methods to Understand E&amp;BI”</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="i01" class="section level1 hasAnchor">
<h1>Lecture 1: Simple linear regression<a href="i01.html#i01" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<div class="outcomes">
<span class="label">By the end of Lecture 1, you can</span>
<ul>
<li>
state a simple linear regression model and identify its components;
</li>
<li>
explain least-squares estimation;
</li>
<li>
distinguish observations, fitted values, errors, and residuals;
</li>
<li>
fit a regression with <code>lm()</code> in R;
</li>
<li>
interpret an intercept and slope in units and within the observed range.
</li>
</ul>
</div>
<div id="before-class-14" class="section level2 hasAnchor course-phase phase-before">
<h2>Before class<a href="i01.html#before-class-14" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div class="video-prep">
<p><span class="label">Video preparation</span><br>
Watch Stanford Statistical Learning
<a href="https://www.youtube.com/watch?v=vCHtY6Me5FI&list=PLoROMvodv4rOzrYsAxzQyHb8n_RWNuS1e&index=9">3.1
Simple Linear Regression</a>. Focus on the population line, the fitted line,
and least squares.</p>
</div>
<p>If lines, slopes, intercepts, or subscripts are not secure, review
<a href="math-refresher.html#math-refresher">Mathematics Refresher: straight lines and indices</a>.</p>
<p>For the 882 pitches with an on-air deal, define:</p>
<ul>
<li><span class="math inline">\(Y_i\)</span>: agreed on-air deal amount, in $100,000s;</li>
<li><span class="math inline">\(X_i\)</span>: amount initially requested, in $100,000s.</li>
</ul>
<p>Before fitting a model, predict the sign and plausible units of the slope.</p>
<details>
<summary>
Check your preparation
</summary>
<p>The slope should be positive: larger requests tend to accompany larger agreed
amounts. Its units are $100,000 of agreed amount per $100,000 requested, which
simplifies to a ratio.</p>
</details>
</div>
<div id="in-class-14" class="section level2 hasAnchor course-phase phase-in-class">
<h2>In class<a href="i01.html#in-class-14" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p class="concept-video">
<strong>Stanford explanation (review):</strong>
<a href="https://www.youtube.com/watch?v=vCHtY6Me5FI">3.1 Simple Linear Regression</a>.
</p>
<div id="begin-with-the-data" class="section level3 hasAnchor">
<h3>Begin with the data<a href="i01.html#begin-with-the-data" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p><img src="I01-simple-linear-regression_files/figure-html/i01-scatter-1.png" width="672" /></p>
<p>Each point is one pitch with an on-air deal. Read requested amount horizontally
and agreed amount vertically; both axes use units of $100,000. The orange line
gives the fitted conditional mean, not the outcome of every pitch. The display
shows 864 of the 882 deal records so that the dense region is readable.
Eighteen records above $1 million on at least one axis are omitted from this
display but retained when estimating the orange line. Always say when a graph
is zoomed; otherwise readers may mistake the displayed range for the complete
data.</p>
</div>
<div id="the-population-model" class="section level3 hasAnchor">
<h3>The population model<a href="i01.html#the-population-model" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The simple linear regression model is</p>
<p><span class="math display">\[
Y_i=\beta_0+\beta_1X_i+\varepsilon_i.
\]</span></p>
<p>Equivalently, the conditional mean is</p>
<p><span class="math display">\[
E[Y_i\mid X_i=x]=\beta_0+\beta_1x.
\]</span></p>
<ul>
<li><span class="math inline">\(Y_i\)</span> is the outcome for observation <span class="math inline">\(i\)</span>.</li>
<li><span class="math inline">\(X_i\)</span> is the predictor.</li>
<li><span class="math inline">\(\beta_0\)</span> is the population intercept.</li>
<li><span class="math inline">\(\beta_1\)</span> is the population slope.</li>
<li><span class="math inline">\(\varepsilon_i\)</span> is the part of <span class="math inline">\(Y_i\)</span> not represented by the line.</li>
</ul>
<p>The slope is</p>
<p><span class="math display">\[
\beta_1
=E[Y\mid X=x+1]-E[Y\mid X=x].
\]</span></p>
<p>It is the expected change in <span class="math inline">\(Y\)</span> associated with a one-unit increase in
<span class="math inline">\(X\)</span>. “Associated with” is deliberate: a regression line alone does not
identify a causal effect.</p>
</div>
<div id="least-squares-estimation" class="section level3 hasAnchor">
<h3>Least-squares estimation<a href="i01.html#least-squares-estimation" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The fitted sample line is</p>
<p><span class="math display">\[
\widehat Y_i=b_0+b_1X_i.
\]</span></p>
<p>For each observation, the residual is the vertical difference</p>
<p><span class="math display">\[
e_i=Y_i-\widehat Y_i.
\]</span></p>
<div id="why-define-error-vertically" class="section level4 hasAnchor">
<h4>Why define error vertically?<a href="i01.html#why-define-error-vertically" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>For observation <span class="math inline">\(i\)</span>, the model predicts <span class="math inline">\(\widehat Y_i\)</span> at its observed
<span class="math inline">\(X_i\)</span>. The residual <span class="math inline">\(e_i=Y_i-\widehat Y_i\)</span> is therefore a difference in
the <strong>outcome’s units</strong>. A positive residual lies above the line; a negative
residual lies below it.</p>
<p>Adding raw residuals is not a useful score: positive and negative misses can
cancel. Adding absolute residuals avoids cancellation, but the resulting
objective has sharp corners and is harder to optimise algebraically. Squared
residuals are non-negative, penalise large misses more strongly, and give a
smooth objective with a tractable solution. This is a modelling choice, not a
claim that squared error is the only possible loss function.</p>
<p>Ordinary least squares chooses <span class="math inline">\(b_0\)</span> and <span class="math inline">\(b_1\)</span> to minimise</p>
<p><span class="math display">\[
\operatorname{SSE}=\sum_{i=1}^{n}e_i^2
=\sum_{i=1}^{n}(Y_i-b_0-b_1X_i)^2.
\]</span></p>
<p>The initials <strong>OLS</strong> stand for <strong>ordinary least squares</strong>: the rule that fits
the linear model by minimising this squared-error criterion.</p>
</div>
<div id="try-the-criterion-yourself" class="section level4 hasAnchor">
<h4>Try the criterion yourself<a href="i01.html#try-the-criterion-yourself" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Drag either square handle. The vertical segments are residuals; the displayed
SSE updates after every move. Then reveal the line with the smallest SSE.</p>
<div id="least-squares-lab" class="ls-lab" role="group" aria-labelledby="ls-lab-title">
<div class="ls-lab-heading">
<p><strong id="ls-lab-title">Least-squares line lab</strong>
<span id="ls-equation" aria-live="polite"></span></p>
</div>
<svg id="ls-svg" viewBox="0 0 700 390" role="img" aria-label="Scatterplot with a draggable line and vertical residual segments">
</svg>
<div class="ls-controls">
<p><label>Line height at x = 1
<input id="ls-left" type="range" min="0" max="10" step="0.05" value="3">
</label>
<label>Line height at x = 9
<input id="ls-right" type="range" min="0" max="10" step="0.05" value="7">
</label></p>
</div>
<div class="ls-actions">
<button id="ls-best" type="button">
Show least-squares fit
</button>
<button id="ls-reset" type="button">
Try another line
</button>
<p><strong id="ls-sse" aria-live="polite"></strong></p>
</div>
<p class="ls-caption">
Squares make every contribution to SSE non-negative. Longer residuals contribute disproportionately because their lengths are squared.
</p>
</div>
<script>
(function () {
  const root = document.getElementById("least-squares-lab");
  if (!root || root.dataset.ready) return;
  root.dataset.ready = "true";
  const svg = root.querySelector("#ls-svg");
  const left = root.querySelector("#ls-left");
  const right = root.querySelector("#ls-right");
  const equation = root.querySelector("#ls-equation");
  const sseText = root.querySelector("#ls-sse");
  const points = [
    {x:1, y:1.8}, {x:2, y:1.4}, {x:3, y:3.2},
    {x:4, y:4.8}, {x:5, y:4.2}, {x:6, y:6.8},
    {x:7, y:6.4}, {x:8, y:8.6}, {x:9, y:8.2}
  ];
  const ns = "http://www.w3.org/2000/svg";
  const box = {left:58, right:680, top:18, bottom:336};
  const sx = x => box.left + x / 10 * (box.right - box.left);
  const sy = y => box.bottom - y / 10 * (box.bottom - box.top);
  const add = (name, attrs, parent=svg) => {
    const el = document.createElementNS(ns, name);
    Object.entries(attrs).forEach(([k,v]) => el.setAttribute(k, v));
    parent.appendChild(el); return el;
  };
  add("line", {x1:box.left, y1:box.bottom, x2:box.right, y2:box.bottom, class:"ls-axis"});
  add("line", {x1:box.left, y1:box.top, x2:box.left, y2:box.bottom, class:"ls-axis"});
  [0,2,4,6,8,10].forEach(v => {
    add("line", {x1:sx(v), y1:box.bottom, x2:sx(v), y2:box.bottom+6, class:"ls-axis"});
    const tx=add("text", {x:sx(v), y:box.bottom+25, class:"ls-tick"}); tx.textContent=v;
    add("line", {x1:box.left-6, y1:sy(v), x2:box.left, y2:sy(v), class:"ls-axis"});
    const ty=add("text", {x:box.left-12, y:sy(v)+4, class:"ls-tick", "text-anchor":"end"}); ty.textContent=v;
  });
  const xl=add("text", {x:(box.left+box.right)/2, y:382, class:"ls-label", "text-anchor":"middle"}); xl.textContent="Predictor x";
  const yl=add("text", {x:16, y:(box.top+box.bottom)/2, class:"ls-label", transform:`rotate(-90 16 ${(box.top+box.bottom)/2})`, "text-anchor":"middle"}); yl.textContent="Outcome y";
  const residualGroup=add("g", {class:"ls-residuals"});
  const line=add("line", {class:"ls-fit-line"});
  const handleLeft=add("rect", {width:16, height:16, rx:2, class:"ls-handle", "aria-hidden":"true"});
  const handleRight=add("rect", {width:16, height:16, rx:2, class:"ls-handle", "aria-hidden":"true"});
  points.forEach(p => add("circle", {cx:sx(p.x), cy:sy(p.y), r:5.5, class:"ls-point"}));
  const meanX=points.reduce((a,p)=>a+p.x,0)/points.length;
  const meanY=points.reduce((a,p)=>a+p.y,0)/points.length;
  const bestSlope=points.reduce((a,p)=>a+(p.x-meanX)*(p.y-meanY),0) /
                  points.reduce((a,p)=>a+(p.x-meanX)**2,0);
  const bestIntercept=meanY-bestSlope*meanX;
  const fitFromHeights = () => {
    const y1=Number(left.value), y9=Number(right.value);
    const slope=(y9-y1)/8, intercept=y1-slope;
    return {intercept, slope};
  };
  function draw() {
    const {intercept, slope}=fitFromHeights();
    residualGroup.replaceChildren();
    let sse=0;
    points.forEach(p => {
      const fitted=intercept+slope*p.x;
      sse+=(p.y-fitted)**2;
      add("line", {x1:sx(p.x), y1:sy(p.y), x2:sx(p.x), y2:sy(fitted), class:"ls-residual"}, residualGroup);
    });
    line.setAttribute("x1", sx(0)); line.setAttribute("y1", sy(intercept));
    line.setAttribute("x2", sx(10)); line.setAttribute("y2", sy(intercept+10*slope));
    [[handleLeft,1,Number(left.value)],[handleRight,9,Number(right.value)]].forEach(([h,x,y])=>{
      h.setAttribute("x",sx(x)-8); h.setAttribute("y",sy(y)-8);
    });
    equation.textContent=`ŷ = ${intercept.toFixed(2)} ${slope<0?"−":"+"} ${Math.abs(slope).toFixed(2)}x`;
    sseText.textContent=`SSE = ${sse.toFixed(2)}`;
  }
  function drag(handle, slider) {
    handle.addEventListener("pointerdown", event => {
      handle.setPointerCapture(event.pointerId);
      const move = e => {
        const rect=svg.getBoundingClientRect();
        const svgY=(e.clientY-rect.top)*390/rect.height;
        const y=Math.max(0,Math.min(10,(box.bottom-svgY)*10/(box.bottom-box.top)));
        slider.value=y.toFixed(2); draw();
      };
      handle.addEventListener("pointermove", move);
      handle.addEventListener("pointerup", () => handle.removeEventListener("pointermove", move), {once:true});
    });
  }
  drag(handleLeft,left); drag(handleRight,right);
  [left,right].forEach(control => control.addEventListener("input",draw));
  root.querySelector("#ls-best").addEventListener("click",()=>{
    left.value=(bestIntercept+bestSlope).toFixed(2);
    right.value=(bestIntercept+9*bestSlope).toFixed(2); draw();
  });
  root.querySelector("#ls-reset").addEventListener("click",()=>{
    left.value=3; right.value=7; draw();
  });
  draw();
})();
</script>
<p>For simple regression,</p>
<p><span class="math display">\[
b_1=\frac{s_{XY}}{s_X^2},
\qquad
b_0=\bar y-b_1\bar x.
\]</span></p>
<p>The fitted line therefore passes through <span class="math inline">\((\bar x,\bar y)\)</span>.</p>
</div>
</div>
<div id="fit-and-read-the-model-in-r" class="section level3 hasAnchor">
<h3>Fit and read the model in R<a href="i01.html#fit-and-read-the-model-in-r" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div class="sourceCode" id="cb135"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb135-1"><a href="i01.html#cb135-1" tabindex="-1"></a>deal_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(deal_100k <span class="sc">~</span> ask_100k, <span class="at">data =</span> deals)</span>
<span id="cb135-2"><a href="i01.html#cb135-2" tabindex="-1"></a><span class="fu">coef</span>(deal_model)</span></code></pre></div>
<pre><code>## (Intercept)    ask_100k 
##   0.2757097   1.0085098</code></pre>
<p>The fitted equation is approximately</p>
<p><span class="math display">\[
\widehat{\text{deal amount}}
=0.276+1.009\times\text{amount requested},
\]</span></p>
<p>with both monetary variables measured in $100,000s.</p>
<p>The slope means that one additional $100,000 requested is associated with
about $100,900 more in the fitted agreed amount among pitches that reached an
on-air deal. It does not mean that asking for more causes investors to offer
more.</p>
<p>The intercept predicts about $27,600 at a request of zero. A zero request lies
outside the observed range and is not substantively meaningful; an intercept
can be mathematically necessary without having a useful standalone
interpretation.</p>
<div class="sourceCode" id="cb137"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb137-1"><a href="i01.html#cb137-1" tabindex="-1"></a><span class="fu">head</span>(<span class="fu">data.frame</span>(</span>
<span id="cb137-2"><a href="i01.html#cb137-2" tabindex="-1"></a>  <span class="at">observed =</span> deals<span class="sc">$</span>deal_100k,</span>
<span id="cb137-3"><a href="i01.html#cb137-3" tabindex="-1"></a>  <span class="at">fitted =</span> <span class="fu">fitted</span>(deal_model),</span>
<span id="cb137-4"><a href="i01.html#cb137-4" tabindex="-1"></a>  <span class="at">residual =</span> <span class="fu">residuals</span>(deal_model)</span>
<span id="cb137-5"><a href="i01.html#cb137-5" tabindex="-1"></a>))</span></code></pre></div>
<pre><code>##    observed    fitted   residual
## 1      0.50 0.7799646 -0.2799646
## 2      4.60 4.9148549 -0.3148549
## 6      5.00 5.3182589 -0.3182589
## 7      2.50 2.7969843 -0.2969843
## 11     0.35 0.6286881 -0.2786881
## 12     2.50 2.7969843 -0.2969843</code></pre>
<p>For every row, <code>observed = fitted + residual</code>.</p>
</div>
<div id="prediction-stays-inside-the-evidence-boundary" class="section level3 hasAnchor">
<h3>Prediction stays inside the evidence boundary<a href="i01.html#prediction-stays-inside-the-evidence-boundary" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div class="sourceCode" id="cb139"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb139-1"><a href="i01.html#cb139-1" tabindex="-1"></a><span class="fu">predict</span>(deal_model, <span class="at">newdata =</span> <span class="fu">data.frame</span>(<span class="at">ask_100k =</span> <span class="dv">3</span>))</span></code></pre></div>
<pre><code>##        1 
## 3.301239</code></pre>
<p>For a $300,000 request, the fitted mean agreed amount is about $330,000. This
is a model-based average, not a guarantee for a new pitch. Extrapolating far
beyond the observed request range would rely almost entirely on the assumed
line.</p>
</div>
</div>
<div id="after-class-14" class="section level2 hasAnchor course-phase phase-after">
<h2>After class<a href="i01.html#after-class-14" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="retrieval-9" class="section level3 hasAnchor">
<h3>Retrieval<a href="i01.html#retrieval-9" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<ol style="list-style-type: decimal">
<li>What is the difference between <span class="math inline">\(\varepsilon_i\)</span> and <span class="math inline">\(e_i\)</span>?</li>
<li>What does least squares minimise?</li>
<li>Why must a slope interpretation include units?</li>
<li>Why can an intercept be mathematically valid but substantively unhelpful?</li>
<li>Why is the slope not automatically causal?</li>
</ol>
<details>
<summary>
Check your answers
</summary>
<ol style="list-style-type: decimal">
<li><span class="math inline">\(\varepsilon_i\)</span> is an unobserved population-model error; <span class="math inline">\(e_i\)</span> is the
observed residual after fitting the sample line.</li>
<li>The sum of squared residuals.</li>
<li>The slope is change in outcome units per one predictor unit.</li>
<li>The value <span class="math inline">\(X=0\)</span> may lie outside the observed range or lack substantive
meaning.</li>
<li>The predictor was not randomly assigned and other factors may affect both
variables.</li>
</ol>
</details>
</div>
<div id="practice-9" class="section level3 hasAnchor">
<h3>Practice<a href="i01.html#practice-9" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<ol style="list-style-type: decimal">
<li>Use the fitted equation to predict the agreed amount for requests of
$100,000 and $500,000.</li>
<li>Calculate the residual for a pitch that requested $300,000 and agreed
$250,000.</li>
<li>Explain why <code>lm(y ~ x, data = df)</code> treats the variable left of <code>~</code> as the
outcome.</li>
<li>Fit <code>equity_offered_pct ~ season</code> and interpret both coefficients.</li>
<li>State the unit of every quantity in Question 4.</li>
</ol>
<details>
<summary>
Check your answers
</summary>
<ol style="list-style-type: decimal">
<li>Substitute <code>ask_100k = 1</code> and <code>ask_100k = 5</code>; the fitted values are about
1.284 and 5.318 in $100,000s.</li>
<li>The fitted amount is about 3.301 in $100,000s, so the residual is
<span class="math inline">\(2.5-3.301\approx-0.801\)</span>, or about <span class="math inline">\(-\$80{,}100\)</span>.</li>
<li>R formulas use <code>outcome ~ predictors</code>.</li>
<li>The fitted intercept is about 20.46 percentage points and the slope about
<span class="math inline">\(-0.824\)</span> percentage points per season. Later seasons are associated with
smaller initial equity offers on average.</li>
<li>The outcome and intercept use percentage points; the predictor uses seasons;
the slope uses percentage points per season.</li>
</ol>
</details>
<p>Continue to <a href="i02.html#i02">Lecture 2: Regression assumptions and coefficient inference</a>.</p>
<p>For a more formal treatment, see James et al., <em>An Introduction to Statistical
Learning</em>, 2nd ed., Sections 3.1 and 3.6.2.</p>
</div>
</div>

</div>
            </section>

          </div>
        </div>
      </div>
<a href="intermediate-course.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="i02.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
  "sharing": null,
  "fontsettings": {
    "theme": "white",
    "family": "sans",
    "size": 2
  },
  "edit": null,
  "history": {
    "link": null,
    "text": null
  },
  "view": {
    "link": null,
    "text": null
  },
  "download": null,
  "search": {
    "engine": "fuse",
    "options": null
  },
  "toc": {
    "collapse": "section",
    "scroll_highlight": true
  },
  "toolbar": {
    "position": "fixed"
  }
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
