<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Lecture 2: Regression assumptions and coefficient inference | Online Textbook for the Learning Line “Quantitative Methods to Understand E&amp;BI”</title>
  <meta name="description" content="An online textbook for the learning line Quantitative Methods within Entrepreneurship and Business Innovation Bachelor Program at Tilburg University." />
  <meta name="generator" content="bookdown 0.47 and GitBook 2.6.7" />

  <meta property="og:title" content="Lecture 2: Regression assumptions and coefficient inference | Online Textbook for the Learning Line “Quantitative Methods to Understand E&amp;BI”" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="An online textbook for the learning line Quantitative Methods within Entrepreneurship and Business Innovation Bachelor Program at Tilburg University." />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Lecture 2: Regression assumptions and coefficient inference | Online Textbook for the Learning Line “Quantitative Methods to Understand E&amp;BI”" />
  
  <meta name="twitter:description" content="An online textbook for the learning line Quantitative Methods within Entrepreneurship and Business Innovation Bachelor Program at Tilburg University." />
  




  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="i01.html"/>
<link rel="next" href="i03.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

<link rel="stylesheet" href="styles.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="book-title"><a href="./">QM to Understand E&amp;BI</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Welcome</a></li>
<li class="part"><span><b>I QM Basic</b></span></li>
<li class="chapter" data-level="" data-path="basic-course.html"><a href="basic-course.html"><i class="fa fa-check"></i>QM Basic: Course overview</a></li>
<li class="chapter" data-level="" data-path="b01.html"><a href="b01.html"><i class="fa fa-check"></i>Lecture 1: Introduction to Data Analysis</a></li>
<li class="chapter" data-level="" data-path="b02.html"><a href="b02.html"><i class="fa fa-check"></i>Lecture 2: Probability foundations and random variables</a></li>
<li class="chapter" data-level="" data-path="b03.html"><a href="b03.html"><i class="fa fa-check"></i>Lecture 3: Discrete distributions and expectation</a></li>
<li class="chapter" data-level="" data-path="b-ep01.html"><a href="b-ep01.html"><i class="fa fa-check"></i>Tutorial 1: Evidence and probability foundations</a></li>
<li class="chapter" data-level="" data-path="b04.html"><a href="b04.html"><i class="fa fa-check"></i>Lecture 4: Variance, conditioning, and belief updating</a></li>
<li class="chapter" data-level="" data-path="b05.html"><a href="b05.html"><i class="fa fa-check"></i>Lecture 5: Joint random variables, covariance, and correlation</a></li>
<li class="chapter" data-level="" data-path="b-ep02.html"><a href="b-ep02.html"><i class="fa fa-check"></i>Tutorial 2: Conditioning and relationships</a></li>
<li class="chapter" data-level="" data-path="b06.html"><a href="b06.html"><i class="fa fa-check"></i>Lecture 6: Continuous distributions and the normal model</a></li>
<li class="chapter" data-level="" data-path="b07.html"><a href="b07.html"><i class="fa fa-check"></i>Lecture 7: Samples, parameters, and estimators</a></li>
<li class="chapter" data-level="" data-path="b08.html"><a href="b08.html"><i class="fa fa-check"></i>Lecture 8: Sampling distributions and the central limit theorem</a></li>
<li class="chapter" data-level="" data-path="b-ep03.html"><a href="b-ep03.html"><i class="fa fa-check"></i>Tutorial 3: Sampling and standard errors</a></li>
<li class="chapter" data-level="" data-path="b09.html"><a href="b09.html"><i class="fa fa-check"></i>Lecture 9: Confidence intervals and tests against zero</a></li>
<li class="chapter" data-level="" data-path="b10.html"><a href="b10.html"><i class="fa fa-check"></i>Lecture 10: Hypothesis testing, errors, and power</a></li>
<li class="chapter" data-level="" data-path="b-ep04.html"><a href="b-ep04.html"><i class="fa fa-check"></i>Tutorial 4: Inference and tests against zero</a></li>
<li class="chapter" data-level="" data-path="formula-sheet.html"><a href="formula-sheet.html"><i class="fa fa-check"></i>QM Basic Formula Sheet</a></li>
<li class="chapter" data-level="" data-path="basic-mock-exam.html"><a href="basic-mock-exam.html"><i class="fa fa-check"></i>Mock Exam: QM Basic</a></li>
<li class="part"><span><b>II QM Intermediate</b></span></li>
<li class="chapter" data-level="" data-path="intermediate-course.html"><a href="intermediate-course.html"><i class="fa fa-check"></i>QM Intermediate: Course overview</a></li>
<li class="chapter" data-level="" data-path="i01.html"><a href="i01.html"><i class="fa fa-check"></i>Lecture 1: Simple linear regression</a></li>
<li class="chapter" data-level="" data-path="i02.html"><a href="i02.html"><i class="fa fa-check"></i>Lecture 2: Regression assumptions and coefficient inference</a></li>
<li class="chapter" data-level="" data-path="i03.html"><a href="i03.html"><i class="fa fa-check"></i>Lecture 3: Model fit and overall usefulness</a></li>
<li class="chapter" data-level="" data-path="i-ep01.html"><a href="i-ep01.html"><i class="fa fa-check"></i>Tutorial 1: Simple regression and model usefulness</a></li>
<li class="chapter" data-level="" data-path="i04.html"><a href="i04.html"><i class="fa fa-check"></i>Lecture 4: Multiple linear regression and controls</a></li>
<li class="chapter" data-level="" data-path="i05.html"><a href="i05.html"><i class="fa fa-check"></i>Lecture 5: Dummy predictors and joint usefulness</a></li>
<li class="chapter" data-level="" data-path="i06.html"><a href="i06.html"><i class="fa fa-check"></i>Lecture 6: Interactions and polynomial terms</a></li>
<li class="chapter" data-level="" data-path="i-ep02.html"><a href="i-ep02.html"><i class="fa fa-check"></i>Tutorial 2: Multiple regression and extensions</a></li>
<li class="chapter" data-level="" data-path="intermediate-code-sheet.html"><a href="intermediate-code-sheet.html"><i class="fa fa-check"></i>QM Intermediate Code Sheet</a></li>
<li class="chapter" data-level="" data-path="intermediate-mock-exam.html"><a href="intermediate-mock-exam.html"><i class="fa fa-check"></i>Mock Exam: QM Intermediate</a></li>
<li class="part"><span><b>III QM Advanced</b></span></li>
<li class="chapter" data-level="" data-path="advanced-course.html"><a href="advanced-course.html"><i class="fa fa-check"></i>QM Advanced: Course overview</a></li>
<li class="part"><span><b>IV Supplementary resources</b></span></li>
<li class="chapter" data-level="" data-path="r-refresher.html"><a href="r-refresher.html"><i class="fa fa-check"></i>R Refresher</a></li>
<li class="chapter" data-level="" data-path="math-refresher.html"><a href="math-refresher.html"><i class="fa fa-check"></i>Mathematics Refresher</a></li>
<li class="chapter" data-level="" data-path="videos.html"><a href="videos.html"><i class="fa fa-check"></i>External Video Guide</a></li>
<li class="divider"></li>
<li class="book-footer">Quantitative Methods learning line</li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Online Textbook for the Learning Line “Quantitative Methods to Understand E&amp;BI”</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="i02" class="section level1 hasAnchor">
<h1>Lecture 2: Regression assumptions and coefficient inference<a href="i02.html#i02" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<div class="outcomes">
<span class="label">By the end of Lecture 2, you can</span>
<ul>
<li>
state the assumptions behind ordinary least-squares estimation and inference;
</li>
<li>
inspect residual plots for non-linearity, unequal variance, and unusual observations;
</li>
<li>
interpret coefficient standard errors and confidence intervals;
</li>
<li>
test a regression coefficient against zero;
</li>
<li>
explain when robust standard errors help and what they cannot repair.
</li>
</ul>
</div>
<div id="before-class-15" class="section level2 hasAnchor course-phase phase-before">
<h2>Before class<a href="i02.html#before-class-15" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div class="video-prep">
<p><span class="label">Video preparation</span><br>
Watch Stanford Statistical Learning
<a href="https://www.youtube.com/watch?v=3GiWpRfkSjc&list=PLoROMvodv4rOzrYsAxzQyHb8n_RWNuS1e&index=10">3.2
Hypothesis Testing and Confidence Intervals</a>. Focus on the standard error of
a coefficient and the test <span class="math inline">\(H_0:\beta_1=0\)</span>.</p>
</div>
<p>Review <a href="math-refresher.html#math-refresher">Mathematics Refresher: standardisation and inequalities</a>
if needed.</p>
<p>Explain in one sentence why a steep fitted slope can still be estimated
imprecisely.</p>
<details>
<summary>
Check your preparation
</summary>
<p>Slope size and slope precision are different: a steep estimate can have a
large standard error when the data are noisy, sparse, dependent, or dominated
by unusual observations.</p>
</details>
</div>
<div id="in-class-15" class="section level2 hasAnchor course-phase phase-in-class">
<h2>In class<a href="i02.html#in-class-15" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p class="concept-video">
<strong>Stanford explanation (review):</strong>
<a href="https://www.youtube.com/watch?v=3GiWpRfkSjc">3.2 Hypothesis Testing and Confidence Intervals</a>.
</p>
<div id="what-each-assumption-supports" class="section level3 hasAnchor">
<h3>What each assumption supports<a href="i02.html#what-each-assumption-supports" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>For</p>
<p><span class="math display">\[
Y_i=\beta_0+\beta_1X_i+\varepsilon_i,
\]</span></p>
<p>separate the conditions below rather than memorising one vague statement that
“the data are normal.” Each condition supports a different part of the
analysis.</p>
<table>
<colgroup>
<col width="33%" />
<col width="33%" />
<col width="33%" />
</colgroup>
<thead>
<tr class="header">
<th>Condition</th>
<th>Meaning</th>
<th>What it supports</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Linear conditional mean</td>
<td><span class="math inline">\(E[Y\mid X=x]=\beta_0+\beta_1x\)</span> over the modelled range</td>
<td>One constant slope summarises the mean relationship</td>
</tr>
<tr class="even">
<td>Zero conditional mean</td>
<td><span class="math inline">\(E[\varepsilon\mid X]=0\)</span></td>
<td>The slope is not systematically absorbing omitted components related to <span class="math inline">\(X\)</span></td>
</tr>
<tr class="odd">
<td>Independent observations</td>
<td>Errors from different rows do not supply duplicate information</td>
<td>The usual standard-error calculation and effective sample size</td>
</tr>
<tr class="even">
<td>Positive variation in <span class="math inline">\(X\)</span></td>
<td>Not all observations have the same predictor value</td>
<td>A slope can be estimated</td>
</tr>
<tr class="odd">
<td>Constant conditional variance</td>
<td><span class="math inline">\(\operatorname{Var}(\varepsilon\mid X)=\sigma^2\)</span></td>
<td>Classical OLS standard errors have the stated form</td>
</tr>
<tr class="even">
<td>Conditional normality</td>
<td><span class="math inline">\(\varepsilon\mid X\)</span> follows a normal distribution</td>
<td>Exact t and F reference distributions in small samples</td>
</tr>
</tbody>
</table>
<p>The outcome and predictor themselves do not need to be normally distributed.
The assumptions concern the conditional mean, errors, and sampling process.</p>
<div id="linearity-is-about-the-average-not-every-point" class="section level4 hasAnchor">
<h4>Linearity is about the average, not every point<a href="i02.html#linearity-is-about-the-average-not-every-point" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Individual outcomes need not lie on a line. Linearity says that the average
outcome at each predictor value follows a line. A systematic curve in
residuals means one constant slope misses part of that average pattern.</p>
</div>
<div id="constant-variance-is-about-vertical-spread" class="section level4 hasAnchor">
<h4>Constant variance is about vertical spread<a href="i02.html#constant-variance-is-about-vertical-spread" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Homoskedasticity says that the conditional variance is the same at each
predictor value. It does not say all residuals have the same size. A fan-shaped
residual plot—in which the vertical band widens or narrows—suggests changing
conditional variance.</p>
<p><img src="I02-regression-inference_files/figure-html/i02-assumption-illustrations-1.png" width="672" /></p>
<p>The top-right pattern points to a misspecified conditional mean. The bottom
right pattern points to non-constant conditional variance. A real plot can
show both problems at once, and absence of a visible pattern is not proof that
all assumptions hold.</p>
</div>
<div id="zero-conditional-mean-and-independence-require-design-knowledge" class="section level4 hasAnchor">
<h4>Zero conditional mean and independence require design knowledge<a href="i02.html#zero-conditional-mean-and-independence-require-design-knowledge" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Residual plots cannot establish <span class="math inline">\(E[\varepsilon\mid X]=0\)</span>: fitted OLS
residuals are mechanically centred and unobserved confounders are not shown.
Ask how the observations were selected, what plausible common causes were
omitted, and whether measurement error or reverse direction is credible.</p>
<p>Independence also comes from the data-generating process. Repeated pitches by
one venture, teams within one network, or observations close in time may be
related. If rows share information, treating all of them as independent can
make the effective sample size look too large and SEs too small.</p>
</div>
<div id="conditional-normality-matters-most-in-small-samples" class="section level4 hasAnchor">
<h4>Conditional normality matters most in small samples<a href="i02.html#conditional-normality-matters-most-in-small-samples" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Normality concerns the distribution of errors at fixed predictor values. It is
used to derive exact small-sample t and F results. With large independent
samples and no dominant observations, approximate inference is often less
sensitive to moderate non-normality. Severe outliers can still distort both
the fitted line and its uncertainty.</p>
</div>
</div>
<div id="diagnose-with-residuals" class="section level3 hasAnchor">
<h3>Diagnose with residuals<a href="i02.html#diagnose-with-residuals" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p><img src="I02-regression-inference_files/figure-html/i02-diagnostics-1.png" width="672" /></p>
<p>In the left panel, fitted outcomes are horizontal and observed-minus-fitted
residuals are vertical, in the outcome’s original units. In the right panel,
the horizontal axis gives theoretical normal quantiles and the vertical axis
gives ordered standardised residuals; normal residuals should lie roughly on
the reference line. Use the panels to ask:</p>
<ul>
<li>Is there curvature around zero?</li>
<li>Does vertical spread change with the fitted value?</li>
<li>Are there unusually large residuals?</li>
<li>Does the normal Q–Q plot depart strongly from a straight line?</li>
</ul>
<p>These data contain influential high-value pitches and unequal residual spread.
The classical model summary is therefore a starting point, not the end of the
diagnosis.</p>
</div>
<div id="standard-errors-and-confidence-intervals" class="section level3 hasAnchor">
<h3>Standard errors and confidence intervals<a href="i02.html#standard-errors-and-confidence-intervals" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div class="sourceCode" id="cb145"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb145-1"><a href="i02.html#cb145-1" tabindex="-1"></a><span class="fu">summary</span>(deal_model)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = deal_100k ~ ask_100k, data = deals)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -4.3438 -0.3012 -0.2885 -0.2821 28.2115 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  0.27571    0.07241   3.808  0.00015 ***
## ask_100k     1.00851    0.01821  55.395  &lt; 2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 1.619 on 880 degrees of freedom
## Multiple R-squared:  0.7771, Adjusted R-squared:  0.7769 
## F-statistic:  3069 on 1 and 880 DF,  p-value: &lt; 2.2e-16</code></pre>
<div class="sourceCode" id="cb147"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb147-1"><a href="i02.html#cb147-1" tabindex="-1"></a><span class="fu">confint</span>(deal_model)</span></code></pre></div>
<pre><code>##                 2.5 %    97.5 %
## (Intercept) 0.1335981 0.4178212
## ask_100k    0.9727782 1.0442414</code></pre>
<p>The estimated slope is <span class="math inline">\(b_1=1.0085\)</span> with classical SE 0.0182. A 95%
confidence interval is approximately</p>
<p><span class="math display">\[
b_1\pm t_{0.975,880}\operatorname{SE}(b_1).
\]</span></p>
<p>The residual degrees of freedom are <span class="math inline">\(n-2=882-2=880\)</span>: estimating the
intercept and slope uses two pieces of information. With <span class="math inline">\(k\)</span> slopes plus an
intercept, residual degrees of freedom become <span class="math inline">\(n-k-1\)</span>.</p>
<p>The interval describes sampling uncertainty under the model conditions. It
does not include uncertainty from selection into televised pitches, the
decision to analyse only on-air deals, or measurement choices.</p>
</div>
<div id="testing-a-coefficient-against-zero" class="section level3 hasAnchor">
<h3>Testing a coefficient against zero<a href="i02.html#testing-a-coefficient-against-zero" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The standard significance test is</p>
<p><span class="math display">\[
H_0:\beta_1=0
\qquad\text{versus}\qquad
H_1:\beta_1\ne0.
\]</span></p>
<p>The test statistic is</p>
<p><span class="math display">\[
t=\frac{b_1-0}{\operatorname{SE}(b_1)}.
\]</span></p>
<div class="sourceCode" id="cb149"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb149-1"><a href="i02.html#cb149-1" tabindex="-1"></a>coef_table <span class="ot">&lt;-</span> <span class="fu">summary</span>(deal_model)<span class="sc">$</span>coefficients</span>
<span id="cb149-2"><a href="i02.html#cb149-2" tabindex="-1"></a>b1 <span class="ot">&lt;-</span> coef_table[<span class="st">&quot;ask_100k&quot;</span>, <span class="st">&quot;Estimate&quot;</span>]</span>
<span id="cb149-3"><a href="i02.html#cb149-3" tabindex="-1"></a>se_b1 <span class="ot">&lt;-</span> coef_table[<span class="st">&quot;ask_100k&quot;</span>, <span class="st">&quot;Std. Error&quot;</span>]</span>
<span id="cb149-4"><a href="i02.html#cb149-4" tabindex="-1"></a>t_value <span class="ot">&lt;-</span> b1 <span class="sc">/</span> se_b1</span>
<span id="cb149-5"><a href="i02.html#cb149-5" tabindex="-1"></a>p_value <span class="ot">&lt;-</span> <span class="dv">2</span> <span class="sc">*</span> <span class="fu">pt</span>(<span class="sc">-</span><span class="fu">abs</span>(t_value), <span class="at">df =</span> <span class="fu">df.residual</span>(deal_model))</span>
<span id="cb149-6"><a href="i02.html#cb149-6" tabindex="-1"></a></span>
<span id="cb149-7"><a href="i02.html#cb149-7" tabindex="-1"></a><span class="fu">c</span>(<span class="at">estimate =</span> b1, <span class="at">standard_error =</span> se_b1,</span>
<span id="cb149-8"><a href="i02.html#cb149-8" tabindex="-1"></a>  <span class="at">t_statistic =</span> t_value, <span class="at">p_value =</span> p_value)</span></code></pre></div>
<pre><code>##       estimate standard_error    t_statistic        p_value 
##   1.008510e+00   1.820567e-02   5.539538e+01  4.161677e-289</code></pre>
<p>The tiny p-value is evidence against a zero linear association in this
selected sample/model. It does not prove that the model is well specified,
that the association is important in every context, or that requesting more
causes a larger deal.</p>
</div>
<div id="robust-standard-errors" class="section level3 hasAnchor">
<h3>Robust standard errors<a href="i02.html#robust-standard-errors" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Heteroskedasticity-consistent, or <strong>robust</strong>, standard errors relax the
constant-variance assumption for inference. The fitted coefficients remain
the ordinary least-squares values; the estimated uncertainty changes.</p>
<div class="sourceCode" id="cb151"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb151-1"><a href="i02.html#cb151-1" tabindex="-1"></a><span class="co"># Run this if these packages are available in the course R environment</span></span>
<span id="cb151-2"><a href="i02.html#cb151-2" tabindex="-1"></a><span class="fu">library</span>(lmtest)</span>
<span id="cb151-3"><a href="i02.html#cb151-3" tabindex="-1"></a><span class="fu">library</span>(sandwich)</span>
<span id="cb151-4"><a href="i02.html#cb151-4" tabindex="-1"></a></span>
<span id="cb151-5"><a href="i02.html#cb151-5" tabindex="-1"></a><span class="fu">coeftest</span>(deal_model, <span class="at">vcov. =</span> <span class="fu">vcovHC</span>(deal_model, <span class="at">type =</span> <span class="st">&quot;HC1&quot;</span>))</span></code></pre></div>
<p>Robust SEs do not repair non-linearity, omitted-variable bias, dependence
across rows, influential errors in the data, or non-random selection. They
address one specific problem: misspecification of conditional error variance.</p>
</div>
<div id="assumptions-belong-in-the-conclusion" class="section level3 hasAnchor">
<h3>Assumptions belong in the conclusion<a href="i02.html#assumptions-belong-in-the-conclusion" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>A defensible interpretation combines four pieces:</p>
<ol style="list-style-type: decimal">
<li>estimate and units;</li>
<li>uncertainty or test result;</li>
<li>population/model scope;</li>
<li>causal boundary.</li>
</ol>
<p>Avoid interpreting significance stars without the coefficient, SE, units,
and model conditions.</p>
</div>
</div>
<div id="after-class-15" class="section level2 hasAnchor course-phase phase-after">
<h2>After class<a href="i02.html#after-class-15" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="retrieval-10" class="section level3 hasAnchor">
<h3>Retrieval<a href="i02.html#retrieval-10" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<ol style="list-style-type: decimal">
<li>Which assumption concerns the conditional mean?</li>
<li>Which assumption do robust SEs relax?</li>
<li>What is tested by <span class="math inline">\(H_0:\beta_1=0\)</span>?</li>
<li>Why need <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span> not be normally distributed?</li>
<li>Name two problems robust SEs do not solve.</li>
<li>Which assumptions cannot be established from a residual plot alone?</li>
</ol>
<details>
<summary>
Check your answers
</summary>
<ol style="list-style-type: decimal">
<li>Linearity and zero conditional mean.</li>
<li>Homoskedasticity for coefficient inference.</li>
<li>Whether the population linear slope is zero within the stated model.</li>
<li>Classical normality concerns the errors conditional on predictors, not the
marginal distributions of <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span>.</li>
<li>Any two of non-linearity, omitted-variable bias, dependence, measurement
error, influential observations, or selection bias.</li>
<li>Zero conditional mean and independence require knowledge of the design and
data-generating process; a plot alone cannot establish them.</li>
</ol>
</details>
</div>
<div id="practice-10" class="section level3 hasAnchor">
<h3>Practice<a href="i02.html#practice-10" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<ol style="list-style-type: decimal">
<li>From <code>summary(deal_model)</code>, write an exam-ready interpretation of the slope,
SE, and p-value.</li>
<li>Explain what a funnel shape in a residual-versus-fitted plot suggests.</li>
<li>Explain what a curved residual pattern suggests.</li>
<li>State why analysing only successful on-air deals changes the target
population.</li>
<li>Fit <code>equity_offered_pct ~ season</code>, calculate a 95% interval for its slope,
and assess <span class="math inline">\(H_0:\beta_1=0\)</span>.</li>
<li>A regression uses <span class="math inline">\(n=75\)</span> observations, an intercept, and three slopes.
State the residual degrees of freedom and explain the subtraction.</li>
</ol>
<details>
<summary>
Check your answers
</summary>
<ol style="list-style-type: decimal">
<li>One extra $100,000 requested is associated with about $100,900 more in the
fitted on-air deal amount among deal records; the classical SE is about
$1,821 per $100,000 requested and the p-value is below 0.001. The result is
associational and its classical SE relies on model conditions that the
diagnostic plots call into question.</li>
<li>Unequal conditional variance.</li>
<li>A misspecified linear conditional mean.</li>
<li>Pitches without a deal are structurally excluded, so the analysis describes
deal records rather than all televised pitches.</li>
<li><code>confint(lm(equity_offered_pct ~ season, data = sharks))</code> gives a negative
interval that excludes zero; the corresponding two-sided test rejects a
zero slope.</li>
<li><span class="math inline">\(df=75-3-1=71\)</span>. Four coefficients—the intercept and three slopes—are
estimated before residual variation is used for inference.</li>
</ol>
</details>
<p>Continue to <a href="i03.html#i03">Lecture 3: Model fit and overall usefulness</a>.</p>
<p>For a more formal treatment, see James et al., <em>An Introduction to Statistical
Learning</em>, 2nd ed., Sections 3.1.2 and 3.3.3, and
<a href="https://tilburguniversity.on.worldcat.org/oclc/317545871">Nieuwenhuis, <em>Statistical Methods for Business and Economics</em></a>,
Chapters 19 and 22.</p>
</div>
</div>

</div>
            </section>

          </div>
        </div>
      </div>
<a href="i01.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="i03.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
  "sharing": null,
  "fontsettings": {
    "theme": "white",
    "family": "sans",
    "size": 2
  },
  "edit": null,
  "history": {
    "link": null,
    "text": null
  },
  "view": {
    "link": null,
    "text": null
  },
  "download": null,
  "search": {
    "engine": "fuse",
    "options": null
  },
  "toc": {
    "collapse": "section",
    "scroll_highlight": true
  },
  "toolbar": {
    "position": "fixed"
  }
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
