<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Lecture 3: Model fit and overall usefulness | Online Textbook for the Learning Line “Quantitative Methods to Understand E&amp;BI”</title>
  <meta name="description" content="An online textbook for the learning line Quantitative Methods within Entrepreneurship and Business Innovation Bachelor Program at Tilburg University." />
  <meta name="generator" content="bookdown 0.47 and GitBook 2.6.7" />

  <meta property="og:title" content="Lecture 3: Model fit and overall usefulness | Online Textbook for the Learning Line “Quantitative Methods to Understand E&amp;BI”" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="An online textbook for the learning line Quantitative Methods within Entrepreneurship and Business Innovation Bachelor Program at Tilburg University." />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Lecture 3: Model fit and overall usefulness | Online Textbook for the Learning Line “Quantitative Methods to Understand E&amp;BI”" />
  
  <meta name="twitter:description" content="An online textbook for the learning line Quantitative Methods within Entrepreneurship and Business Innovation Bachelor Program at Tilburg University." />
  




  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="i02.html"/>
<link rel="next" href="i-ep01.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

<link rel="stylesheet" href="styles.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="book-title"><a href="./">QM to Understand E&amp;BI</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Welcome</a></li>
<li class="part"><span><b>I QM Basic</b></span></li>
<li class="chapter" data-level="" data-path="basic-course.html"><a href="basic-course.html"><i class="fa fa-check"></i>QM Basic: Course overview</a></li>
<li class="chapter" data-level="" data-path="b01.html"><a href="b01.html"><i class="fa fa-check"></i>Lecture 1: Introduction to Data Analysis</a></li>
<li class="chapter" data-level="" data-path="b02.html"><a href="b02.html"><i class="fa fa-check"></i>Lecture 2: Probability foundations and random variables</a></li>
<li class="chapter" data-level="" data-path="b03.html"><a href="b03.html"><i class="fa fa-check"></i>Lecture 3: Discrete distributions and expectation</a></li>
<li class="chapter" data-level="" data-path="b-ep01.html"><a href="b-ep01.html"><i class="fa fa-check"></i>Tutorial 1: Evidence and probability foundations</a></li>
<li class="chapter" data-level="" data-path="b04.html"><a href="b04.html"><i class="fa fa-check"></i>Lecture 4: Variance, conditioning, and belief updating</a></li>
<li class="chapter" data-level="" data-path="b05.html"><a href="b05.html"><i class="fa fa-check"></i>Lecture 5: Joint random variables, covariance, and correlation</a></li>
<li class="chapter" data-level="" data-path="b-ep02.html"><a href="b-ep02.html"><i class="fa fa-check"></i>Tutorial 2: Conditioning and relationships</a></li>
<li class="chapter" data-level="" data-path="b06.html"><a href="b06.html"><i class="fa fa-check"></i>Lecture 6: Continuous distributions and the normal model</a></li>
<li class="chapter" data-level="" data-path="b07.html"><a href="b07.html"><i class="fa fa-check"></i>Lecture 7: Samples, parameters, and estimators</a></li>
<li class="chapter" data-level="" data-path="b08.html"><a href="b08.html"><i class="fa fa-check"></i>Lecture 8: Sampling distributions and the central limit theorem</a></li>
<li class="chapter" data-level="" data-path="b-ep03.html"><a href="b-ep03.html"><i class="fa fa-check"></i>Tutorial 3: Sampling and standard errors</a></li>
<li class="chapter" data-level="" data-path="b09.html"><a href="b09.html"><i class="fa fa-check"></i>Lecture 9: Confidence intervals and tests against zero</a></li>
<li class="chapter" data-level="" data-path="b10.html"><a href="b10.html"><i class="fa fa-check"></i>Lecture 10: Hypothesis testing, errors, and power</a></li>
<li class="chapter" data-level="" data-path="b-ep04.html"><a href="b-ep04.html"><i class="fa fa-check"></i>Tutorial 4: Inference and tests against zero</a></li>
<li class="chapter" data-level="" data-path="formula-sheet.html"><a href="formula-sheet.html"><i class="fa fa-check"></i>QM Basic Formula Sheet</a></li>
<li class="chapter" data-level="" data-path="basic-mock-exam.html"><a href="basic-mock-exam.html"><i class="fa fa-check"></i>Mock Exam: QM Basic</a></li>
<li class="part"><span><b>II QM Intermediate</b></span></li>
<li class="chapter" data-level="" data-path="intermediate-course.html"><a href="intermediate-course.html"><i class="fa fa-check"></i>QM Intermediate: Course overview</a></li>
<li class="chapter" data-level="" data-path="i01.html"><a href="i01.html"><i class="fa fa-check"></i>Lecture 1: Simple linear regression</a></li>
<li class="chapter" data-level="" data-path="i02.html"><a href="i02.html"><i class="fa fa-check"></i>Lecture 2: Regression assumptions and coefficient inference</a></li>
<li class="chapter" data-level="" data-path="i03.html"><a href="i03.html"><i class="fa fa-check"></i>Lecture 3: Model fit and overall usefulness</a></li>
<li class="chapter" data-level="" data-path="i-ep01.html"><a href="i-ep01.html"><i class="fa fa-check"></i>Tutorial 1: Simple regression and model usefulness</a></li>
<li class="chapter" data-level="" data-path="i04.html"><a href="i04.html"><i class="fa fa-check"></i>Lecture 4: Multiple linear regression and controls</a></li>
<li class="chapter" data-level="" data-path="i05.html"><a href="i05.html"><i class="fa fa-check"></i>Lecture 5: Dummy predictors and joint usefulness</a></li>
<li class="chapter" data-level="" data-path="i06.html"><a href="i06.html"><i class="fa fa-check"></i>Lecture 6: Interactions and polynomial terms</a></li>
<li class="chapter" data-level="" data-path="i-ep02.html"><a href="i-ep02.html"><i class="fa fa-check"></i>Tutorial 2: Multiple regression and extensions</a></li>
<li class="chapter" data-level="" data-path="intermediate-code-sheet.html"><a href="intermediate-code-sheet.html"><i class="fa fa-check"></i>QM Intermediate Code Sheet</a></li>
<li class="chapter" data-level="" data-path="intermediate-mock-exam.html"><a href="intermediate-mock-exam.html"><i class="fa fa-check"></i>Mock Exam: QM Intermediate</a></li>
<li class="part"><span><b>III QM Advanced</b></span></li>
<li class="chapter" data-level="" data-path="advanced-course.html"><a href="advanced-course.html"><i class="fa fa-check"></i>QM Advanced: Course overview</a></li>
<li class="part"><span><b>IV Supplementary resources</b></span></li>
<li class="chapter" data-level="" data-path="r-refresher.html"><a href="r-refresher.html"><i class="fa fa-check"></i>R Refresher</a></li>
<li class="chapter" data-level="" data-path="math-refresher.html"><a href="math-refresher.html"><i class="fa fa-check"></i>Mathematics Refresher</a></li>
<li class="chapter" data-level="" data-path="videos.html"><a href="videos.html"><i class="fa fa-check"></i>External Video Guide</a></li>
<li class="divider"></li>
<li class="book-footer">Quantitative Methods learning line</li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Online Textbook for the Learning Line “Quantitative Methods to Understand E&amp;BI”</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="i03" class="section level1 hasAnchor">
<h1>Lecture 3: Model fit and overall usefulness<a href="i03.html#i03" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<div class="outcomes">
<span class="label">By the end of Lecture 3, you can</span>
<ul>
<li>
decompose outcome variation into explained and residual components;
</li>
<li>
calculate and interpret <span class="math inline">\(R^2\)</span>;
</li>
<li>
state and interpret the overall F-test for model usefulness;
</li>
<li>
connect the simple-regression F-test to the slope t-test;
</li>
<li>
distinguish fit, statistical evidence, prediction, and causality.
</li>
</ul>
</div>
<div id="before-class-16" class="section level2 hasAnchor course-phase phase-before">
<h2>Before class<a href="i03.html#before-class-16" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div class="video-prep">
<p><span class="label">Video preparation</span><br>
Watch Stanford Statistical Learning
<a href="https://www.youtube.com/watch?v=50sv4UTjE90&list=PLoROMvodv4rOzrYsAxzQyHb8n_RWNuS1e&index=12">3.4
Some Important Questions</a>. Focus on the questions “Is there a relationship?”
and “How accurately can we predict the response?”</p>
</div>
<p>If squared terms or ratios are not secure, review
<a href="math-refresher.html#math-refresher">Mathematics Refresher: squares and proportions</a>.</p>
<p>Decide whether each quantity should be small or large for a useful model:
SSE, SSR, and <span class="math inline">\(R^2\)</span>.</p>
<details>
<summary>
Check your preparation
</summary>
<p>For a useful model, SSE should be relatively small, SSR relatively large, and
<span class="math inline">\(R^2\)</span> relatively large. These are comparisons to total outcome variation,
not universal cut-offs.</p>
</details>
</div>
<div id="in-class-16" class="section level2 hasAnchor course-phase phase-in-class">
<h2>In class<a href="i03.html#in-class-16" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p class="concept-video">
<strong>Stanford explanation (review):</strong>
<a href="https://www.youtube.com/watch?v=50sv4UTjE90">3.4 Some Important Questions</a>.
</p>
<div id="three-sums-of-squares" class="section level3 hasAnchor">
<h3>Three sums of squares<a href="i03.html#three-sums-of-squares" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The intercept-only prediction for every observation is <span class="math inline">\(\bar y\)</span>. Regression
compares that baseline with fitted values <span class="math inline">\(\hat y_i\)</span>.</p>
<p><span class="math display">\[
\underbrace{\sum_i(y_i-\bar y)^2}_{\text{SST: total}}
=
\underbrace{\sum_i(\hat y_i-\bar y)^2}_{\text{SSR: explained}}
+
\underbrace{\sum_i(y_i-\hat y_i)^2}_{\text{SSE: residual}}.
\]</span></p>
<p>For ordinary least squares with an intercept,
<span class="math inline">\(\text{SST}=\text{SSR}+\text{SSE}\)</span>.</p>
<div class="sourceCode" id="cb148"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb148-1"><a href="i03.html#cb148-1" tabindex="-1"></a>y <span class="ot">&lt;-</span> deals<span class="sc">$</span>deal_100k</span>
<span id="cb148-2"><a href="i03.html#cb148-2" tabindex="-1"></a>yhat <span class="ot">&lt;-</span> <span class="fu">fitted</span>(deal_model)</span>
<span id="cb148-3"><a href="i03.html#cb148-3" tabindex="-1"></a></span>
<span id="cb148-4"><a href="i03.html#cb148-4" tabindex="-1"></a>SST <span class="ot">&lt;-</span> <span class="fu">sum</span>((y <span class="sc">-</span> <span class="fu">mean</span>(y))<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb148-5"><a href="i03.html#cb148-5" tabindex="-1"></a>SSE <span class="ot">&lt;-</span> <span class="fu">sum</span>((y <span class="sc">-</span> yhat)<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb148-6"><a href="i03.html#cb148-6" tabindex="-1"></a>SSR <span class="ot">&lt;-</span> <span class="fu">sum</span>((yhat <span class="sc">-</span> <span class="fu">mean</span>(y))<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb148-7"><a href="i03.html#cb148-7" tabindex="-1"></a></span>
<span id="cb148-8"><a href="i03.html#cb148-8" tabindex="-1"></a><span class="fu">c</span>(<span class="at">SST =</span> SST, <span class="at">SSR =</span> SSR, <span class="at">SSE =</span> SSE, <span class="at">check =</span> SSR <span class="sc">+</span> SSE)</span></code></pre></div>
<pre><code>##       SST       SSR       SSE     check 
## 10350.932  8044.112  2306.820 10350.932</code></pre>
</div>
<div id="the-coefficient-of-determination" class="section level3 hasAnchor">
<h3>The coefficient of determination<a href="i03.html#the-coefficient-of-determination" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p><span class="math display">\[
R^2=\frac{\text{SSR}}{\text{SST}}
=1-\frac{\text{SSE}}{\text{SST}}.
\]</span></p>
<p>It is the proportion of observed sample variation in <span class="math inline">\(Y\)</span> explained by the
fitted values from the model.</p>
<div class="sourceCode" id="cb150"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb150-1"><a href="i03.html#cb150-1" tabindex="-1"></a><span class="fu">c</span>(</span>
<span id="cb150-2"><a href="i03.html#cb150-2" tabindex="-1"></a>  <span class="at">manual =</span> <span class="dv">1</span> <span class="sc">-</span> SSE <span class="sc">/</span> SST,</span>
<span id="cb150-3"><a href="i03.html#cb150-3" tabindex="-1"></a>  <span class="at">from_R =</span> <span class="fu">summary</span>(deal_model)<span class="sc">$</span>r.squared,</span>
<span id="cb150-4"><a href="i03.html#cb150-4" tabindex="-1"></a>  <span class="at">correlation_squared =</span> <span class="fu">cor</span>(deals<span class="sc">$</span>ask_100k, deals<span class="sc">$</span>deal_100k)<span class="sc">^</span><span class="dv">2</span></span>
<span id="cb150-5"><a href="i03.html#cb150-5" tabindex="-1"></a>)</span></code></pre></div>
<pre><code>##              manual              from_R correlation_squared 
##           0.7771389           0.7771389           0.7771389</code></pre>
<p>Here <span class="math inline">\(R^2\approx0.777\)</span>: about 77.7% of the variation in agreed on-air deal
amount among deal records is explained by its linear association with amount
requested.</p>
<p>In simple linear regression with an intercept, <span class="math inline">\(R^2=r_{XY}^2\)</span>. The sign of
the relationship is lost by squaring; inspect the slope or correlation for
direction.</p>
<p><span class="math inline">\(R^2\)</span> is not:</p>
<ul>
<li>the percentage of predictions that are correct;</li>
<li>proof that assumptions hold;</li>
<li>proof that the predictor causes the outcome;</li>
<li>evidence that the model will perform equally well on new data.</li>
</ul>
</div>
<div id="the-overall-f-test" class="section level3 hasAnchor">
<h3>The overall F-test<a href="i03.html#the-overall-f-test" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>For a regression with <span class="math inline">\(k\)</span> predictors, the overall usefulness test is</p>
<p><span class="math display">\[
H_0:\beta_1=\cdots=\beta_k=0
\]</span></p>
<p>against the alternative that at least one slope is non-zero. The statistic is</p>
<p><span class="math display">\[
F=\frac{\text{SSR}/k}{\text{SSE}/(n-k-1)}.
\]</span></p>
<p>Large <span class="math inline">\(F\)</span> means the explained variation per predictor is large relative to
the residual variation per residual degree of freedom.</p>
<div class="sourceCode" id="cb152"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb152-1"><a href="i03.html#cb152-1" tabindex="-1"></a><span class="fu">summary</span>(deal_model)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = deal_100k ~ ask_100k, data = deals)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -4.3438 -0.3012 -0.2885 -0.2821 28.2115 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  0.27571    0.07241   3.808  0.00015 ***
## ask_100k     1.00851    0.01821  55.395  &lt; 2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 1.619 on 880 degrees of freedom
## Multiple R-squared:  0.7771, Adjusted R-squared:  0.7769 
## F-statistic:  3069 on 1 and 880 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>The output reports <span class="math inline">\(F\approx3069\)</span> on 1 and 880 degrees of freedom, with a
very small p-value. Rejecting the null says the model with requested amount
fits better than an intercept-only model under the inferential conditions.</p>
</div>
<div id="in-simple-regression-f-and-t-answer-the-same-slope-question" class="section level3 hasAnchor">
<h3>In simple regression, F and t answer the same slope question<a href="i03.html#in-simple-regression-f-and-t-answer-the-same-slope-question" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>With one predictor and a two-sided alternative,</p>
<p><span class="math display">\[
F=t^2.
\]</span></p>
<div class="sourceCode" id="cb154"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb154-1"><a href="i03.html#cb154-1" tabindex="-1"></a>t_slope <span class="ot">&lt;-</span> <span class="fu">summary</span>(deal_model)<span class="sc">$</span>coefficients[<span class="st">&quot;ask_100k&quot;</span>, <span class="st">&quot;t value&quot;</span>]</span>
<span id="cb154-2"><a href="i03.html#cb154-2" tabindex="-1"></a>f_model <span class="ot">&lt;-</span> <span class="fu">unname</span>(<span class="fu">summary</span>(deal_model)<span class="sc">$</span>fstatistic[<span class="st">&quot;value&quot;</span>])</span>
<span id="cb154-3"><a href="i03.html#cb154-3" tabindex="-1"></a><span class="fu">c</span>(<span class="at">t_squared =</span> t_slope<span class="sc">^</span><span class="dv">2</span>, <span class="at">F =</span> f_model)</span></code></pre></div>
<pre><code>## t_squared         F 
##  3068.648  3068.648</code></pre>
<p>This equivalence disappears when a multiple-regression F-test evaluates
several slopes jointly.</p>
</div>
<div id="usefulness-has-more-than-one-meaning" class="section level3 hasAnchor">
<h3>Usefulness has more than one meaning<a href="i03.html#usefulness-has-more-than-one-meaning" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>A model can have:</p>
<ul>
<li>a statistically non-zero slope but low <span class="math inline">\(R^2\)</span>;</li>
<li>high <span class="math inline">\(R^2\)</span> but poor causal interpretation;</li>
<li>good in-sample fit but fragile predictions outside the observed data;</li>
<li>accurate predictions but coefficients that do not support a structural
explanation.</li>
</ul>
<p>Always align the evaluation with the goal: explanation, prediction, or
decision support.</p>
</div>
<div id="read-the-complete-r-summary" class="section level3 hasAnchor">
<h3>Read the complete R summary<a href="i03.html#read-the-complete-r-summary" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div class="sourceCode" id="cb156"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb156-1"><a href="i03.html#cb156-1" tabindex="-1"></a><span class="fu">summary</span>(deal_model)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = deal_100k ~ ask_100k, data = deals)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -4.3438 -0.3012 -0.2885 -0.2821 28.2115 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  0.27571    0.07241   3.808  0.00015 ***
## ask_100k     1.00851    0.01821  55.395  &lt; 2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 1.619 on 880 degrees of freedom
## Multiple R-squared:  0.7771, Adjusted R-squared:  0.7769 
## F-statistic:  3069 on 1 and 880 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>Read it in this order:</p>
<ol style="list-style-type: decimal">
<li>formula and analysis sample;</li>
<li>coefficient estimates and units;</li>
<li>standard errors, t statistics, and p-values;</li>
<li>residual scale;</li>
<li><span class="math inline">\(R^2\)</span> and adjusted <span class="math inline">\(R^2\)</span>;</li>
<li>overall F-test;</li>
<li>assumptions and design limits outside the printed table.</li>
</ol>
</div>
</div>
<div id="after-class-16" class="section level2 hasAnchor course-phase phase-after">
<h2>After class<a href="i03.html#after-class-16" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="retrieval-11" class="section level3 hasAnchor">
<h3>Retrieval<a href="i03.html#retrieval-11" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<ol style="list-style-type: decimal">
<li>What do SST, SSR, and SSE measure?</li>
<li>Why is <span class="math inline">\(R^2\)</span> between 0 and 1 in an OLS model with an intercept?</li>
<li>What is the null hypothesis of the overall F-test?</li>
<li>Why do the simple-regression slope t-test and F-test agree?</li>
<li>Why can a high <span class="math inline">\(R^2\)</span> coexist with a weak causal claim?</li>
</ol>
<details>
<summary>
Check your answers
</summary>
<ol style="list-style-type: decimal">
<li>Total, fitted/explained, and residual sample variation in the outcome.</li>
<li>SSE is non-negative and no larger than SST for that model, so
<span class="math inline">\(1-\text{SSE}/\text{SST}\)</span> lies from 0 to 1.</li>
<li>All population slope coefficients equal zero.</li>
<li>With one predictor, both test <span class="math inline">\(H_0:\beta_1=0\)</span>, and <span class="math inline">\(F=t^2\)</span>.</li>
<li>Fit measures association in the observed data; causality depends on design
and assumptions about confounding and selection.</li>
</ol>
</details>
</div>
<div id="practice-11" class="section level3 hasAnchor">
<h3>Practice<a href="i03.html#practice-11" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<ol style="list-style-type: decimal">
<li>If SST = 500 and SSE = 125, calculate SSR and <span class="math inline">\(R^2\)</span>.</li>
<li>Interpret <span class="math inline">\(R^2=0.20\)</span> without calling the model “80% wrong.”</li>
<li>A model has <span class="math inline">\(k=3\)</span>, <span class="math inline">\(n=104\)</span>, SSR = 300, and SSE = 500. Calculate F.</li>
<li>Explain why adding a predictor cannot increase training SSE in OLS.</li>
<li>Read <code>summary(lm(equity_offered_pct ~ season, data = sharks))</code>: report the
slope, <span class="math inline">\(R^2\)</span>, F-test conclusion, and causal boundary.</li>
</ol>
<details>
<summary>
Check your answers
</summary>
<ol style="list-style-type: decimal">
<li>SSR = 375 and <span class="math inline">\(R^2=375/500=0.75\)</span>.</li>
<li>The fitted values explain 20% of observed outcome variation; 80% remains in
residual variation around the fitted line.</li>
<li><span class="math inline">\(F=(300/3)/(500/(104-3-1))=100/5=20\)</span>.</li>
<li>The expanded model can reproduce the old fit by assigning the new slope
zero, so least squares cannot find a worse minimum SSE.</li>
<li>The slope is about <span class="math inline">\(-0.824\)</span> percentage points per season,
<span class="math inline">\(R^2\approx0.173\)</span>, and the overall F-test rejects a zero slope. The
observational time trend does not establish a causal effect of season.</li>
</ol>
</details>
<p>Continue to <a href="i-ep01.html#i-ep01">Tutorial 1: Simple regression and model usefulness</a>.</p>
<p>For a more formal treatment, see James et al., <em>An Introduction to Statistical
Learning</em>, 2nd ed., Section 3.1.3, and
<a href="https://tilburguniversity.on.worldcat.org/oclc/317545871">Nieuwenhuis, <em>Statistical Methods for Business and Economics</em></a>,
Chapters 19–20.</p>
</div>
</div>

</div>
            </section>

          </div>
        </div>
      </div>
<a href="i02.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="i-ep01.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
  "sharing": null,
  "fontsettings": {
    "theme": "white",
    "family": "sans",
    "size": 2
  },
  "edit": null,
  "history": {
    "link": null,
    "text": null
  },
  "view": {
    "link": null,
    "text": null
  },
  "download": null,
  "search": {
    "engine": "fuse",
    "options": null
  },
  "toc": {
    "collapse": "section",
    "scroll_highlight": true
  },
  "toolbar": {
    "position": "fixed"
  }
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
