<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Lecture 4: Multiple linear regression and controls | Online Textbook for the Learning Line “Quantitative Methods to Understand E&amp;BI”</title>
  <meta name="description" content="An online textbook for the learning line Quantitative Methods within Entrepreneurship and Business Innovation Bachelor Program at Tilburg University." />
  <meta name="generator" content="bookdown 0.47 and GitBook 2.6.7" />

  <meta property="og:title" content="Lecture 4: Multiple linear regression and controls | Online Textbook for the Learning Line “Quantitative Methods to Understand E&amp;BI”" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="An online textbook for the learning line Quantitative Methods within Entrepreneurship and Business Innovation Bachelor Program at Tilburg University." />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Lecture 4: Multiple linear regression and controls | Online Textbook for the Learning Line “Quantitative Methods to Understand E&amp;BI”" />
  
  <meta name="twitter:description" content="An online textbook for the learning line Quantitative Methods within Entrepreneurship and Business Innovation Bachelor Program at Tilburg University." />
  




  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="i-ep01.html"/>
<link rel="next" href="i05.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

<link rel="stylesheet" href="styles.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="book-title"><a href="./">QM to Understand E&amp;BI</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Welcome</a></li>
<li class="part"><span><b>I QM Basic</b></span></li>
<li class="chapter" data-level="" data-path="basic-course.html"><a href="basic-course.html"><i class="fa fa-check"></i>QM Basic: Course overview</a></li>
<li class="chapter" data-level="" data-path="b01.html"><a href="b01.html"><i class="fa fa-check"></i>Lecture 1: Introduction to Data Analysis</a></li>
<li class="chapter" data-level="" data-path="b02.html"><a href="b02.html"><i class="fa fa-check"></i>Lecture 2: Probability foundations and random variables</a></li>
<li class="chapter" data-level="" data-path="b03.html"><a href="b03.html"><i class="fa fa-check"></i>Lecture 3: Discrete distributions and expectation</a></li>
<li class="chapter" data-level="" data-path="b-ep01.html"><a href="b-ep01.html"><i class="fa fa-check"></i>Tutorial 1: Evidence and probability foundations</a></li>
<li class="chapter" data-level="" data-path="b04.html"><a href="b04.html"><i class="fa fa-check"></i>Lecture 4: Variance, conditioning, and belief updating</a></li>
<li class="chapter" data-level="" data-path="b05.html"><a href="b05.html"><i class="fa fa-check"></i>Lecture 5: Joint random variables, covariance, and correlation</a></li>
<li class="chapter" data-level="" data-path="b-ep02.html"><a href="b-ep02.html"><i class="fa fa-check"></i>Tutorial 2: Conditioning and relationships</a></li>
<li class="chapter" data-level="" data-path="b06.html"><a href="b06.html"><i class="fa fa-check"></i>Lecture 6: Continuous distributions and the normal model</a></li>
<li class="chapter" data-level="" data-path="b07.html"><a href="b07.html"><i class="fa fa-check"></i>Lecture 7: Samples, parameters, and estimators</a></li>
<li class="chapter" data-level="" data-path="b08.html"><a href="b08.html"><i class="fa fa-check"></i>Lecture 8: Sampling distributions and the central limit theorem</a></li>
<li class="chapter" data-level="" data-path="b-ep03.html"><a href="b-ep03.html"><i class="fa fa-check"></i>Tutorial 3: Sampling and standard errors</a></li>
<li class="chapter" data-level="" data-path="b09.html"><a href="b09.html"><i class="fa fa-check"></i>Lecture 9: Confidence intervals and tests against zero</a></li>
<li class="chapter" data-level="" data-path="b10.html"><a href="b10.html"><i class="fa fa-check"></i>Lecture 10: Hypothesis testing, errors, and power</a></li>
<li class="chapter" data-level="" data-path="b-ep04.html"><a href="b-ep04.html"><i class="fa fa-check"></i>Tutorial 4: Inference and tests against zero</a></li>
<li class="chapter" data-level="" data-path="formula-sheet.html"><a href="formula-sheet.html"><i class="fa fa-check"></i>QM Basic Formula Sheet</a></li>
<li class="chapter" data-level="" data-path="basic-mock-exam.html"><a href="basic-mock-exam.html"><i class="fa fa-check"></i>Mock Exam: QM Basic</a></li>
<li class="part"><span><b>II QM Intermediate</b></span></li>
<li class="chapter" data-level="" data-path="intermediate-course.html"><a href="intermediate-course.html"><i class="fa fa-check"></i>QM Intermediate: Course overview</a></li>
<li class="chapter" data-level="" data-path="i01.html"><a href="i01.html"><i class="fa fa-check"></i>Lecture 1: Simple linear regression</a></li>
<li class="chapter" data-level="" data-path="i02.html"><a href="i02.html"><i class="fa fa-check"></i>Lecture 2: Regression assumptions and coefficient inference</a></li>
<li class="chapter" data-level="" data-path="i03.html"><a href="i03.html"><i class="fa fa-check"></i>Lecture 3: Model fit and overall usefulness</a></li>
<li class="chapter" data-level="" data-path="i-ep01.html"><a href="i-ep01.html"><i class="fa fa-check"></i>Tutorial 1: Simple regression and model usefulness</a></li>
<li class="chapter" data-level="" data-path="i04.html"><a href="i04.html"><i class="fa fa-check"></i>Lecture 4: Multiple linear regression and controls</a></li>
<li class="chapter" data-level="" data-path="i05.html"><a href="i05.html"><i class="fa fa-check"></i>Lecture 5: Dummy predictors and joint usefulness</a></li>
<li class="chapter" data-level="" data-path="i06.html"><a href="i06.html"><i class="fa fa-check"></i>Lecture 6: Interactions and polynomial terms</a></li>
<li class="chapter" data-level="" data-path="i-ep02.html"><a href="i-ep02.html"><i class="fa fa-check"></i>Tutorial 2: Multiple regression and extensions</a></li>
<li class="chapter" data-level="" data-path="intermediate-code-sheet.html"><a href="intermediate-code-sheet.html"><i class="fa fa-check"></i>QM Intermediate Code Sheet</a></li>
<li class="chapter" data-level="" data-path="intermediate-mock-exam.html"><a href="intermediate-mock-exam.html"><i class="fa fa-check"></i>Mock Exam: QM Intermediate</a></li>
<li class="part"><span><b>III QM Advanced</b></span></li>
<li class="chapter" data-level="" data-path="advanced-course.html"><a href="advanced-course.html"><i class="fa fa-check"></i>QM Advanced: Course overview</a></li>
<li class="part"><span><b>IV Supplementary resources</b></span></li>
<li class="chapter" data-level="" data-path="r-refresher.html"><a href="r-refresher.html"><i class="fa fa-check"></i>R Refresher</a></li>
<li class="chapter" data-level="" data-path="math-refresher.html"><a href="math-refresher.html"><i class="fa fa-check"></i>Mathematics Refresher</a></li>
<li class="chapter" data-level="" data-path="videos.html"><a href="videos.html"><i class="fa fa-check"></i>External Video Guide</a></li>
<li class="divider"></li>
<li class="book-footer">Quantitative Methods learning line</li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Online Textbook for the Learning Line “Quantitative Methods to Understand E&amp;BI”</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="i04" class="section level1 hasAnchor">
<h1>Lecture 4: Multiple linear regression and controls<a href="i04.html#i04" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<div class="outcomes">
<span class="label">By the end of Lecture 4, you can</span>
<ul>
<li>
state a multiple linear regression model;
</li>
<li>
interpret a coefficient while holding the other included predictors fixed;
</li>
<li>
explain why simple and multiple-regression coefficients can differ;
</li>
<li>
fit and compare multiple-regression specifications in R;
</li>
<li>
distinguish statistical control from causal identification.
</li>
</ul>
</div>
<div id="before-class-18" class="section level2 hasAnchor course-phase phase-before">
<h2>Before class<a href="i04.html#before-class-18" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div class="video-prep">
<p><span class="label">Video preparation</span><br>
Watch Stanford Statistical Learning
<a href="https://www.youtube.com/watch?v=o9hoLdylWKo&list=PLoROMvodv4rOzrYsAxzQyHb8n_RWNuS1e&index=11">3.3
Multiple Linear Regression</a>. Focus on the conditional interpretation of one
coefficient and the reason several predictors may be included together.</p>
</div>
<p>Review <a href="math-refresher.html#math-refresher">Mathematics Refresher: subscripts and multivariable equations</a>
if needed.</p>
<p>Why might the simple slope from <code>equity_offered_pct ~ season</code> differ after
amount requested is added to the model?</p>
<details>
<summary>
Check your preparation
</summary>
<p>If requested amount is associated with both season and offered equity, the
simple slope mixes their relationships. Multiple regression compares seasons
at the same included request amount, so its coefficient can differ.</p>
</details>
</div>
<div id="in-class-18" class="section level2 hasAnchor course-phase phase-in-class">
<h2>In class<a href="i04.html#in-class-18" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p class="concept-video">
<strong>Stanford explanation (review):</strong>
<a href="https://www.youtube.com/watch?v=o9hoLdylWKo">3.3 Multiple Linear Regression</a>.
</p>
<div id="more-than-one-predictor" class="section level3 hasAnchor">
<h3>More than one predictor<a href="i04.html#more-than-one-predictor" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>For predictors <span class="math inline">\(X_{i1},\ldots,X_{ik}\)</span>, the model is</p>
<p><span class="math display">\[
Y_i=\beta_0+\beta_1X_{i1}+\cdots+\beta_kX_{ik}+\varepsilon_i,
\]</span></p>
<p>with conditional mean</p>
<p><span class="math display">\[
E[Y_i\mid X_{i1}=x_1,\ldots,X_{ik}=x_k]
=\beta_0+\beta_1x_1+\cdots+\beta_kx_k.
\]</span></p>
<p>The coefficient <span class="math inline">\(\beta_j\)</span> is the expected change in <span class="math inline">\(Y\)</span> for a one-unit
increase in <span class="math inline">\(X_j\)</span>, <strong>holding the other included predictors fixed</strong>.</p>
<p>This is a model-based comparison. It does not require that two real pitches
are identical on every feature; it compares fitted conditional means at fixed
values of the included variables.</p>
</div>
<div id="a-shark-tank-model" class="section level3 hasAnchor">
<h3>A Shark Tank model<a href="i04.html#a-shark-tank-model" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Let the outcome be initial equity offered, in percentage points. Include:</p>
<ul>
<li><code>season</code>;</li>
<li><code>ask_100k</code>, requested dollars divided by 100,000;</li>
<li><code>description_words</code>, the number of words in the source’s short description.</li>
</ul>
<div class="sourceCode" id="cb160"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb160-1"><a href="i04.html#cb160-1" tabindex="-1"></a>equity_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(</span>
<span id="cb160-2"><a href="i04.html#cb160-2" tabindex="-1"></a>  equity_offered_pct <span class="sc">~</span> season <span class="sc">+</span> ask_100k <span class="sc">+</span> description_words,</span>
<span id="cb160-3"><a href="i04.html#cb160-3" tabindex="-1"></a>  <span class="at">data =</span> sharks</span>
<span id="cb160-4"><a href="i04.html#cb160-4" tabindex="-1"></a>)</span>
<span id="cb160-5"><a href="i04.html#cb160-5" tabindex="-1"></a><span class="fu">summary</span>(equity_model)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = equity_offered_pct ~ season + ask_100k + description_words, 
##     data = sharks)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -15.295  -4.776  -1.283   3.288  82.106 
## 
## Coefficients:
##                   Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)       22.02493    0.88785  24.807  &lt; 2e-16 ***
## season            -0.83615    0.05098 -16.401  &lt; 2e-16 ***
## ask_100k          -0.28975    0.05771  -5.021 5.79e-07 ***
## description_words -0.12834    0.11375  -1.128    0.259    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 7.619 on 1437 degrees of freedom
## Multiple R-squared:  0.1876, Adjusted R-squared:  0.1859 
## F-statistic: 110.6 on 3 and 1437 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>The fitted equation is approximately</p>
<p><span class="math display">\[
\widehat{equity}
=22.025-0.836\,season-0.290\,ask_{100k}
-0.128\,description\_words.
\]</span></p>
<p>Interpret each slope conditionally:</p>
<ul>
<li>At the same requested amount and description length, one later season is
associated with 0.836 percentage points less initial equity offered.</li>
<li>At the same season and description length, an additional $100,000 requested
is associated with 0.290 percentage points less initial equity offered.</li>
<li>At the same season and request, one additional description word is
associated with 0.128 percentage points less initial equity offered.</li>
</ul>
<p>The last estimate is not statistically distinguishable from zero at 5% in the
classical summary. Its point estimate should still be reported; “not
significant” is not the same as “exactly zero.”</p>
</div>
<div id="a-coefficient-interpretation-protocol" class="section level3 hasAnchor">
<h3>A coefficient-interpretation protocol<a href="i04.html#a-coefficient-interpretation-protocol" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Use the same five checks every time you interpret a slope:</p>
<ol style="list-style-type: decimal">
<li><strong>Estimate and direction:</strong> state the fitted change and its sign.</li>
<li><strong>Predictor step and unit:</strong> say what a one-unit increase means.</li>
<li><strong>Outcome unit:</strong> state the unit in which the outcome changes.</li>
<li><strong>Conditioning:</strong> name the other included predictors being held fixed.</li>
<li><strong>Scope:</strong> identify the analysed records and say “associated with” unless a
research design justifies a causal claim.</li>
</ol>
<p>The variables in this model use deliberately different units:</p>
<table>
<colgroup>
<col width="33%" />
<col width="33%" />
<col width="33%" />
</colgroup>
<thead>
<tr class="header">
<th>Term</th>
<th>A one-unit increase means</th>
<th>Coefficient unit</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>season</code></td>
<td>one later season</td>
<td>equity percentage points per season</td>
</tr>
<tr class="even">
<td><code>ask_100k</code></td>
<td>$100,000 more requested</td>
<td>equity percentage points per $100,000</td>
</tr>
<tr class="odd">
<td><code>description_words</code></td>
<td>one additional word</td>
<td>equity percentage points per word</td>
</tr>
</tbody>
</table>
<p>Scale the coefficient to the comparison readers care about. Holding the other
included predictors fixed:</p>
<ul>
<li>five later seasons correspond to
<span class="math inline">\(5(-0.836)=-4.18\)</span> fitted equity percentage points;</li>
<li>$500,000 more requested is five <code>ask_100k</code> units, corresponding to
<span class="math inline">\(5(-0.290)=-1.45\)</span> percentage points;</li>
<li>ten additional description words correspond to
<span class="math inline">\(10(-0.128)=-1.28\)</span> percentage points.</li>
</ul>
<p>Rescaling a predictor changes the numerical coefficient and its SE but not the
fitted values, t statistic, or substantive relationship. Reporting a tiny
“per dollar” coefficient would be correct but hard to read; $100,000 units make
the same model interpretable.</p>
</div>
<div id="why-coefficients-change" class="section level3 hasAnchor">
<h3>Why coefficients change<a href="i04.html#why-coefficients-change" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Compare the season slope across specifications:</p>
<div class="sourceCode" id="cb162"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb162-1"><a href="i04.html#cb162-1" tabindex="-1"></a>m_simple <span class="ot">&lt;-</span> <span class="fu">lm</span>(equity_offered_pct <span class="sc">~</span> season, <span class="at">data =</span> sharks)</span>
<span id="cb162-2"><a href="i04.html#cb162-2" tabindex="-1"></a>m_adjusted <span class="ot">&lt;-</span> <span class="fu">lm</span>(equity_offered_pct <span class="sc">~</span> season <span class="sc">+</span> ask_100k,</span>
<span id="cb162-3"><a href="i04.html#cb162-3" tabindex="-1"></a>                 <span class="at">data =</span> sharks)</span>
<span id="cb162-4"><a href="i04.html#cb162-4" tabindex="-1"></a>m_full <span class="ot">&lt;-</span> equity_model</span>
<span id="cb162-5"><a href="i04.html#cb162-5" tabindex="-1"></a></span>
<span id="cb162-6"><a href="i04.html#cb162-6" tabindex="-1"></a><span class="fu">c</span>(</span>
<span id="cb162-7"><a href="i04.html#cb162-7" tabindex="-1"></a>  <span class="at">simple =</span> <span class="fu">coef</span>(m_simple)[<span class="st">&quot;season&quot;</span>],</span>
<span id="cb162-8"><a href="i04.html#cb162-8" tabindex="-1"></a>  <span class="at">adjusted_for_ask =</span> <span class="fu">coef</span>(m_adjusted)[<span class="st">&quot;season&quot;</span>],</span>
<span id="cb162-9"><a href="i04.html#cb162-9" tabindex="-1"></a>  <span class="at">adjusted_for_ask_and_words =</span> <span class="fu">coef</span>(m_full)[<span class="st">&quot;season&quot;</span>]</span>
<span id="cb162-10"><a href="i04.html#cb162-10" tabindex="-1"></a>)</span></code></pre></div>
<pre><code>##                     simple.season           adjusted_for_ask.season 
##                        -0.8241241                        -0.8143307 
## adjusted_for_ask_and_words.season 
##                        -0.8361515</code></pre>
<p>A coefficient changes when added predictors account for variation that was
previously absorbed into the simpler association. The change is informative,
but it does not prove that the larger model is causal or “correct.”</p>
</div>
<div id="control-variables-useful-but-not-magical" class="section level3 hasAnchor">
<h3>Control variables: useful but not magical<a href="i04.html#control-variables-useful-but-not-magical" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Including a control can:</p>
<ul>
<li>make a comparison more like-for-like on measured dimensions;</li>
<li>reduce residual variation;</li>
<li>reveal that a simple association was partly compositional;</li>
<li>increase uncertainty when predictors overlap strongly.</li>
</ul>
<p>It cannot automatically control for unmeasured factors, reverse causality,
selection into the sample, or measurement error. A “control variable” is just
an included predictor unless the research design and assumptions justify a
causal role.</p>
</div>
<div id="assumptions-extend-to-the-full-predictor-set" class="section level3 hasAnchor">
<h3>Assumptions extend to the full predictor set<a href="i04.html#assumptions-extend-to-the-full-predictor-set" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>For multiple regression, check:</p>
<ol style="list-style-type: decimal">
<li>the conditional mean is linear in included terms;</li>
<li><span class="math inline">\(E[\varepsilon_i\mid X_{i1},\ldots,X_{ik}]=0\)</span>;</li>
<li>observations are independent under the design;</li>
<li>no predictor is an exact linear combination of the others;</li>
<li>classical SEs require constant conditional error variance;</li>
<li>exact small-sample t/F inference uses conditional normality.</li>
</ol>
<p>High correlation among predictors does not bias OLS by itself, but it can make
individual coefficients unstable and imprecise. Exact linear dependence makes
the coefficients unidentified.</p>
</div>
<div id="a-coefficient-plot-keeps-units-visible" class="section level3 hasAnchor">
<h3>A coefficient plot keeps units visible<a href="i04.html#a-coefficient-plot-keeps-units-visible" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p><img src="I04-multiple-regression_files/figure-html/i04-coefficient-plot-1.png" width="672" /></p>
<p>The horizontal axis is the estimated change in initial equity, in percentage
points, for the one-unit predictor step named on each row. A dot is the
coefficient estimate; its horizontal line is the 95% confidence interval; the
dashed vertical line marks zero. Each row uses a different predictor unit, so
coefficient magnitudes are not directly comparable without considering those
units.</p>
</div>
</div>
<div id="after-class-18" class="section level2 hasAnchor course-phase phase-after">
<h2>After class<a href="i04.html#after-class-18" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="retrieval-12" class="section level3 hasAnchor">
<h3>Retrieval<a href="i04.html#retrieval-12" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<ol style="list-style-type: decimal">
<li>What phrase must appear in a multiple-regression slope interpretation?</li>
<li>Why can a coefficient change after another predictor is added?</li>
<li>What is the zero conditional mean assumption?</li>
<li>Why do controls not automatically identify causality?</li>
<li>What problem can strongly overlapping predictors create?</li>
<li>What five elements belong in a slope interpretation?</li>
</ol>
<details>
<summary>
Check your answers
</summary>
<ol style="list-style-type: decimal">
<li>“Holding the other included predictors fixed.”</li>
<li>The simpler slope may combine relationships involving omitted correlated
predictors.</li>
<li>The error has mean zero at every combination of included predictor values.</li>
<li>Unmeasured confounding, selection, reverse causality, and measurement error
can remain.</li>
<li>Unstable, imprecise individual coefficient estimates; exact overlap makes
the model unidentified.</li>
<li>Estimate and direction, predictor step and unit, outcome unit, held-fixed
predictors, and the sample/causal scope.</li>
</ol>
</details>
</div>
<div id="practice-12" class="section level3 hasAnchor">
<h3>Practice<a href="i04.html#practice-12" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<ol style="list-style-type: decimal">
<li>Interpret all three slopes from <code>equity_model</code> with units and conditioning.</li>
<li>Calculate 95% confidence intervals with <code>confint(equity_model)</code>.</li>
<li>Test each coefficient against zero and distinguish three individual tests
from one joint model test.</li>
<li>Remove <code>description_words</code>. Compare the season and request coefficients.</li>
<li>Name one plausible omitted variable and explain which model assumption it
could threaten.</li>
<li>Interpret a five-season difference using the fitted season coefficient.</li>
<li>Interpret a $500,000 difference in requested amount.</li>
<li>Interpret a ten-word difference in description length and use its 95%
interval to assess <span class="math inline">\(H_0:\beta=0\)</span>.</li>
<li>Compare two otherwise identical fitted pitches when one is three seasons
later and requests $200,000 more. Calculate the combined fitted difference.</li>
</ol>
<details>
<summary>
Check your answers
</summary>
<ol style="list-style-type: decimal">
<li>Holding the other two predictors fixed: one later season is associated with
0.836 percentage points less equity; another $100,000 requested with 0.290
percentage points less equity; and one additional description word with
0.128 percentage points less equity.</li>
<li>The season interval is approximately <span class="math inline">\((-0.936, -0.736)\)</span>, the request interval
<span class="math inline">\((-0.403, -0.177)\)</span>, and the description interval <span class="math inline">\((-0.351, 0.095)\)</span>.</li>
<li>Individual t-tests evaluate one <span class="math inline">\(\beta_j=0\)</span>; the overall F-test evaluates
all slope coefficients jointly.</li>
<li>Without <code>description_words</code>, the season coefficient is about <span class="math inline">\(-0.814\)</span> and
the request coefficient about <span class="math inline">\(-0.287\)</span>. They change only slightly here;
that empirical stability does not prove absence of omitted-variable bias.</li>
<li>Examples include venture maturity, revenue, founder experience, or editing
decisions; if related to both an included predictor and offered equity, it
threatens zero conditional mean.</li>
<li>Holding request and description length fixed, a pitch five seasons later is
fitted to offer about <span class="math inline">\(5(-0.836)=-4.18\)</span> equity percentage points.</li>
<li>$500,000 equals five predictor units. Holding season and description length
fixed, the fitted difference is <span class="math inline">\(5(-0.290)=-1.45\)</span> percentage points.</li>
<li>Ten words correspond to about <span class="math inline">\(-1.28\)</span> fitted percentage points, holding
season and request fixed. Multiplying its interval by 10 gives approximately
<span class="math inline">\((-3.51,0.95)\)</span>; because zero remains plausible, the two-sided 5% test does
not reject a zero coefficient.</li>
<li>The fitted difference is
<span class="math inline">\(3(-0.836)+2(-0.290)\approx-3.09\)</span> percentage points, holding description
length fixed. Add coefficient contributions because the model is additive.</li>
</ol>
</details>
<p>Continue to <a href="i05.html#i05">Lecture 5: Dummy predictors and joint usefulness</a>.</p>
<p>For a more formal treatment, see James et al., <em>An Introduction to Statistical
Learning</em>, 2nd ed., Sections 3.2 and 3.3.3, and
<a href="https://tilburguniversity.on.worldcat.org/oclc/317545871">Nieuwenhuis, <em>Statistical Methods for Business and Economics</em></a>,
Chapter 20.</p>
</div>
</div>

</div>
            </section>

          </div>
        </div>
      </div>
<a href="i-ep01.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="i05.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
  "sharing": null,
  "fontsettings": {
    "theme": "white",
    "family": "sans",
    "size": 2
  },
  "edit": null,
  "history": {
    "link": null,
    "text": null
  },
  "view": {
    "link": null,
    "text": null
  },
  "download": null,
  "search": {
    "engine": "fuse",
    "options": null
  },
  "toc": {
    "collapse": "section",
    "scroll_highlight": true
  },
  "toolbar": {
    "position": "fixed"
  }
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
