<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Lecture 5: Dummy predictors and joint usefulness | Online Textbook for the Learning Line “Quantitative Methods to Understand E&amp;BI”</title>
  <meta name="description" content="An online textbook for the learning line Quantitative Methods within Entrepreneurship and Business Innovation Bachelor Program at Tilburg University." />
  <meta name="generator" content="bookdown 0.47 and GitBook 2.6.7" />

  <meta property="og:title" content="Lecture 5: Dummy predictors and joint usefulness | Online Textbook for the Learning Line “Quantitative Methods to Understand E&amp;BI”" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="An online textbook for the learning line Quantitative Methods within Entrepreneurship and Business Innovation Bachelor Program at Tilburg University." />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Lecture 5: Dummy predictors and joint usefulness | Online Textbook for the Learning Line “Quantitative Methods to Understand E&amp;BI”" />
  
  <meta name="twitter:description" content="An online textbook for the learning line Quantitative Methods within Entrepreneurship and Business Innovation Bachelor Program at Tilburg University." />
  




  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="i04.html"/>
<link rel="next" href="i06.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

<link rel="stylesheet" href="styles.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="book-title"><a href="./">QM to Understand E&amp;BI</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Welcome</a></li>
<li class="part"><span><b>I QM Basic</b></span></li>
<li class="chapter" data-level="" data-path="basic-course.html"><a href="basic-course.html"><i class="fa fa-check"></i>QM Basic: Course overview</a></li>
<li class="chapter" data-level="" data-path="b01.html"><a href="b01.html"><i class="fa fa-check"></i>Lecture 1: Introduction to Data Analysis</a></li>
<li class="chapter" data-level="" data-path="b02.html"><a href="b02.html"><i class="fa fa-check"></i>Lecture 2: Probability foundations and random variables</a></li>
<li class="chapter" data-level="" data-path="b03.html"><a href="b03.html"><i class="fa fa-check"></i>Lecture 3: Discrete distributions and expectation</a></li>
<li class="chapter" data-level="" data-path="b-ep01.html"><a href="b-ep01.html"><i class="fa fa-check"></i>Tutorial 1: Evidence and probability foundations</a></li>
<li class="chapter" data-level="" data-path="b04.html"><a href="b04.html"><i class="fa fa-check"></i>Lecture 4: Variance, conditioning, and belief updating</a></li>
<li class="chapter" data-level="" data-path="b05.html"><a href="b05.html"><i class="fa fa-check"></i>Lecture 5: Joint random variables, covariance, and correlation</a></li>
<li class="chapter" data-level="" data-path="b-ep02.html"><a href="b-ep02.html"><i class="fa fa-check"></i>Tutorial 2: Conditioning and relationships</a></li>
<li class="chapter" data-level="" data-path="b06.html"><a href="b06.html"><i class="fa fa-check"></i>Lecture 6: Continuous distributions and the normal model</a></li>
<li class="chapter" data-level="" data-path="b07.html"><a href="b07.html"><i class="fa fa-check"></i>Lecture 7: Samples, parameters, and estimators</a></li>
<li class="chapter" data-level="" data-path="b08.html"><a href="b08.html"><i class="fa fa-check"></i>Lecture 8: Sampling distributions and the central limit theorem</a></li>
<li class="chapter" data-level="" data-path="b-ep03.html"><a href="b-ep03.html"><i class="fa fa-check"></i>Tutorial 3: Sampling and standard errors</a></li>
<li class="chapter" data-level="" data-path="b09.html"><a href="b09.html"><i class="fa fa-check"></i>Lecture 9: Confidence intervals and tests against zero</a></li>
<li class="chapter" data-level="" data-path="b10.html"><a href="b10.html"><i class="fa fa-check"></i>Lecture 10: Hypothesis testing, errors, and power</a></li>
<li class="chapter" data-level="" data-path="b-ep04.html"><a href="b-ep04.html"><i class="fa fa-check"></i>Tutorial 4: Inference and tests against zero</a></li>
<li class="chapter" data-level="" data-path="formula-sheet.html"><a href="formula-sheet.html"><i class="fa fa-check"></i>QM Basic Formula Sheet</a></li>
<li class="chapter" data-level="" data-path="basic-mock-exam.html"><a href="basic-mock-exam.html"><i class="fa fa-check"></i>Mock Exam: QM Basic</a></li>
<li class="part"><span><b>II QM Intermediate</b></span></li>
<li class="chapter" data-level="" data-path="intermediate-course.html"><a href="intermediate-course.html"><i class="fa fa-check"></i>QM Intermediate: Course overview</a></li>
<li class="chapter" data-level="" data-path="i01.html"><a href="i01.html"><i class="fa fa-check"></i>Lecture 1: Simple linear regression</a></li>
<li class="chapter" data-level="" data-path="i02.html"><a href="i02.html"><i class="fa fa-check"></i>Lecture 2: Regression assumptions and coefficient inference</a></li>
<li class="chapter" data-level="" data-path="i03.html"><a href="i03.html"><i class="fa fa-check"></i>Lecture 3: Model fit and overall usefulness</a></li>
<li class="chapter" data-level="" data-path="i-ep01.html"><a href="i-ep01.html"><i class="fa fa-check"></i>Tutorial 1: Simple regression and model usefulness</a></li>
<li class="chapter" data-level="" data-path="i04.html"><a href="i04.html"><i class="fa fa-check"></i>Lecture 4: Multiple linear regression and controls</a></li>
<li class="chapter" data-level="" data-path="i05.html"><a href="i05.html"><i class="fa fa-check"></i>Lecture 5: Dummy predictors and joint usefulness</a></li>
<li class="chapter" data-level="" data-path="i06.html"><a href="i06.html"><i class="fa fa-check"></i>Lecture 6: Interactions and polynomial terms</a></li>
<li class="chapter" data-level="" data-path="i-ep02.html"><a href="i-ep02.html"><i class="fa fa-check"></i>Tutorial 2: Multiple regression and extensions</a></li>
<li class="chapter" data-level="" data-path="intermediate-code-sheet.html"><a href="intermediate-code-sheet.html"><i class="fa fa-check"></i>QM Intermediate Code Sheet</a></li>
<li class="chapter" data-level="" data-path="intermediate-mock-exam.html"><a href="intermediate-mock-exam.html"><i class="fa fa-check"></i>Mock Exam: QM Intermediate</a></li>
<li class="part"><span><b>III QM Advanced</b></span></li>
<li class="chapter" data-level="" data-path="advanced-course.html"><a href="advanced-course.html"><i class="fa fa-check"></i>QM Advanced: Course overview</a></li>
<li class="part"><span><b>IV Supplementary resources</b></span></li>
<li class="chapter" data-level="" data-path="r-refresher.html"><a href="r-refresher.html"><i class="fa fa-check"></i>R Refresher</a></li>
<li class="chapter" data-level="" data-path="math-refresher.html"><a href="math-refresher.html"><i class="fa fa-check"></i>Mathematics Refresher</a></li>
<li class="chapter" data-level="" data-path="videos.html"><a href="videos.html"><i class="fa fa-check"></i>External Video Guide</a></li>
<li class="divider"></li>
<li class="book-footer">Quantitative Methods learning line</li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Online Textbook for the Learning Line “Quantitative Methods to Understand E&amp;BI”</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="i05" class="section level1 hasAnchor">
<h1>Lecture 5: Dummy predictors and joint usefulness<a href="i05.html#i05" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<div class="outcomes">
<span class="label">By the end of Lecture 5, you can</span>
<ul>
<li>
encode a two-level or multi-level categorical predictor with dummy variables;
</li>
<li>
interpret dummy coefficients relative to a named reference group;
</li>
<li>
avoid the dummy-variable trap;
</li>
<li>
use an overall or partial F-test to assess joint usefulness;
</li>
<li>
separate adjusted associations from causal or essentialist claims.
</li>
</ul>
</div>
<div id="before-class-19" class="section level2 hasAnchor course-phase phase-before">
<h2>Before class<a href="i05.html#before-class-19" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div class="video-prep">
<p><span class="label">Video preparation</span><br>
Watch Stanford Statistical Learning
<a href="https://www.youtube.com/watch?v=dEBQmiXv9fk&list=PLoROMvodv4rOzrYsAxzQyHb8n_RWNuS1e&index=13">3.5
Extensions of the Linear Model</a>. Focus on qualitative predictors and how a
reference category determines coefficient meaning.</p>
</div>
<p>Review <a href="math-refresher.html#math-refresher">Mathematics Refresher: indicators and reference categories</a>
if needed.</p>
<p>With three categories—<code>all_men</code>, <code>all_women</code>, and <code>mixed</code>—how many dummy
variables are needed in a model that includes an intercept?</p>
<details>
<summary>
Check your preparation
</summary>
<p>Two. One category is the reference group; the intercept represents it, and the
two dummy coefficients compare the remaining categories with it.</p>
</details>
</div>
<div id="in-class-19" class="section level2 hasAnchor course-phase phase-in-class">
<h2>In class<a href="i05.html#in-class-19" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p class="concept-video">
<strong>Stanford explanation (review):</strong>
<a href="https://www.youtube.com/watch?v=dEBQmiXv9fk">3.5 Extensions of the Linear Model</a>.
</p>
<div id="a-two-level-indicator" class="section level3 hasAnchor">
<h3>A two-level indicator<a href="i05.html#a-two-level-indicator" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>For a binary predictor <span class="math inline">\(D_i\in\{0,1\}\)</span>,</p>
<p><span class="math display">\[
E[Y_i\mid D_i]=\beta_0+\beta_1D_i.
\]</span></p>
<p>Then</p>
<p><span class="math display">\[
E[Y_i\mid D_i=0]=\beta_0,
\qquad
E[Y_i\mid D_i=1]=\beta_0+\beta_1.
\]</span></p>
<p>Thus <span class="math inline">\(\beta_1\)</span> is the expected difference between the 1 group and the 0
reference group.</p>
</div>
<div id="more-than-two-categories" class="section level3 hasAnchor">
<h3>More than two categories<a href="i05.html#more-than-two-categories" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>With <span class="math inline">\(G\)</span> categories and an intercept, use <span class="math inline">\(G-1\)</span> dummies. Including all
<span class="math inline">\(G\)</span> dummies plus an intercept creates exact linear dependence because the
dummies sum to 1. This is the <strong>dummy-variable trap</strong>.</p>
<p>R creates the dummies automatically when a predictor is a factor. Set the
reference category deliberately and verify it.</p>
<div class="sourceCode" id="cb164"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb164-1"><a href="i05.html#cb164-1" tabindex="-1"></a><span class="fu">levels</span>(known_gender<span class="sc">$</span>gender)</span></code></pre></div>
<pre><code>## [1] &quot;all_men&quot;   &quot;all_women&quot; &quot;mixed&quot;</code></pre>
<div class="sourceCode" id="cb166"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb166-1"><a href="i05.html#cb166-1" tabindex="-1"></a><span class="fu">contrasts</span>(known_gender<span class="sc">$</span>gender)</span></code></pre></div>
<pre><code>##           all_women mixed
## all_men           0     0
## all_women         1     0
## mixed             0     1</code></pre>
<p>The source categories describe the presenting team as all men, all women, or
mixed. They do not measure the share of women, gender identity beyond the
source categories, or the composition of the full venture.</p>
</div>
<div id="fit-an-adjusted-category-comparison" class="section level3 hasAnchor">
<h3>Fit an adjusted category comparison<a href="i05.html#fit-an-adjusted-category-comparison" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div class="sourceCode" id="cb168"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb168-1"><a href="i05.html#cb168-1" tabindex="-1"></a>gender_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(</span>
<span id="cb168-2"><a href="i05.html#cb168-2" tabindex="-1"></a>  equity_offered_pct <span class="sc">~</span> season <span class="sc">+</span> ask_100k <span class="sc">+</span> gender,</span>
<span id="cb168-3"><a href="i05.html#cb168-3" tabindex="-1"></a>  <span class="at">data =</span> known_gender</span>
<span id="cb168-4"><a href="i05.html#cb168-4" tabindex="-1"></a>)</span>
<span id="cb168-5"><a href="i05.html#cb168-5" tabindex="-1"></a><span class="fu">summary</span>(gender_model)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = equity_offered_pct ~ season + ask_100k + gender, 
##     data = known_gender)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -16.118  -4.778  -1.100   3.220  82.590 
## 
## Coefficients:
##                 Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)     20.83883    0.50649  41.143  &lt; 2e-16 ***
## season          -0.82389    0.04780 -17.238  &lt; 2e-16 ***
## ask_100k        -0.26613    0.05822  -4.571 5.28e-06 ***
## genderall_women  1.28352    0.48102   2.668  0.00771 ** 
## gendermixed      0.12093    0.54115   0.223  0.82320    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 7.612 on 1429 degrees of freedom
## Multiple R-squared:  0.1913, Adjusted R-squared:  0.189 
## F-statistic: 84.49 on 4 and 1429 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>Holding season and requested amount fixed:</p>
<ul>
<li>all-women teams are fitted to offer about 1.28 percentage points more equity
initially than all-men teams;</li>
<li>mixed teams are fitted to differ from all-men teams by about 0.12 percentage
points.</li>
</ul>
<p>The all-women coefficient has a classical p-value of about 0.008; the mixed
coefficient has a p-value of about 0.823. These are two reference-group
comparisons, not a claim that gender causes the offers.</p>
<p>A complete dummy-coefficient interpretation must name both categories, give
the outcome unit, state the predictors held fixed, and preserve the sample and
measurement boundary. For example: “Among pitches with a recorded source
classification, all-women presenting teams are fitted to offer 1.28 equity
percentage points more than all-men presenting teams at the same season and
requested amount.”</p>
<p>Changing the reference group changes coefficient labels, not fitted values or
overall model fit.</p>
<div class="sourceCode" id="cb170"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb170-1"><a href="i05.html#cb170-1" tabindex="-1"></a>known_gender<span class="sc">$</span>gender_women_ref <span class="ot">&lt;-</span> <span class="fu">relevel</span>(known_gender<span class="sc">$</span>gender,</span>
<span id="cb170-2"><a href="i05.html#cb170-2" tabindex="-1"></a>                                         <span class="at">ref =</span> <span class="st">&quot;all_women&quot;</span>)</span>
<span id="cb170-3"><a href="i05.html#cb170-3" tabindex="-1"></a><span class="fu">coef</span>(<span class="fu">lm</span>(equity_offered_pct <span class="sc">~</span> season <span class="sc">+</span> ask_100k <span class="sc">+</span> gender_women_ref,</span>
<span id="cb170-4"><a href="i05.html#cb170-4" tabindex="-1"></a>        <span class="at">data =</span> known_gender))</span></code></pre></div>
<pre><code>##             (Intercept)                  season                ask_100k 
##              22.1223564              -0.8238940              -0.2661283 
## gender_women_refall_men   gender_women_refmixed 
##              -1.2835231              -1.1625889</code></pre>
</div>
<div id="the-overall-f-test-1" class="section level3 hasAnchor">
<h3>The overall F-test<a href="i05.html#the-overall-f-test-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>For <span class="math inline">\(k\)</span> slopes, the overall test is</p>
<p><span class="math display">\[
H_0:\beta_1=\cdots=\beta_k=0
\]</span></p>
<p>against at least one non-zero slope. In R, it appears in <code>summary(model)</code>.
For <code>gender_model</code>, the very small overall p-value says the full set of season,
request, and category predictors is jointly useful relative to an
intercept-only model.</p>
</div>
<div id="a-partial-f-test-for-a-group-of-terms" class="section level3 hasAnchor">
<h3>A partial F-test for a group of terms<a href="i05.html#a-partial-f-test-for-a-group-of-terms" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>An individual t-test asks whether one coefficient is zero. A partial F-test
asks whether several coefficients are jointly zero after retaining other
predictors.</p>
<p>To test whether the two gender dummies add information beyond season and
request:</p>
<p><span class="math display">\[
H_0:\beta_{all\_women}=\beta_{mixed}=0.
\]</span></p>
<div class="sourceCode" id="cb172"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb172-1"><a href="i05.html#cb172-1" tabindex="-1"></a><span class="fu">anova</span>(reduced_gender, gender_model)</span></code></pre></div>
<pre><code>## Analysis of Variance Table
## 
## Model 1: equity_offered_pct ~ season + ask_100k
## Model 2: equity_offered_pct ~ season + ask_100k + gender
##   Res.Df   RSS Df Sum of Sq      F Pr(&gt;F)  
## 1   1431 83228                             
## 2   1429 82792  2    436.25 3.7649 0.0234 *
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>The partial F-test has p-value about 0.023. At 5%, the two source-category
terms are jointly useful in this specification. This statement is not
equivalent to saying every dummy coefficient is individually significant.</p>
<p>The reduced model must be <strong>nested</strong> inside the complete model: it is obtained
by setting the tested coefficients to zero while keeping the same analysis
rows.</p>
</div>
<div id="visualise-adjusted-comparisons" class="section level3 hasAnchor">
<h3>Visualise adjusted comparisons<a href="i05.html#visualise-adjusted-comparisons" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p><img src="I05-dummies-f-tests_files/figure-html/i05-adjusted-gender-plot-1.png" width="672" /></p>
<p>The horizontal axis names the source categories and the vertical axis gives
fitted initial equity in percent. The points compare fitted means at the same
average season and request; the vertical lines are 95% confidence intervals.
They express model-based uncertainty, not causal effects or uncertainty about
how the categories were recorded.</p>
</div>
</div>
<div id="after-class-19" class="section level2 hasAnchor course-phase phase-after">
<h2>After class<a href="i05.html#after-class-19" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="retrieval-13" class="section level3 hasAnchor">
<h3>Retrieval<a href="i05.html#retrieval-13" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<ol style="list-style-type: decimal">
<li>Why are only <span class="math inline">\(G-1\)</span> dummies used with an intercept?</li>
<li>What does a dummy coefficient compare?</li>
<li>What changes when the reference group changes?</li>
<li>What does a partial F-test evaluate?</li>
<li>Why can a joint F-test reject when one individual t-test does not?</li>
</ol>
<details>
<summary>
Check your answers
</summary>
<ol style="list-style-type: decimal">
<li>All <span class="math inline">\(G\)</span> dummies sum to the intercept, creating exact collinearity.</li>
<li>A category with the named reference category, holding other included
predictors fixed.</li>
<li>Coefficient representation changes; fitted values and overall fit do not.</li>
<li>Whether a specified group of coefficients is jointly zero in nested models.</li>
<li>The F-test evaluates the terms together; individual tests ask narrower
questions and may have larger separate uncertainty.</li>
</ol>
</details>
</div>
<div id="practice-13" class="section level3 hasAnchor">
<h3>Practice<a href="i05.html#practice-13" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<ol style="list-style-type: decimal">
<li>Relevel <code>gender</code> so <code>mixed</code> is the reference group and interpret both dummy
coefficients. Save the relevelled model as <code>relevelled_model</code>.</li>
<li>Verify that fitted values are unchanged after releveling by comparing it
with <code>gender_model</code>.</li>
<li>State the hypotheses for the partial F-test of both gender dummies.</li>
<li>Explain why the seven <code>unknown</code> records were excluded rather than treated
as evidence of a substantive fourth group.</li>
<li>Write a 120-word interpretation of the full model that includes the source
measurement boundary and causal limit.</li>
<li>Explain why “the all-women coefficient is 1.28%” is ambiguous, then rewrite
it precisely.</li>
</ol>
<details>
<summary>
Check your answers
</summary>
<ol style="list-style-type: decimal">
<li><p>Use:</p>
<div class="sourceCode" id="cb174"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb174-1"><a href="i05.html#cb174-1" tabindex="-1"></a>mixed_reference <span class="ot">&lt;-</span> <span class="fu">relevel</span>(known_gender<span class="sc">$</span>gender, <span class="at">ref =</span> <span class="st">&quot;mixed&quot;</span>)</span>
<span id="cb174-2"><a href="i05.html#cb174-2" tabindex="-1"></a>relevelled_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(</span>
<span id="cb174-3"><a href="i05.html#cb174-3" tabindex="-1"></a>  equity_offered_pct <span class="sc">~</span> season <span class="sc">+</span> ask_100k <span class="sc">+</span> mixed_reference,</span>
<span id="cb174-4"><a href="i05.html#cb174-4" tabindex="-1"></a>  <span class="at">data =</span> known_gender</span>
<span id="cb174-5"><a href="i05.html#cb174-5" tabindex="-1"></a>)</span>
<span id="cb174-6"><a href="i05.html#cb174-6" tabindex="-1"></a><span class="fu">coef</span>(relevelled_model)</span></code></pre></div>
<p>At fixed season and request, the all-men coefficient is about <span class="math inline">\(-0.121\)</span>
percentage points and the all-women coefficient about <span class="math inline">\(1.163\)</span> percentage
points, each relative to mixed teams.</p></li>
<li><p><code>all.equal(fitted(gender_model), fitted(relevelled_model))</code> returns <code>TRUE</code> up
to numerical tolerance.</p></li>
<li><p><span class="math inline">\(H_0:\beta_{all\_women}=\beta_{mixed}=0\)</span> against at least one non-zero
coefficient, with all-men as the current reference.</p></li>
<li><p><code>unknown</code> records lack a known classification; absence of recorded
information is not a meaningful team-composition category.</p></li>
<li><p>A complete answer reports estimates and units, reference group, held-fixed
variables, uncertainty, selected sample, broad source coding, and the
associational—not causal—scope.</p></li>
<li><p>It confuses percent with percentage points and omits the comparison and
conditioning. A precise version is: “At the same season and requested
amount, all-women presenting teams are fitted to offer 1.28 equity
percentage points more initially than all-men presenting teams.”</p></li>
</ol>
</details>
<p>Continue to <a href="i06.html#i06">Lecture 6: Interactions and polynomial terms</a>.</p>
<p>For a more formal treatment, see James et al., <em>An Introduction to Statistical
Learning</em>, 2nd ed., Sections 3.2.2 and 3.3.1, and
<a href="https://tilburguniversity.on.worldcat.org/oclc/317545871">Nieuwenhuis, <em>Statistical Methods for Business and Economics</em></a>,
Chapters 20–21.</p>
</div>
</div>

</div>
            </section>

          </div>
        </div>
      </div>
<a href="i04.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="i06.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
  "sharing": null,
  "fontsettings": {
    "theme": "white",
    "family": "sans",
    "size": 2
  },
  "edit": null,
  "history": {
    "link": null,
    "text": null
  },
  "view": {
    "link": null,
    "text": null
  },
  "download": null,
  "search": {
    "engine": "fuse",
    "options": null
  },
  "toc": {
    "collapse": "section",
    "scroll_highlight": true
  },
  "toolbar": {
    "position": "fixed"
  }
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
