<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Lecture 6: Interactions and polynomial terms | Online Textbook for the Learning Line “Quantitative Methods to Understand E&amp;BI”</title>
  <meta name="description" content="An online textbook for the learning line Quantitative Methods within Entrepreneurship and Business Innovation Bachelor Program at Tilburg University." />
  <meta name="generator" content="bookdown 0.47 and GitBook 2.6.7" />

  <meta property="og:title" content="Lecture 6: Interactions and polynomial terms | Online Textbook for the Learning Line “Quantitative Methods to Understand E&amp;BI”" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="An online textbook for the learning line Quantitative Methods within Entrepreneurship and Business Innovation Bachelor Program at Tilburg University." />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Lecture 6: Interactions and polynomial terms | Online Textbook for the Learning Line “Quantitative Methods to Understand E&amp;BI”" />
  
  <meta name="twitter:description" content="An online textbook for the learning line Quantitative Methods within Entrepreneurship and Business Innovation Bachelor Program at Tilburg University." />
  




  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="i05.html"/>
<link rel="next" href="i-ep02.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

<link rel="stylesheet" href="styles.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="book-title"><a href="./">QM to Understand E&amp;BI</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Welcome</a></li>
<li class="part"><span><b>I QM Basic</b></span></li>
<li class="chapter" data-level="" data-path="basic-course.html"><a href="basic-course.html"><i class="fa fa-check"></i>QM Basic: Course overview</a></li>
<li class="chapter" data-level="" data-path="b01.html"><a href="b01.html"><i class="fa fa-check"></i>Lecture 1: Introduction to Data Analysis</a></li>
<li class="chapter" data-level="" data-path="b02.html"><a href="b02.html"><i class="fa fa-check"></i>Lecture 2: Probability foundations and random variables</a></li>
<li class="chapter" data-level="" data-path="b03.html"><a href="b03.html"><i class="fa fa-check"></i>Lecture 3: Discrete distributions and expectation</a></li>
<li class="chapter" data-level="" data-path="b-ep01.html"><a href="b-ep01.html"><i class="fa fa-check"></i>Tutorial 1: Evidence and probability foundations</a></li>
<li class="chapter" data-level="" data-path="b04.html"><a href="b04.html"><i class="fa fa-check"></i>Lecture 4: Variance, conditioning, and belief updating</a></li>
<li class="chapter" data-level="" data-path="b05.html"><a href="b05.html"><i class="fa fa-check"></i>Lecture 5: Joint random variables, covariance, and correlation</a></li>
<li class="chapter" data-level="" data-path="b-ep02.html"><a href="b-ep02.html"><i class="fa fa-check"></i>Tutorial 2: Conditioning and relationships</a></li>
<li class="chapter" data-level="" data-path="b06.html"><a href="b06.html"><i class="fa fa-check"></i>Lecture 6: Continuous distributions and the normal model</a></li>
<li class="chapter" data-level="" data-path="b07.html"><a href="b07.html"><i class="fa fa-check"></i>Lecture 7: Samples, parameters, and estimators</a></li>
<li class="chapter" data-level="" data-path="b08.html"><a href="b08.html"><i class="fa fa-check"></i>Lecture 8: Sampling distributions and the central limit theorem</a></li>
<li class="chapter" data-level="" data-path="b-ep03.html"><a href="b-ep03.html"><i class="fa fa-check"></i>Tutorial 3: Sampling and standard errors</a></li>
<li class="chapter" data-level="" data-path="b09.html"><a href="b09.html"><i class="fa fa-check"></i>Lecture 9: Confidence intervals and tests against zero</a></li>
<li class="chapter" data-level="" data-path="b10.html"><a href="b10.html"><i class="fa fa-check"></i>Lecture 10: Hypothesis testing, errors, and power</a></li>
<li class="chapter" data-level="" data-path="b-ep04.html"><a href="b-ep04.html"><i class="fa fa-check"></i>Tutorial 4: Inference and tests against zero</a></li>
<li class="chapter" data-level="" data-path="formula-sheet.html"><a href="formula-sheet.html"><i class="fa fa-check"></i>QM Basic Formula Sheet</a></li>
<li class="chapter" data-level="" data-path="basic-mock-exam.html"><a href="basic-mock-exam.html"><i class="fa fa-check"></i>Mock Exam: QM Basic</a></li>
<li class="part"><span><b>II QM Intermediate</b></span></li>
<li class="chapter" data-level="" data-path="intermediate-course.html"><a href="intermediate-course.html"><i class="fa fa-check"></i>QM Intermediate: Course overview</a></li>
<li class="chapter" data-level="" data-path="i01.html"><a href="i01.html"><i class="fa fa-check"></i>Lecture 1: Simple linear regression</a></li>
<li class="chapter" data-level="" data-path="i02.html"><a href="i02.html"><i class="fa fa-check"></i>Lecture 2: Regression assumptions and coefficient inference</a></li>
<li class="chapter" data-level="" data-path="i03.html"><a href="i03.html"><i class="fa fa-check"></i>Lecture 3: Model fit and overall usefulness</a></li>
<li class="chapter" data-level="" data-path="i-ep01.html"><a href="i-ep01.html"><i class="fa fa-check"></i>Tutorial 1: Simple regression and model usefulness</a></li>
<li class="chapter" data-level="" data-path="i04.html"><a href="i04.html"><i class="fa fa-check"></i>Lecture 4: Multiple linear regression and controls</a></li>
<li class="chapter" data-level="" data-path="i05.html"><a href="i05.html"><i class="fa fa-check"></i>Lecture 5: Dummy predictors and joint usefulness</a></li>
<li class="chapter" data-level="" data-path="i06.html"><a href="i06.html"><i class="fa fa-check"></i>Lecture 6: Interactions and polynomial terms</a></li>
<li class="chapter" data-level="" data-path="i-ep02.html"><a href="i-ep02.html"><i class="fa fa-check"></i>Tutorial 2: Multiple regression and extensions</a></li>
<li class="chapter" data-level="" data-path="intermediate-code-sheet.html"><a href="intermediate-code-sheet.html"><i class="fa fa-check"></i>QM Intermediate Code Sheet</a></li>
<li class="chapter" data-level="" data-path="intermediate-mock-exam.html"><a href="intermediate-mock-exam.html"><i class="fa fa-check"></i>Mock Exam: QM Intermediate</a></li>
<li class="part"><span><b>III QM Advanced</b></span></li>
<li class="chapter" data-level="" data-path="advanced-course.html"><a href="advanced-course.html"><i class="fa fa-check"></i>QM Advanced: Course overview</a></li>
<li class="part"><span><b>IV Supplementary resources</b></span></li>
<li class="chapter" data-level="" data-path="r-refresher.html"><a href="r-refresher.html"><i class="fa fa-check"></i>R Refresher</a></li>
<li class="chapter" data-level="" data-path="math-refresher.html"><a href="math-refresher.html"><i class="fa fa-check"></i>Mathematics Refresher</a></li>
<li class="chapter" data-level="" data-path="videos.html"><a href="videos.html"><i class="fa fa-check"></i>External Video Guide</a></li>
<li class="divider"></li>
<li class="book-footer">Quantitative Methods learning line</li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Online Textbook for the Learning Line “Quantitative Methods to Understand E&amp;BI”</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="i06" class="section level1 hasAnchor">
<h1>Lecture 6: Interactions and polynomial terms<a href="i06.html#i06" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<div class="outcomes">
<span class="label">By the end of Lecture 6, you can</span>
<ul>
<li>
explain an interaction as a slope that depends on another variable;
</li>
<li>
interpret main effects in a model containing an interaction;
</li>
<li>
use centering to make lower-order terms more meaningful;
</li>
<li>
fit and interpret a quadratic term without reading its coefficients separately;
</li>
<li>
apply the hierarchy principle and communicate conditional predictions graphically.
</li>
</ul>
</div>
<div id="before-class-20" class="section level2 hasAnchor course-phase phase-before">
<h2>Before class<a href="i06.html#before-class-20" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div class="video-prep">
<p><span class="label">Video preparation</span><br>
Watch Stanford Statistical Learning
<a href="https://www.youtube.com/watch?v=dEBQmiXv9fk&list=PLoROMvodv4rOzrYsAxzQyHb8n_RWNuS1e&index=13">3.5
Extensions of the Linear Model</a> and
<a href="https://www.youtube.com/watch?v=F-D3lZzYn50&list=PLoROMvodv4rOzrYsAxzQyHb8n_RWNuS1e&index=48">7.1
Polynomials and Step Functions</a>. Focus on why an interaction changes a
slope and why a polynomial remains a linear regression model in its
coefficients.</p>
</div>
<p>Review <a href="math-refresher.html#math-refresher">Mathematics Refresher: products, powers, and centering</a>
if needed.</p>
<p>In the model <span class="math inline">\(Y=\beta_0+\beta_1X+\beta_2D+\beta_3XD+\varepsilon\)</span>, write the
line for <span class="math inline">\(D=0\)</span> and for <span class="math inline">\(D=1\)</span>.</p>
<details>
<summary>
Check your preparation
</summary>
<p>For <span class="math inline">\(D=0\)</span>, <span class="math inline">\(E[Y\mid X,D=0]=\beta_0+\beta_1X\)</span>. For <span class="math inline">\(D=1\)</span>,
<span class="math inline">\(E[Y\mid X,D=1]=(\beta_0+\beta_2)+(\beta_1+\beta_3)X\)</span>.</p>
</details>
</div>
<div id="in-class-20" class="section level2 hasAnchor course-phase phase-in-class">
<h2>In class<a href="i06.html#in-class-20" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p class="concept-video">
<strong>Stanford explanations (review):</strong>
<a href="https://www.youtube.com/watch?v=dEBQmiXv9fk">3.5 Extensions of the Linear Model</a> and
<a href="https://www.youtube.com/watch?v=F-D3lZzYn50">7.1 Polynomials and Step Functions</a>.
</p>
<div id="interaction-means-it-depends" class="section level3 hasAnchor">
<h3>Interaction means “it depends”<a href="i06.html#interaction-means-it-depends" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>An additive model assumes the slope of <span class="math inline">\(X\)</span> is the same at every value of
<span class="math inline">\(Z\)</span>:</p>
<p><span class="math display">\[
E[Y\mid X,Z]=\beta_0+\beta_1X+\beta_2Z.
\]</span></p>
<p>Adding a product allows that slope to vary:</p>
<p><span class="math display">\[
E[Y\mid X,Z]
=\beta_0+\beta_1X+\beta_2Z+\beta_3XZ.
\]</span></p>
<p>The change in the conditional mean for a one-unit increase in <span class="math inline">\(X\)</span> is</p>
<p><span class="math display">\[
\beta_1+\beta_3Z.
\]</span></p>
<p>Thus <span class="math inline">\(\beta_3\)</span> is a <strong>difference in slopes</strong>, not a standalone effect.
Its units combine the variables. If <span class="math inline">\(X\)</span> is measured in seasons and <span class="math inline">\(Z\)</span> is
an indicator, <span class="math inline">\(\beta_3\)</span> is the difference in outcome units per season
between the indicator groups.</p>
</div>
<div id="a-binary-interaction" class="section level3 hasAnchor">
<h3>A binary interaction<a href="i06.html#a-binary-interaction" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>For this example only, <code>women = 1</code> means the source classifies the presenting
team as all-women or mixed; <code>women = 0</code> means all-men. It does not measure a
share of women or the full venture team. Seven unknown records are excluded.</p>
<p>Centre season at its sample mean:</p>
<p><span class="math display">\[
season\_c=season-\overline{season}.
\]</span></p>
<p>Then the lower-order <code>women</code> coefficient compares groups at the average season
rather than at the unobserved Season 0.</p>
<div class="sourceCode" id="cb175"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb175-1"><a href="i06.html#cb175-1" tabindex="-1"></a><span class="fu">summary</span>(interaction_model)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = equity_offered_pct ~ season_c * women + ask_100k, 
##     data = known_gender)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -15.871  -4.742  -1.290   3.412  82.689 
## 
## Coefficients:
##                Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)    13.62479    0.33545  40.616  &lt; 2e-16 ***
## season_c       -0.79938    0.06632 -12.053  &lt; 2e-16 ***
## women           0.80697    0.41171   1.960   0.0502 .  
## ask_100k       -0.26776    0.05834  -4.590 4.83e-06 ***
## season_c:women -0.06146    0.09557  -0.643   0.5203    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 7.62 on 1429 degrees of freedom
## Multiple R-squared:  0.1894, Adjusted R-squared:  0.1871 
## F-statistic: 83.47 on 4 and 1429 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>For all-men teams (<code>women = 0</code>), the fitted season slope is about <span class="math inline">\(-0.799\)</span>
percentage points per season. For teams with women represented, it is</p>
<p><span class="math display">\[
-0.799+(-0.061)=-0.861.
\]</span></p>
<p>The interaction estimate is <span class="math inline">\(-0.061\)</span>, with p-value about 0.520. This model
does not provide evidence that the season trend differs between these two
broad source-defined groups. It also does not prove the slopes are identical.</p>
<p><img src="I06-interactions-polynomials_files/figure-html/i06-interaction-plot-1.png" width="672" /></p>
<p>The horizontal axis is season and the vertical axis is fitted initial equity
at the same average requested amount. Each line represents one source-defined
group; its slope is the fitted change per season for that group, and their
vertical separation is the fitted group difference at a given season. Graph
the model because neither <span class="math inline">\(\beta_1\)</span> nor <span class="math inline">\(\beta_2\)</span> is an overall effect when
an interaction is present.</p>
</div>
<div id="the-hierarchy-principle" class="section level3 hasAnchor">
<h3>The hierarchy principle<a href="i06.html#the-hierarchy-principle" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>If a model contains <span class="math inline">\(XZ\)</span>, ordinarily retain both <span class="math inline">\(X\)</span> and <span class="math inline">\(Z\)</span>, even when
one lower-order term is not individually significant. The lower-order terms
define the lines whose difference the interaction describes.</p>
<p>In R:</p>
<div class="sourceCode" id="cb177"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb177-1"><a href="i06.html#cb177-1" tabindex="-1"></a><span class="fu">lm</span>(y <span class="sc">~</span> x <span class="sc">*</span> z, <span class="at">data =</span> df)  <span class="co"># expands to x + z + x:z</span></span></code></pre></div>
</div>
<div id="polynomial-terms-model-curvature" class="section level3 hasAnchor">
<h3>Polynomial terms model curvature<a href="i06.html#polynomial-terms-model-curvature" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>A quadratic conditional mean is</p>
<p><span class="math display">\[
E[Y\mid X=x]=\beta_0+\beta_1x+\beta_2x^2.
\]</span></p>
<p>It remains a linear regression model because it is linear in the unknown
coefficients <span class="math inline">\(\beta_0,\beta_1,\beta_2\)</span>.</p>
<p>The slope is not constant. A one-unit change from <span class="math inline">\(x\)</span> to <span class="math inline">\(x+1\)</span> changes the
fitted mean by</p>
<p><span class="math display">\[
\beta_1+\beta_2(2x+1).
\]</span></p>
<p>Therefore do not interpret <span class="math inline">\(\beta_1\)</span> as the overall slope while <span class="math inline">\(x^2\)</span> is in
the model. Compare fitted values or graph the curve.</p>
<div class="sourceCode" id="cb178"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb178-1"><a href="i06.html#cb178-1" tabindex="-1"></a><span class="fu">summary</span>(poly_season)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = equity_offered_pct ~ season + I(season^2) + ask_100k, 
##     data = sharks)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -16.154  -4.549  -1.011   3.390  82.000 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) 24.17168    0.82057  29.457  &lt; 2e-16 ***
## season      -1.71323    0.20567  -8.330  &lt; 2e-16 ***
## I(season^2)  0.05103    0.01137   4.489 7.74e-06 ***
## ask_100k    -0.27108    0.05740  -4.723 2.56e-06 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 7.57 on 1437 degrees of freedom
## Multiple R-squared:  0.1981, Adjusted R-squared:  0.1965 
## F-statistic: 118.3 on 3 and 1437 DF,  p-value: &lt; 2.2e-16</code></pre>
<div class="sourceCode" id="cb180"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb180-1"><a href="i06.html#cb180-1" tabindex="-1"></a><span class="fu">anova</span>(linear_season, poly_season)</span></code></pre></div>
<pre><code>## Analysis of Variance Table
## 
## Model 1: equity_offered_pct ~ season + ask_100k
## Model 2: equity_offered_pct ~ season + I(season^2) + ask_100k
##   Res.Df   RSS Df Sum of Sq      F    Pr(&gt;F)    
## 1   1438 83493                                  
## 2   1437 82338  1    1154.5 20.149 7.737e-06 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>The partial F-test for adding <code>season^2</code> has p-value below 0.001 in the
classical model. The fitted curvature is statistically detectable, but the
gain in adjusted <span class="math inline">\(R^2\)</span> and the substantive shape should also be assessed.</p>
<p><img src="I06-interactions-polynomials_files/figure-html/i06-polynomial-plot-1.png" width="672" /></p>
<p>The points are raw season means; the curve holds requested amount at its sample
mean. Do not extrapolate the quadratic beyond Seasons 1–16: polynomials can
turn sharply outside the observed range.</p>
</div>
<div id="extensions-do-not-replace-assumptions" class="section level3 hasAnchor">
<h3>Extensions do not replace assumptions<a href="i06.html#extensions-do-not-replace-assumptions" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Interactions and polynomials make the conditional mean more flexible. They do
not solve dependence, selection, measurement error, heteroskedasticity, or
unmeasured confounding. Choose terms from a substantive question, inspect the
implied predictions, and report the relevant combined effects.</p>
</div>
</div>
<div id="after-class-20" class="section level2 hasAnchor course-phase phase-after">
<h2>After class<a href="i06.html#after-class-20" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="retrieval-14" class="section level3 hasAnchor">
<h3>Retrieval<a href="i06.html#retrieval-14" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<ol style="list-style-type: decimal">
<li>What does an interaction coefficient measure?</li>
<li>Why centre a predictor before interacting it?</li>
<li>State the hierarchy principle.</li>
<li>Why is a quadratic model still a linear regression model?</li>
<li>Why should a polynomial be graphed and not extrapolated casually?</li>
</ol>
<details>
<summary>
Check your answers
</summary>
<ol style="list-style-type: decimal">
<li>How one predictor’s slope changes with the other predictor.</li>
<li>To make lower-order terms refer to a meaningful reference value such as the
sample mean.</li>
<li>Retain the component lower-order terms when including their interaction or
higher-order term.</li>
<li>It is linear in the unknown coefficients, even though it is curved in <span class="math inline">\(x\)</span>.</li>
<li>Component coefficients do not equal one constant slope, and polynomial
curves can behave unrealistically outside the data range.</li>
</ol>
</details>
</div>
<div id="practice-14" class="section level3 hasAnchor">
<h3>Practice<a href="i06.html#practice-14" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<ol style="list-style-type: decimal">
<li>In <span class="math inline">\(Y=10+2X+3D-0.5XD\)</span>, write both group lines and interpret the
interaction.</li>
<li>Fit <code>season * women</code> with and without centering season. Verify that fitted
values and the interaction coefficient remain unchanged.</li>
<li>Fit the linear and quadratic season models and compare adjusted <span class="math inline">\(R^2\)</span>.</li>
<li>Calculate the fitted change from Season 5 to 6 in the quadratic model.</li>
<li>Explain why the non-significant interaction is not evidence that source
gender composition never matters.</li>
<li>State the units of the interaction coefficient in this model and interpret
its estimate without using causal language.</li>
</ol>
<details>
<summary>
Check your answers
</summary>
<ol style="list-style-type: decimal">
<li><p>For <span class="math inline">\(D=0\)</span>, the line is <span class="math inline">\(10+2X\)</span>. For <span class="math inline">\(D=1\)</span>, it is <span class="math inline">\(13+1.5X\)</span>.
The <span class="math inline">\(D=1\)</span> slope is 0.5 units smaller.</p></li>
<li><p>For example:</p>
<div class="sourceCode" id="cb182"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb182-1"><a href="i06.html#cb182-1" tabindex="-1"></a>uncentered <span class="ot">&lt;-</span> <span class="fu">lm</span>(equity_offered_pct <span class="sc">~</span> season <span class="sc">*</span> women <span class="sc">+</span> ask_100k,</span>
<span id="cb182-2"><a href="i06.html#cb182-2" tabindex="-1"></a>                 <span class="at">data =</span> known_gender)</span>
<span id="cb182-3"><a href="i06.html#cb182-3" tabindex="-1"></a>centered <span class="ot">&lt;-</span> <span class="fu">lm</span>(equity_offered_pct <span class="sc">~</span> season_c <span class="sc">*</span> women <span class="sc">+</span> ask_100k,</span>
<span id="cb182-4"><a href="i06.html#cb182-4" tabindex="-1"></a>               <span class="at">data =</span> known_gender)</span>
<span id="cb182-5"><a href="i06.html#cb182-5" tabindex="-1"></a><span class="fu">all.equal</span>(<span class="fu">fitted</span>(uncentered), <span class="fu">fitted</span>(centered))</span>
<span id="cb182-6"><a href="i06.html#cb182-6" tabindex="-1"></a><span class="fu">coef</span>(uncentered)[<span class="st">&quot;season:women&quot;</span>]</span>
<span id="cb182-7"><a href="i06.html#cb182-7" tabindex="-1"></a><span class="fu">coef</span>(centered)[<span class="st">&quot;season_c:women&quot;</span>]</span></code></pre></div>
<p>The fitted values agree and both interaction estimates are about
<span class="math inline">\(-0.0615\)</span>. Centering changes the intercept and lower-order group
coefficient, not fitted values, the interaction estimate, or model fit.</p></li>
<li><p>Extract with <code>summary(model)$adj.r.squared</code>; adjusted <span class="math inline">\(R^2\)</span> is about
0.186 for the linear model and 0.196 for the quadratic model.</p></li>
<li><p>With estimates <span class="math inline">\(\beta_1\approx-1.713\)</span> and
<span class="math inline">\(\beta_2\approx0.0510\)</span>, the change is
<span class="math inline">\(\beta_1+\beta_2(2\cdot5+1)\approx-1.15\)</span> percentage points.</p></li>
<li><p>The test concerns one operationalisation, sample, model, and interaction;
limited precision or misspecification can remain, and the source category
is broad.</p></li>
<li><p>The unit is equity percentage points per season as a difference between
groups. Holding requested amount fixed, the fitted seasonal slope for teams
with women represented is 0.0615 percentage points per season more negative
than for all-men teams; the two-sided test does not distinguish this
difference from zero at 5%.</p></li>
</ol>
</details>
<p>Continue to <a href="i-ep02.html#i-ep02">Tutorial 2: Multiple regression and extensions</a>.</p>
<p>For a more formal treatment, see James et al., <em>An Introduction to Statistical
Learning</em>, 2nd ed., Section 3.3.2 and Sections 3.6.4–3.6.6, and
<a href="https://tilburguniversity.on.worldcat.org/oclc/317545871">Nieuwenhuis, <em>Statistical Methods for Business and Economics</em></a>,
Chapter 21.</p>
</div>
</div>

</div>
            </section>

          </div>
        </div>
      </div>
<a href="i05.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="i-ep02.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
  "sharing": null,
  "fontsettings": {
    "theme": "white",
    "family": "sans",
    "size": 2
  },
  "edit": null,
  "history": {
    "link": null,
    "text": null
  },
  "view": {
    "link": null,
    "text": null
  },
  "download": null,
  "search": {
    "engine": "fuse",
    "options": null
  },
  "toc": {
    "collapse": "section",
    "scroll_highlight": true
  },
  "toolbar": {
    "position": "fixed"
  }
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
